import React, { createContext, useContext, useState, useEffect } from 'react';

// ── Supported Indian Languages ──
export const LANGUAGES = [
  { code: 'en', label: 'English', native: 'English' },
  { code: 'hi', label: 'Hindi', native: 'हिंदी' },
  { code: 'or', label: 'Odia', native: 'ଓଡ଼ିଆ' },
  { code: 'te', label: 'Telugu', native: 'తెలుగు' },
  { code: 'ta', label: 'Tamil', native: 'தமிழ்' },
  { code: 'bn', label: 'Bengali', native: 'বাংলা' },
];

// ── Translation Dictionary ──
export const translations = {
  en: {
    appName: 'SUOWMRS',
    appSubtitle: 'Water Monitoring & Reuse',
    dashboard: 'Overview',
    waterMonitoring: 'Water Monitoring',
    alerts: 'Alerts & History',
    storage: 'Underground Storage',
    waterReuse: 'Water Reuse & Quality',
    weather: 'Weather Forecast',
    complaints: 'Citizen Portal',
    sos: 'Emergency SOS',
    maintenance: 'Maintenance Hub',
    systemHealth: 'System Health',
    sensors: 'Sensors & Valves',
    esp32Diagnostics: 'ESP32 Controller',
    sensorDiagnostics: 'Sensors & Calibration',
    componentsHealth: 'Actuators & Relays',
    workOrders: 'Work Orders & Tickets',
    adminDashboard: 'Municipality Control',
    userApprovals: 'User Approvals',
    adminMap: 'GIS Flood Mapping',
    adminSystems: 'Multi-System Grid',
    adminComplaints: 'Citizen Reports',
    adminAnalytics: 'Predictive Analytics',
    aiPrediction: 'AI Flood Prediction',
    myProfile: 'My Profile & Password',
    signOut: 'Sign Out',
    userVerificationTitle: 'User Verification & Approvals',
    userVerificationDesc: 'Verify incoming Resident and Technician registrations before granting access.',
    pending: 'Pending',
    verified: 'Verified',
    rejected: 'Rejected',
    all: 'All',
    refresh: 'Refresh',
    searchUser: 'Search users...',
    residentOps: 'Resident Operations',
    technicianSuite: 'Technician Suite',
    municipalityAdmin: 'Municipality Admin',
    live: 'Live',
    demoUser: 'Demo User',
    waterMonitoringTitle: 'Water Monitoring Dashboard',
    emergencySos: 'Emergency SOS',
    reportIssue: 'Report Issue',
    waterLevel: 'Water Level',
    undergroundStorage: 'Underground Storage',
    solenoidValve: 'Solenoid Valve',
    liveDrainageTrend: 'Live Drainage Trend',
    alertFeed: 'Alert Feed',
    treatmentTitle: 'Water Treatment & Reuse Lifecycle',
    approvedReuseChannels: 'Approved Reuse Channels',
    gardening: 'Gardening',
    cleaning: 'Cleaning',
    irrigation: 'Irrigation',
    construction: 'Construction',
    industrial: 'Industrial',
    manualOverride: 'Manual Override',
    openValve: 'Open Valve',
    closeValve: 'Close Valve',
    totalStored: 'Total Stored',
    treatedWater: 'Treated Water',
    availableReuse: 'Available for Reuse',
    language: 'Language',
    role: 'Role',
    // Dynamic Backend Data & Alerts
    alert_normal: 'Water level normal at {level}%. Drainage flow stable.',
    alert_warning: 'Caution: Rising water level at {level}%. Monitoring closely.',
    alert_danger: 'HIGH RISK: Water level at {level}%! Diverter valve auto-opened.',
    alert_critical: 'CRITICAL FLOOD ALERT: Water level at {level}%! Emergency protocol active.',
    status_normal: 'NORMAL',
    status_warning: 'WARNING',
    status_danger: 'HIGH RISK',
    status_critical: 'CRITICAL FLOOD',
    status_high: 'HIGH',
    status_moderate: 'MODERATE',
    status_low: 'LOW',
    status_none: 'NONE',
    valve_diverting: 'Diverting Flow',
    valve_standby: 'Standby',
    valve_auto: 'Automatic',
    valve_manual: 'Manual',
    activeTank: 'Active Tank',
    current: 'Current',
    capacity: 'Capacity',
    available: 'Available',
    inflowRate: 'Inflow Rate',
    empty: 'Empty',
    full: 'Full',
    minToday: 'MIN TODAY',
    avgToday: 'AVG TODAY',
    peakToday: 'PEAK TODAY',
    unread: 'Unread',
    noAlertsHealthy: 'No alerts — System healthy',
    autoUpdatesStream: 'Auto-updates from live Socket.io stream',
    quality: 'Quality',
    quality_good: 'GOOD',
    quality_excellent: 'EXCELLENT',
    quality_moderate: 'MODERATE',
    collected: 'Collected',
    efficiency: 'Efficiency',
    distributed: 'Distributed',
    treatmentPhase: 'Phase 4: Stored Inflow → Filtration → Approved Municipal Distribution',
    sensorsActive: 'Sensors Active',
    offline: 'Offline',

    // TTS (Text-to-Speech) Dashboard Voice Keys
    tts_listen: 'Listen',
    tts_listenAll: 'Listen Dashboard',
    tts_stop: 'Stop',
    tts_waterLevel: 'Live drainage water level is {level} percent. System condition is {status}.',
    tts_storage: 'Underground storage is {fill} percent full. Current volume is {volume} litres out of {capacity} litres. {available} litres available.',
    tts_valve: 'Solenoid valve status is {status}. Mode is automatic. Trigger level is 75 percent.',
    tts_floodBannerCritical: 'Critical flood threshold exceeded. Drainage level is {level} percent. Underground diverter valve is {valve}.',
    tts_floodBannerWarning: 'Elevated water level detected. Drainage level is {level} percent. Underground diverter valve is {valve}.',
    tts_dashSummary: 'Dashboard summary. Water level is {level} percent, status {status}. Storage is {fill} percent full with {volume} litres stored. Valve is {valve}. {alert}',
    tts_noAlerts: 'No active alerts. System is healthy.',
    tts_alertCount: '{count} active alerts.',
    tts_sirenWarning: 'Siren alert: Valve has been opened.',

    // Landing Page & Footer Keys
    home: 'Home',
    residentPortal: 'Resident Portal',
    signIn: 'Sign In',
    heroBadge: 'Smart Underground Overflow Water Management and Reuse System (SUOWMRS)',
    heroTitle1: 'One Smart Platform for',
    heroTitle2: 'Flood, Rainwater & Greywater Management',
    heroDesc: 'A next-generation AI & IoT platform for smart flood prevention, rainwater harvesting, greywater recycling, and real-time water management—all in one intelligent underground system.',
    sensorsMonitored: 'Sensors Monitored',
    liveWaterLevel: 'Live Water Level',
    storedWater: 'Stored Water',
    autoValveStatus: 'Auto Valve Status',
    totalFloodPrevented: 'Total Flood Volume Prevented',
    activeIoTNodes: 'Active IoT Sensor Nodes',
    systemUptime: 'System Telemetry Uptime',
    treatedWaterReused: 'Treated Water Reused',
    ecosystemBlueprint: 'The 7-Phase SUOWMRS Ecosystem',
    tailoredExperience: 'Built for 3 Essential User Roles',
    openResidentView: 'Open Resident View',
    technicianHub: 'Technician Hub',
    footerFoundation: 'SUOWMRS Smart Water Platform',
    allRightsReserved: 'All rights reserved.',
    step1Title: '1. IoT Sensing',
    step1Desc: 'Ultrasonic depth sensors track drain water column levels every 5 seconds.',
    step2Title: '2. Auto Diversion',
    step2Desc: 'Solenoid valves actuate at 75% depth threshold, funneling runoff underground.',
    step3Title: '3. Filtration',
    step3Desc: 'Captured water undergoes multi-stage treatment to clear debris & turbidity.',
    step4Title: '4. City Reuse',
    step4Desc: 'Purified water is allocated for parks, irrigation, street washing & firefighting.',

    // 7 Phases
    phase1Title: '1. IoT Drain Sensing',
    phase1Desc: 'Ultrasonic sensors measure real-time water column depth every 5 seconds.',
    phase2Title: '2. Auto Diversion Valves',
    phase2Desc: 'Solenoid diverter valves trigger automatically at 75% depth threshold.',
    phase3Title: '3. Alerts & Early Warnings',
    phase3Desc: 'Instant SMS & portal notifications sent to residents and city emergency teams.',
    phase4Title: '4. Underground Storage Sump',
    phase4Desc: 'High-capacity subterranean sumps hold over 50,000L of storm runoff.',
    phase5Title: '5. Filtration & Quality Check',
    phase5Desc: 'Multi-stage mesh & sedimentation filtration purifies runoff for non-potable use.',
    phase6Title: '6. Municipality Control Center',
    phase6Desc: 'Central GIS map & system health portal for city engineers and operators.',
    phase7Title: '7. AI Flood Risk Engine',
    phase7Desc: 'Machine learning predicts flood saturation & rainfall runoff 4 hours in advance.',

    // Roles
    role1Title: 'Resident Operations',
    role1Desc: 'Live water gauges, flood early warnings, SOS emergency trigger, citizen complaint submission, and water reuse availability.',
    role2Title: 'Technician Suite',
    role2Desc: 'Hardware telemetry, ESP32 calibration, solenoid valve overrides, pump health inspections, and predictive maintenance schedules.',
    role3Title: 'Municipality Admin',
    role3Desc: 'City-wide flood GIS mapping, multi-system status aggregates, rapid emergency dispatch, and AI hydrological analytics.',

    // FAQs
    faq1Q: 'How does SUOWMRS detect and prevent urban flooding automatically?',
    faq1A: 'IoT ultrasonic sensors mounted inside drainage channels continuously measure water column depth. When levels breach the 75% depth threshold, the system automatically triggers solenoid diverter valves to open, funneling storm runoff into underground storage reservoirs before streets flood.',
    faq2Q: 'Is the collected flood water safe for municipal reuse?',
    faq2A: 'Yes! The collected water goes through an active treatment pipeline featuring multi-stage filtration. The purified water is designated for approved non-potable municipal uses such as agricultural irrigation, park gardening, street washing, and firefighter emergency reserves.',
    faq3Q: 'What role does the AI Flood Prediction Engine play?',
    faq3A: 'The Phase 7 AI Flood Engine combines live IoT telemetry, historical rainfall patterns, and real-time weather forecasts to calculate a Drainage Saturation Index (DSI). It predicts flood risk up to 4 hours in advance so city authorities can take proactive preventative actions.',
    faq4Q: 'Can field technicians manage hardware diagnostics remotely?',
    faq4A: 'Absolutely. Technicians have a dedicated Technician Suite allowing them to view ESP32 controller diagnostics, sensor calibration parameters, solenoid relay states, and log maintenance work orders directly from the platform.',

    // Features Showcase Section
    featuresBadge: 'System Capabilities',
    featuresTitle: 'Comprehensive Features & Platform Modules',
    featuresSubtitle: 'Everything you need to monitor, control, and reuse storm water across your city.',
    feat1Title: 'IoT Water Telemetry',
    feat1Desc: 'Real-time ultrasonic depth sensing, flow rates, RSSI signal telemetry across city wards.',
    feat2Title: 'Underground Sump Storage',
    feat2Desc: 'Subterranean holding sumps managing 50,000L+ storm runoff with active volume gauges.',
    feat3Title: 'Water Filtration & Reuse',
    feat3Desc: 'Multi-stage filtration feeding gardening, street cleaning, irrigation & firefighting.',
    feat4Title: 'AI Flood Prediction Engine',
    feat4Desc: 'Machine learning calculating Drainage Saturation Index (DSI) 4 hours in advance.',
    feat5Title: 'GIS Flood Map & Control Grid',
    feat5Desc: 'Interactive spatial mapping, ward flood risk heatmaps, and emergency team dispatch.',
    feat6Title: 'Citizen Portal & Emergency SOS',
    feat6Desc: 'Instant emergency SOS dispatch and geotagged community issue complaint portal.',
    feat7Title: 'Technician Maintenance Suite',
    feat7Desc: 'ESP32 controller diagnostics, sensor calibration, relay controls, and work order tickets.',
    feat8Title: 'Weather & Monsoon Forecast',
    feat8Desc: 'Rainfall radar integration, precipitation probability, and monsoon risk analytics.',

    automatedLifecycle: 'Automated Lifecycle',
    howItWorksTitle: 'How SUOWMRS Works in 4 Steps',
    architecturalBlueprint: 'Architectural Blueprint',
    explorePhase: 'Explore phase',
    faqTitle: 'Frequently Asked Questions',
    faqSubtitle: 'Got Questions? We Have Answers.',

    // Common & Alerts Page UI keys
    markAllRead: 'Mark All Read',
    searchAlertsPlaceholder: 'Search alerts by message or location...',
    allClear: 'All Clear',
    noAlertsFilter: 'No alerts match the current filter.',
    alertStreamSubtitle: 'Real-time alert stream · {total} total records · Auto-refreshes every 30s',
    justNow: 'Just now',
    minutesAgo: '{m}m ago',
    hoursAgo: '{h}h ago',
    daysAgo: '{d}d ago',
    depth: 'Depth',
    status: 'Status',
    todayPeak: 'Today Peak',
    todayAvg: 'Today Avg',
    state: 'State',
    triggerLevel: 'Trigger Level',
    mode: 'Mode',
    relay: 'Relay',
    criticalFloodBanner: '🚨 Critical Flood Threshold Exceeded!',
    elevatedWaterBanner: '⚠️ Elevated Water Level Detected',
    excessInflow: 'Excess inflow',
    primarySumpLevel: 'Primary Sump Level',
    peak24hWaterLevel: '24h Peak Water Level',
    maxRecordedToday: 'Max recorded today',
    flowVelocity: 'Drainage Flow Velocity',
    normalDischargeSpeed: 'Normal Discharge Speed',
    sensorTelemetry: 'IoT Sensor Telemetry',
    linePowerStable: 'Line Power Stable',
    page: 'Page',
    of: 'of',
    pageOf: 'Page {page} of {pages} · {total} alerts',
    previous: 'Previous',
    next: 'Next',
    showingPage: 'Showing Page {page} of {pages} ({total} total systems)',

    // Weather Page keys
    currentConditions: 'Current Conditions',
    rainfallSuffix: 'mm/hr rainfall',
    intensitySuffix: 'intensity',
    humiditySuffix: 'humidity',
    floodRiskLevel: 'Flood Risk Level',
    temperature: 'Temperature',
    humidity: 'Humidity',
    windSpeed: 'Wind Speed',
    cloudCover: 'Cloud Cover',
    hourlyRainfallForecast: 'Hourly Rainfall Forecast',
    forecastSummary: 'Forecast Summary',
    expectedTotalRainfall: 'Expected Total Rainfall',
    overNextHours: 'over next {hours}h',
    currentIntensity: 'Current Intensity',
    forecastDuration: 'Forecast Duration',
    untilConditionsClear: 'until conditions clear',
    drainageImpact: 'Drainage Impact',
    estimatedDrainageLoad: 'estimated drainage load',
    weatherEngineNote: 'Weather data feeds directly into the AI Flood Prediction Engine (Phase 7) for real-time risk calculation.',
    weatherSubtitle: '{city}, {state} · Hydrological risk integration · Auto-refresh 60s',
    now: 'Now',
    risk_high_desc: 'Heavy rainfall detected. Drainage systems under stress. Flood risk elevated.',
    risk_moderate_desc: 'Moderate rainfall. Monitor water levels. Review drainage capacity.',
    risk_low_desc: 'Light rainfall. Systems operating normally. No immediate risk.',
    risk_none_desc: 'No rainfall detected. Clear conditions. All systems green.',
    cond_heavy_monsoon: 'Monsoon Thunderstorm with Active Inundation Alert',
    cond_light_rain: 'Light Monsoon Showers',
    cond_moderate_rain: 'Moderate Rainfall',
    cond_clear: 'Clear Skies',
    cond_thunderstorm: 'Severe Thunderstorm Alert',
    intensity_clear: 'Clear',
    intensity_light: 'Light Rain',
    intensity_moderate: 'Moderate',
    intensity_heavy: 'Heavy Rain',
    intensity_violent: 'Violent',
    impact_critical: 'Critical',
    impact_elevated: 'Elevated',
    impact_normal: 'Normal',
    quality_good: 'Good',
    quality_excellent: 'Excellent',
    quality_moderate: 'Moderate',
    quality_poor: 'Poor',
    pipeline: 'Treatment Pipeline',
    waterQuality: 'Water Quality',
    purificationEfficiency: 'Purification Efficiency',
    distributed: 'distributed',
    allocatedSuffix: 'of allocated',
    swal_valve_open_title: 'Open Solenoid Diverter Valve?',
    swal_valve_close_title: 'Close Solenoid Diverter Valve?',
    swal_valve_open_desc: 'Manually opening the valve will immediately divert drainage water into the underground storage reservoir.',
    swal_valve_close_desc: 'Closing the valve will halt underground storage diversion and keep the main storm drainage pathway active.',
    swal_confirm_open_valve: 'Confirm Open Valve',
    swal_confirm_close_valve: 'Confirm Close Valve',
    swal_cancel: 'Cancel',
    swal_confirm: 'Confirm',
    swal_diversion_title: 'Initiate Emergency Water Diversion?',
    swal_diversion_heading: 'Critical Storm Drainage Action',
    swal_diversion_desc: 'Actuating the underground solenoid diverter valve will instantly channel excess stormwater from {systemId} into the underground cistern buffer.',
    swal_diversion_confirm: 'Yes, Divert Water Now',
    swal_location: 'Location',
    swal_current_water_level: 'Current Water Level',
    swal_storage_cistern: 'Storage Cistern',
    swal_critical_badge: 'CRITICAL',
    swal_capacity_available: 'Capacity Available',
    swal_sos_title: 'Trigger Emergency SOS Dispatch?',
    swal_sos_heading: 'Critical Disaster Response Warning',
    swal_sos_desc: 'This will instantly transmit high-priority alert coordinates to the Municipal Flood Control Room and local emergency personnel.',
    swal_sos_confirm: 'Yes, Dispatch SOS',
    swal_reboot_title: 'Reboot ESP32 Controller?',
    swal_reboot_desc: 'Telemetry streaming will pause for approximately 3-5 seconds while the microcontroller restarts.',
    swal_reboot_confirm: 'Yes, Reboot Node',
    swal_reboot_success_title: 'Reboot Signal Sent',
    swal_reboot_success_desc: 'The ESP32 controller has been instructed to perform a soft system reset.',
  },
  hi: {
    appName: 'SUOWMRS',
    appSubtitle: 'जल निगरानी और पुनर्उपयोग',
    dashboard: 'अवलोकन',
    waterMonitoring: 'जल निगरानी',
    alerts: 'अलर्ट और इतिहास',
    storage: 'भूमिगत भंडारण',
    waterReuse: 'जल पुनर्उपयोग और गुणवत्ता',
    weather: 'मौसम पूर्वानुमान',
    complaints: 'नागरिक पोर्टल',
    sos: 'आपातकालीन SOS',
    maintenance: 'रखरखाव केंद्र',
    systemHealth: 'सिस्टम स्वास्थ्य',
    sensors: 'सेंसर और वाल्व',
    esp32Diagnostics: 'ईएसपी32 नियंत्रक',
    sensorDiagnostics: 'सेंसर और अंशांकन',
    componentsHealth: 'एक्चुएटर और रिले',
    workOrders: 'कार्य आदेश और टिकट',
    adminDashboard: 'नगरपालिका नियंत्रण',
    userApprovals: 'उपयोगकर्ता अनुमोदन',
    adminMap: 'GIS बाढ़ मानचित्र',
    adminSystems: 'मल्टी-सिस्टम ग्रिड',
    adminComplaints: 'नागरिक रिपोर्ट',
    adminAnalytics: 'पूर्वानुमान विश्लेषण',
    aiPrediction: 'एआई बाढ़ पूर्वानुमान',
    myProfile: 'मेरी प्रोफ़ाइल और पासवर्ड',
    signOut: 'साइन आउट',
    userVerificationTitle: 'उपयोगकर्ता सत्यापन और अनुमोदन',
    userVerificationDesc: 'नेटवर्क एक्सेस देने से पहले नए निवासी और तकनीशियन पंजीकरण का सत्यापन करें।',
    pending: 'लंबित',
    verified: 'सत्यापित',
    rejected: 'अस्वीकृत',
    all: 'सभी',
    refresh: 'रिफ़्रेश',
    searchUser: 'उपयोगकर्ता खोजें...',
    residentOps: 'निवासी संचालन',
    technicianSuite: 'तकनीशियन सूट',
    municipalityAdmin: 'नगरपालिका प्रशासन',
    live: 'लाइव',
    demoUser: 'डेमो उपयोगकर्ता',
    waterMonitoringTitle: 'जल निगरानी डैशबोर्ड',
    emergencySos: 'आपातकालीन SOS',
    reportIssue: 'समस्या रिपोर्ट करें',
    waterLevel: 'जल स्तर',
    undergroundStorage: 'भूमिगत भंडार',
    solenoidValve: 'सोलेनॉइड वाल्व',
    liveDrainageTrend: 'लाइव जल स्तर प्रवृत्ति',
    alertFeed: 'अलर्ट फ़ीड',
    treatmentTitle: 'जल उपचार और पुनर्उपयोग जीवनचक्र',
    approvedReuseChannels: 'स्वीकृत पुनर्उपयोग चैनल',
    gardening: 'बागवानी',
    cleaning: 'सफाई',
    irrigation: 'सिंचाई',
    construction: 'निर्माण',
    industrial: 'औद्योगिक',
    manualOverride: 'मैनुअल ओवरराइड',
    openValve: 'वाल्व खोलें',
    closeValve: 'वाल्व बंद करें',
    totalStored: 'कुल संग्रहित',
    treatedWater: 'उपचारित जल',
    availableReuse: 'पुनर्उपयोग के लिए उपलब्ध',
    language: 'भाषा',
    role: 'भूमिका',
    // Dynamic Backend Data & Alerts
    alert_normal: 'जल स्तर {level}% पर सामान्य। जल निकासी स्थिर।',
    alert_warning: 'सावधानी: जल स्तर बढ़कर {level}% हुआ। निगरानी जारी।',
    alert_danger: 'उच्च जोखिम: जल स्तर {level}% पर! डायवर्टर वाल्व स्वचालित रूप से खुला।',
    alert_critical: 'गंभीर बाढ़ चेतावनी: जल स्तर {level}%! आपातकालीन प्रोटोकॉल सक्रिय।',
    status_normal: 'सामान्य',
    status_warning: 'चेतावनी',
    status_danger: 'उच्च जोखिम',
    status_critical: 'गंभीर बाढ़',
    status_high: 'उच्च जोखिम',
    status_moderate: 'मध्यम',
    status_low: 'कम',
    status_none: 'सुरक्षित',
    valve_diverting: 'प्रवाह मोड़ रहा है',
    valve_standby: 'स्टैंडबाय',
    valve_auto: 'स्वचालित',
    valve_manual: 'मैनुअल',
    activeTank: 'सक्रिय टैंक',
    current: 'वर्तमान',
    capacity: 'क्षमता',
    available: 'उपलब्ध',
    inflowRate: 'अंतर्प्रवाह दर',
    empty: 'खाली',
    full: 'भरा हुआ',
    minToday: 'न्यूनतम आज',
    avgToday: 'औसत आज',
    peakToday: 'चरम आज',
    unread: 'अपठित',
    noAlertsHealthy: 'कोई अलर्ट नहीं — सिस्टम स्वस्थ',
    autoUpdatesStream: 'लाइव Socket.io स्ट्रीम से स्वतः अपडेट',
    quality: 'गुणवत्ता',
    quality_good: 'उत्तम',
    quality_excellent: 'अति उत्तम',
    quality_moderate: 'मध्यम',
    collected: 'एकत्रित',
    efficiency: 'दक्षता',
    distributed: 'वितरित',
    treatmentPhase: 'चरण 4: संग्रहित अंतर्प्रवाह → निस्पंदन → स्वीकृत नगर वितरण',
    sensorsActive: 'सेंसर सक्रिय',
    offline: 'ऑफ़लाइन',

    // TTS (Text-to-Speech) डैशबोर्ड ध्वनि कुंजियाँ
    tts_listen: 'सुनें',
    tts_listenAll: 'डैशबोर्ड सुनें',
    tts_stop: 'रोकें',
    tts_waterLevel: 'लाइव जल निकासी स्तर {level} प्रतिशत है। सिस्टम स्थिति {status} है।',
    tts_storage: 'भूमिगत भंडार {fill} प्रतिशत भरा है। वर्तमान मात्रा {volume} लीटर है, कुल क्षमता {capacity} लीटर। {available} लीटर उपलब्ध।',
    tts_valve: 'सोलेनॉइड वाल्व की स्थिति {status} है। मोड स्वचालित है। ट्रिगर स्तर 75 प्रतिशत।',
    tts_floodBannerCritical: 'गंभीर बाढ़ सीमा पार! जल स्तर {level} प्रतिशत। डायवर्टर वाल्व {valve} है।',
    tts_floodBannerWarning: 'जल स्तर बढ़ा हुआ। जल स्तर {level} प्रतिशत। डायवर्टर वाल्व {valve} है।',
    tts_dashSummary: 'डैशबोर्ड सारांश। जल स्तर {level} प्रतिशत, स्थिति {status}। भंडार {fill} प्रतिशत भरा, {volume} लीटर संग्रहित। वाल्व {valve}। {alert}',
    tts_noAlerts: 'कोई सक्रिय अलर्ट नहीं। सिस्टम स्वस्थ है।',
    tts_alertCount: '{count} सक्रिय अलर्ट।',
    tts_sirenWarning: 'सायरन चेतावनी: वाल्व खोला गया है।',

    // Landing Page & Footer Keys
    home: 'होम',
    residentPortal: 'निवासी पोर्टल',
    signIn: 'साइन इन',
    liveApp: 'लाइव ऐप',
    heroBadge: 'स्मार्ट भूमिगत ओवरफ्लो और जल निगरानी / पुनर्उपयोग प्रणाली',
    heroTitle1: 'आगामी पीढ़ी का एआई और आईओटी प्लेटफॉर्म',
    heroTitle2: 'बाढ़ रोकथाम और जल पुनर्उपयोग',
    heroDesc: 'SUOWMRS शहरी बाढ़ संकट को स्थायी जल परिसंपत्तियों में परिवर्तित करता है। वास्तविक समय नाले की सेंसिंग से लेकर भूमिगत ऑटो-डायवर्जन और एआई पूर्वानुमान तक।',
    sensorsMonitored: 'सेंसर मॉनिटर किए गए',
    liveWaterLevel: 'लाइव जल स्तर',
    storedWater: 'संग्रहित जल',
    autoValveStatus: 'ऑटो वाल्व स्थिति',
    totalFloodPrevented: 'कुल रोकथाम बाढ़ जल',
    activeIoTNodes: 'सक्रिय IoT सेंसर नोड्स',
    systemUptime: 'सिस्टम टेलीमेट्री अपटाइम',
    treatedWaterReused: 'उपचारित जल पुनर्उपयोग',
    ecosystemBlueprint: '7-चरण SUOWMRS पारिस्थितिकी तंत्र',
    tailoredExperience: '3 आवश्यक उपयोगकर्ता भूमिकाओं के लिए निर्मित',
    openResidentView: 'निवासी दृश्य खोलें',
    technicianHub: 'तकनीशियन हब',
    footerFoundation: 'SUOWMRS स्मार्ट जल मंच',
    allRightsReserved: 'सर्वाधिकार सुरक्षित।',
    step1Title: '1. IoT सेंसिंग',
    step1Desc: 'अल्ट्रासोनिक गहराई सेंसर हर 5 सेकंड में नाले के जल स्तर को ट्रैक करते हैं।',
    step2Title: '2. स्वतः डायवर्जन',
    step2Desc: '75% गहराई पर सोलेनॉइड वाल्व स्वतः खुलते हैं और पानी को भूमिगत मोड़ते हैं।',
    step3Title: '3. निस्पंदन',
    step3Desc: 'एकत्रित पानी मलबे और मैल को साफ करने के लिए बहु-स्तरीय उपचार से गुजरता है।',
    step4Title: '4. नगर पुनर्उपयोग',
    step4Desc: 'शुद्ध पानी पार्कों, सिंचाई, सड़क धुलाई और अग्निशमन के लिए आवंटित किया जाता है।',

    // 7 Phases
    phase1Title: '1. IoT नाला सेंसिंग',
    phase1Desc: 'अल्ट्रासोनिक सेंसर हर 5 सेकंड में वास्तविक समय जल गहराई मापते हैं।',
    phase2Title: '2. स्वतः डायवर्जन वाल्व',
    phase2Desc: '75% गहराई सीमा पर सोलेनॉइड डायवर्टर वाल्व स्वतः चालू होते हैं।',
    phase3Title: '3. अलर्ट और पूर्व चेतावनियां',
    phase3Desc: 'नागरिकों और आपातकालीन टीमों को तत्काल एसएमएस व पोर्टल सूचनाएं।',
    phase4Title: '4. भूमिगत भंडारण संप',
    phase4Desc: 'उच्च क्षमता वाले भूमिगत संप 50,000L से अधिक बाढ़ जल संचित करते हैं।',
    phase5Title: '5. निस्पंदन और गुणवत्ता जांच',
    phase5Desc: 'बहु-स्तरीय निस्पंदन पानी को गैर-पेयजल उपयोग के लिए शुद्ध करता है।',
    phase6Title: '6. नगरपालिका नियंत्रण केंद्र',
    phase6Desc: 'शहर के इंजीनियरों और ऑपरेटरों के लिए केंद्रीय जीआईएस मानचित्र और स्वास्थ्य पोर्टल।',
    phase7Title: '7. AI बाढ़ जोखिम इंजन',
    phase7Desc: 'मशीन लर्निंग 4 घंटे पहले ही बाढ़ संतृप्ति और वर्षा जल का पूर्वानुमान लगाती है।',

    // Roles
    role1Title: 'निवासी संचालन',
    role1Desc: 'लाइव जल गेज, बाढ़ पूर्व चेतावनी, एसओएस आपातकालीन ट्रिगर, नागरिक शिकायत और जल पुनर्उपयोग उपलब्ध।',
    role2Title: 'तकनीशियन सूट',
    role2Desc: 'हार्डवेयर टेलीमेट्री, ईएसपी32 अंशांकन, वाल्व ओवरराइड, पंप स्वास्थ्य जांच और निवारक रखरखाव शेड्यूल।',
    role3Title: 'नगरपालिका प्रशासन',
    role3Desc: 'शहर-व्यापी बाढ़ जीआईएस मैपिंग, मल्टी-सिस्टम स्थिति समुच्चय, त्वरित आपातकालीन प्रेषण और एआई जल विज्ञान विश्लेषण।',

    // FAQs
    faq1Q: 'SUOWMRS स्वचालित रूप से शहरी बाढ़ का पता कैसे लगाता है और इसे कैसे रोकता है?',
    faq1A: 'ड्रेनेज चैनलों के अंदर स्थापित आईओटी अल्ट्रासोनिक सेंसर लगातार जल स्तंभ की गहराई को मापते हैं। जब स्तर 75% की सीमा को पार करता है, तो प्रणाली स्वचालित रूप से सोलेनॉइड वाल्व खोलती है, जिससे पानी सड़कों पर भरने से पहले भूमिगत जलाशयों में चला जाता है।',
    faq2Q: 'क्या एकत्रित बाढ़ का पानी नगरपालिका के पुनर्उपयोग के लिए सुरक्षित है?',
    faq2A: 'हाँ! एकत्रित पानी बहु-स्तरीय निस्पंदन उपचार प्रक्रिया से गुजरता है। शुद्ध पानी पार्कों की बागवानी, सिंचाई, सड़क धुलाई और अग्निशमन रिजर्व के लिए स्वीकृत है।',
    faq3Q: 'AI बाढ़ पूर्वानुमान इंजन क्या भूमिका निभाता है?',
    faq3A: 'चरण 7 एआई इंजन आईओटी टेलीमेट्री, ऐतिहासिक वर्षा पैटर्न और मौसम पूर्वानुमान को मिलाकर ड्रेनेज संतृप्ति सूचकांक (DSI) की गणना करता है। यह 4 घंटे पहले तक बाढ़ के जोखिम की भविष्यवाणी करता है।',
    faq4Q: 'क्या फील्ड तकनीशियन दूरस्थ रूप से हार्डवेयर का प्रबंधन कर सकते हैं?',
    faq4A: 'बिल्कुल। तकनीशियनों के पास एक समर्पित तकनीशियन सूट है जिससे वे ESP32 नियंत्रक डायग्नोस्टिक्स, सेंसर अंशांकन और वाल्व रिले की जांच दूरस्थ रूप से कर सकते हैं।',

    // Features Showcase Section
    featuresBadge: 'सिस्टम क्षमताएं',
    featuresTitle: 'व्यापक विशेषताएं और प्लेटफ़ॉर्म मॉड्यूल',
    featuresSubtitle: 'आपके शहर में वर्षा जल की निगरानी, नियंत्रण और पुनर्उपयोग के लिए आवश्यक सब कुछ।',
    feat1Title: 'IoT जल टेलीमेट्री',
    feat1Desc: 'शहर के वार्डों में वास्तविक समय अल्ट्रासोनिक गहराई सेंसिंग, प्रवाह दर और आरएसएसआई सिग्नल टेलीमेट्री।',
    feat2Title: 'भूमिगत संप भंडारण',
    feat2Desc: 'सक्रिय आयतन गेज के साथ 50,000L+ वर्षा जल का प्रबंधन करने वाले भूमिगत होल्डिंग संप।',
    feat3Title: 'जल निस्पंदन और पुनर्उपयोग',
    feat3Desc: 'बागवानी, सड़क की सफाई, सिंचाई और अग्निशमन के लिए आपूर्ति करने वाला बहु-स्तरीय निस्पंदन।',
    feat4Title: 'AI बाढ़ जोखिम पूर्वानुमान',
    feat4Desc: 'मशीन लर्निंग द्वारा 4 घंटे पहले ही जल निकासी संतृप्ति सूचकांक (DSI) की गणना।',
    feat5Title: 'GIS बाढ़ मानचित्र और ग्रिड',
    feat5Desc: 'इंटरएक्टिव स्थानिक मैपिंग, वार्ड बाढ़ जोखिम हीटमैप और आपातकालीन टीम प्रेषण।',
    feat6Title: 'नागरिक पोर्टल और आपातकालीन SOS',
    feat6Desc: 'त्वरित आपातकालीन एसओएस प्रेषण और जियोटैग की गई सामुदायिक समस्या रिपोर्टिंग पोर्टल।',
    feat7Title: 'तकनीशियन रखरखाव सूट',
    feat7Desc: 'ESP32 नियंत्रक डायग्नोस्टिक्स, सेंसर अंशांकन, वाल्व रिले नियंत्रण और कार्य आदेश।',
    feat8Title: 'मौसम और मानसून पूर्वानुमान',
    feat8Desc: 'वर्षा रडार एकीकरण, वर्षा की संभावना और मानसून जोखिम विश्लेषण।',

    automatedLifecycle: 'स्वचालित जीवनचक्र',
    howItWorksTitle: '4 चरणों में SUOWMRS कैसे काम करता है',
    architecturalBlueprint: 'वास्तुकला की रूपरेखा',
    explorePhase: 'चरण देखें',
    faqTitle: 'अक्सर पूछे जाने वाले प्रश्न',
    faqSubtitle: 'क्या आपके पास प्रश्न हैं? हमारे पास उत्तर हैं।',

    // Common & Alerts Page UI keys
    markAllRead: 'सभी पढ़ा हुआ चिह्नित करें',
    searchAlertsPlaceholder: 'संदेश या स्थान द्वारा अलर्ट खोजें...',
    allClear: 'सब कुछ सुरक्षित',
    noAlertsFilter: 'वर्तमान फ़िल्टर से कोई अलर्ट मेल नहीं खाता।',
    alertStreamSubtitle: 'वास्तविक समय अलर्ट स्ट्रीम · कुल {total} रिकॉर्ड · हर 30s में स्वतः रीफ़्रेश',
    justNow: 'अभी-अभी',
    minutesAgo: '{m} मि. पहले',
    hoursAgo: '{h} घंटे पहले',
    daysAgo: '{d} दिन पहले',
    depth: 'गहराई',
    status: 'स्थिति',
    todayPeak: 'आज का चरम',
    todayAvg: 'आज का औसत',
    state: 'अवस्था',
    triggerLevel: 'ट्रिगर स्तर',
    mode: 'मोड',
    relay: 'रिले',
    criticalFloodBanner: '🚨 गंभीर बाढ़ सीमा पार हो गई!',
    elevatedWaterBanner: '⚠️ जल स्तर में वृद्धि पाई गई',
    excessInflow: 'अतिरिक्त अंतर्प्रवाह',
    primarySumpLevel: 'प्राथमिक सम्प स्तर',
    peak24hWaterLevel: '24 घंटे का चरम जल स्तर',
    maxRecordedToday: 'आज दर्ज अधिकतम',
    flowVelocity: 'जल निकासी प्रवाह वेग',
    normalDischargeSpeed: 'सामान्य निर्वहन गति',
    sensorTelemetry: 'IoT सेंसर टेलीमेट्री',
    linePowerStable: 'लाइन पावर स्थिर',
    page: 'पृष्ठ',
    of: 'का',
    pageOf: 'पृष्ठ {page} / {pages} · कुल {total} अलर्ट',
    previous: 'पिछला',
    next: 'अगला',
    showingPage: 'पृष्ठ {page} / {pages} प्रदर्शित ({total} कुल सिस्टम)',

    // Weather Page keys
    currentConditions: 'वर्तमान स्थितियां',
    rainfallSuffix: 'मिमी/घंटा वर्षा',
    intensitySuffix: 'तीव्रता',
    humiditySuffix: 'आर्द्रता',
    floodRiskLevel: 'बाढ़ जोखिम स्तर',
    temperature: 'तापमान',
    humidity: 'आर्द्रता',
    windSpeed: 'हवा की गति',
    cloudCover: 'बादल आवरण',
    hourlyRainfallForecast: 'प्रति घंटा वर्षा पूर्वानुमान',
    forecastSummary: 'पूर्वानुमान सारांश',
    expectedTotalRainfall: 'अपेक्षित कुल वर्षा',
    overNextHours: 'अगले {hours} घंटे में',
    currentIntensity: 'वर्तमान तीव्रता',
    forecastDuration: 'पूर्वानुमान अवधि',
    untilConditionsClear: 'स्थिति सामान्य होने तक',
    drainageImpact: 'जल निकासी प्रभाव',
    estimatedDrainageLoad: 'अनुमानित जल निकासी भार',
    weatherEngineNote: 'मौसम डेटा वास्तविक समय जोखिम गणना के लिए AI बाढ़ पूर्वानुमान इंजन (चरण 7) में जाता है।',
    weatherSubtitle: '{city}, {state} · जल विज्ञान जोखिम एकीकरण · स्वतः रीफ़्रेश 60s',
    now: 'अब',
    risk_high_desc: 'भारी वर्षा का पता चला। जल निकासी व्यवस्था पर दबाव। बाढ़ का जोखिम बढ़ा।',
    risk_moderate_desc: 'मध्यम वर्षा। जल स्तर पर नज़र रखें। जल निकासी क्षमता की समीक्षा करें।',
    risk_low_desc: 'हल्की वर्षा। प्रणालियाँ सामान्य रूप से काम कर रही हैं। कोई तात्कालिक जोखिम नहीं।',
    risk_none_desc: 'कोई वर्षा नहीं। साफ़ मौसम। सभी प्रणालियाँ हरी स्थिति में।',
    cond_heavy_monsoon: 'सक्रिय जलभराव चेतावनी के साथ मानसूनी तूफान',
    cond_light_rain: 'हल्की मानसूनी फुहारें',
    cond_moderate_rain: 'मध्यम वर्षा',
    cond_clear: 'साफ़ मौसम',
    cond_thunderstorm: 'गंभीर तूफान चेतावनी',
    intensity_clear: 'साफ़',
    intensity_light: 'हल्की बारिश',
    intensity_moderate: 'मध्यम',
    intensity_heavy: 'भारी बारिश',
    intensity_violent: 'अति भीषण',
    impact_critical: 'गंभीर',
    impact_elevated: 'बढ़ा हुआ',
    impact_normal: 'सामान्य',
    quality_good: 'अच्छा',
    quality_excellent: 'उत्कृष्ट',
    quality_moderate: 'मध्यम',
    quality_poor: 'खराब',
    pipeline: 'उपचार पाइपलाइन',
    waterQuality: 'जल गुणवत्ता',
    purificationEfficiency: 'शुद्धिकरण दक्षता',
    distributed: 'वितरित',
    allocatedSuffix: 'आवंटित का',
    swal_valve_open_title: 'सोलेनॉइड डायवर्टर वाल्व खोलें?',
    swal_valve_close_title: 'सोलेनॉइड डायवर्टर वाल्व बंद करें?',
    swal_valve_open_desc: 'मैन्युअल रूप से वाल्व खोलने से जल निकासी का पानी तुरंत भूमिगत भंडारण जलाशय में मुड़ जाएगा।',
    swal_valve_close_desc: 'वाल्व बंद करने से भूमिगत भंडारण मोड़ रुक जाएगा और मुख्य तूफान जल निकासी मार्ग सक्रिय रहेगा।',
    swal_confirm_open_valve: 'वाल्व खोलना सुनिश्चित करें',
    swal_confirm_close_valve: 'वाल्व बंद करना सुनिश्चित करें',
    swal_cancel: 'रद्द करें',
    swal_confirm: 'पुष्टि करें',
    swal_diversion_title: 'आपातकालीन जल मोड़ शुरू करें?',
    swal_diversion_heading: 'गंभीर तूफान जल निकासी कार्रवाई',
    swal_diversion_desc: 'भूमिगत सोलेनॉइड डायवर्टर वाल्व को सक्रिय करने से {systemId} से अतिरिक्त तूफानी पानी तुरंत भूमिगत जलकुंड बफर में चला जाएगा।',
    swal_diversion_confirm: 'हां, पानी अभी मोड़ें',
    swal_location: 'स्थान',
    swal_current_water_level: 'वर्तमान जल स्तर',
    swal_storage_cistern: 'भंडारण जलाशय',
    swal_critical_badge: 'गंभीर',
    swal_capacity_available: 'क्षमता उपलब्ध',
    swal_sos_title: 'आपातकालीन SOS डिस्पैच ट्रिगर करें?',
    swal_sos_heading: 'गंभीर आपदा प्रतिक्रिया चेतावनी',
    swal_sos_desc: 'यह तुरंत नगरपालिका बाढ़ नियंत्रण कक्ष और स्थानीय आपातकालीन कर्मियों को उच्च प्राथमिकता वाले अलर्ट निर्देशांक प्रसारित करेगा।',
    swal_sos_confirm: 'हां, SOS भेजें',
    swal_reboot_title: 'ईएसपी32 नियंत्रक रीबूट करें?',
    swal_reboot_desc: 'माइक्रोकंट्रोलर के पुनरारंभ होने के दौरान टेलीमेट्री स्ट्रीमिंग लगभग 3-5 सेकंड के लिए रुक जाएगी।',
    swal_reboot_confirm: 'हां, नोड रीबूट करें',
    swal_reboot_success_title: 'रीबूट सिग्नल भेजा गया',
    swal_reboot_success_desc: 'ईएसपी32 नियंत्रक को सॉफ़्ट सिस्टम रीसेट करने का निर्देश दिया गया है।',
  },
  or: {
    appName: 'SUOWMRS',
    appSubtitle: 'ଜଳ ଅନୁବୀକ୍ଷଣ ଓ ପୁନର୍ ବ୍ୟବହାର',
    dashboard: 'ସଂକ୍ଷିପ୍ତ ବିବରଣ',
    waterMonitoring: 'ଜଳ ଅନୁବୀକ୍ଷଣ',
    alerts: 'ସତର୍କତା ଓ ଇତିହାସ',
    storage: 'ଭୂ-ସଂରକ୍ଷଣ',
    waterReuse: 'ଜଳ ପୁନର୍ ବ୍ୟବହାର',
    weather: 'ପାଣିପାଗ ପୂର୍ବାନୁମାନ',
    complaints: 'ନାଗରିକ ପୋର୍ଟାଲ',
    sos: 'ଜରୁରୀ SOS',
    maintenance: 'ରକ୍ଷଣାବେକ୍ଷଣ',
    systemHealth: 'ସିଷ୍ଟମ ସ୍ୱାସ୍ଥ୍ୟ',
    sensors: 'ସେନ୍ସର ଓ ଭାଲ୍ଭ',
    esp32Diagnostics: 'ESP32 ନିୟନ୍ତ୍ରକ',
    sensorDiagnostics: 'ସେନ୍ସର ଓ କାଲିବ୍ରେସନ୍',
    componentsHealth: 'ଆକ୍ଚୁଏଟର ଓ ରିଲେ',
    workOrders: 'କାର୍ଯ୍ୟ ଆଦେଶ ଓ ଟିକେଟ',
    adminDashboard: 'ମ୍ୟୁନିସିପାଲ ନିୟନ୍ତ୍ରଣ',
    userApprovals: 'ଉପଭୋକ୍ତା ଅନୁମୋଦନ',
    adminMap: 'GIS ବନ୍ୟା ମାନଚିତ୍ର',
    adminSystems: 'ବହୁ-ସିଷ୍ଟମ ଗ୍ରିଡ',
    adminComplaints: 'ନାଗରିକ ରିପୋର୍ଟ',
    adminAnalytics: 'ପୂର୍ବାନୁମାନ ବିଶ୍ଳେଷଣ',
    aiPrediction: 'AI ବନ୍ୟା ପୂର୍ବାନୁମାନ',
    myProfile: 'ମୋର ପ୍ରୋଫାଇଲ୍ ଓ ପାସୱାର୍ଡ',
    signOut: 'ସାଇନ୍ ଆଉଟ୍',
    userVerificationTitle: 'ଉପଭୋକ୍ତା ଯାଞ୍ଚ ଓ ଅନୁମୋଦନ',
    userVerificationDesc: 'ନେଟୱାର୍କ ପ୍ରବେଶ ଅନୁମତି ଦେବା ପୂର୍ବରୁ ଆସୁଥିବା ନିବାସୀ ଓ ଟେକ୍ନିସିଆନ ପଞ୍ଜୀକରଣ ଯାଞ୍ଚ କରନ୍ତୁ।',
    pending: 'ବିଚାରାଧୀନ',
    verified: 'ଯାଞ୍ଚ ହୋଇଛି',
    rejected: 'ଅଗ୍ରାହ୍ୟ',
    all: 'ସମସ୍ତ',
    refresh: 'ରିଫ୍ରେସ',
    searchUser: 'ଉପଭୋକ୍ତା ଖୋଜନ୍ତୁ...',
    residentOps: 'ନିବାସୀ କାର୍ଯ୍ୟ',
    technicianSuite: 'ଟେକ୍ନିସିଆନ ସ୍ୟୁଟ',
    municipalityAdmin: 'ମ୍ୟୁନିସିପାଲ ପ୍ରଶାସନ',
    live: 'ସରଜୀବ',
    demoUser: 'ଡେମୋ ଉପଯୋଗକର୍ତ୍ତା',
    waterMonitoringTitle: 'ଜଳ ଅନୁବୀକ୍ଷଣ ଡ୍ୟାଶବୋର୍ଡ',
    emergencySos: 'ଜରୁରୀ SOS',
    reportIssue: 'ସମସ୍ୟା ଜଣାନ୍ତୁ',
    waterLevel: 'ଜଳ ସ୍ତର',
    undergroundStorage: 'ଭୂ-ଭଣ୍ଡାର',
    solenoidValve: 'ସୋଲେନୋଇଡ ଭାଲ୍ଭ',
    liveDrainageTrend: 'ସଜୀବ ଜଳ ସ୍ତର ଧାରା',
    alertFeed: 'ସତର୍କତା ଫିଡ',
    treatmentTitle: 'ଜଳ ଶୋଧନ ଓ ପୁନର୍ ବ୍ୟବହାର ଚକ୍ର',
    approvedReuseChannels: 'ଅନୁମୋଦିତ ପୁନର୍ ବ୍ୟବହାର ଚ୍ୟାନେଲ',
    gardening: 'ବଗିଚା',
    cleaning: 'ଯାନ ସଫା',
    irrigation: 'ଜଳସେଚନ',
    construction: 'ନିର୍ମାଣ',
    industrial: 'ଶିଳ୍ପ',
    manualOverride: 'ମ୍ୟାନୁଆଲ ଓଭରରାଇଡ',
    openValve: 'ଭାଲ୍ଭ ଖୋଲନ୍ତୁ',
    closeValve: 'ଭାଲ୍ଭ ବନ୍ଦ କରନ୍ତୁ',
    totalStored: 'ମୋଟ ସଂଗ୍ରହ',
    treatedWater: 'ଶୋଧିତ ଜଳ',
    availableReuse: 'ପୁନର୍ ବ୍ୟବହାର ଯୋଗ୍ୟ',
    language: 'ଭାଷା',
    role: 'ଭୂମିକା',
    // Dynamic Backend Data & Alerts
    alert_normal: 'ଜଳ ସ୍ତର {level}% ରେ ସ୍ୱାଭାବିକ। ନିଷ୍କାସନ ସ୍ଥିର।',
    alert_warning: 'ସତର୍କତା: ଜଳ ସ୍ତର ବୃଦ୍ଧି ପାଇ {level}% ହୋଇଛି। ନଜର ରଖାଯାଇଛି।',
    alert_danger: 'ଉଚ୍ଚ ବିପଦ: ଜଳ ସ୍ତର {level}%! ଡାଇଭର୍ଟର ଭାଲ୍ଭ ଆପେ ଖୋଲିଲା।',
    alert_critical: 'ଜରୁରୀ ବନ୍ୟା ସତର୍କତା: ଜଳ ସ୍ତର {level}%! ଜରୁରୀ ପଦକ୍ଷେପ ସକ୍ରିୟ।',
    status_normal: 'ସ୍ୱାଭାବିକ',
    status_warning: 'ସତର୍କତା',
    status_danger: 'ଉଚ୍ଚ ବିପଦ',
    status_critical: 'ଜରୁରୀ ବନ୍ୟା',
    status_high: 'ଉଚ୍ଚ ବିପଦ',
    status_moderate: 'ମଧ୍ୟମ',
    status_low: 'କମ୍',
    status_none: 'ସୁରକ୍ଷିତ',
    valve_diverting: 'ପ୍ରବାହ ମୋଡ଼ାଯାଉଛି',
    valve_standby: 'ଷ୍ଟାଣ୍ଡବାଇ',
    valve_auto: 'ସ୍ୱୟଂଚାଳିତ',
    valve_manual: 'ମ୍ୟାନୁଆଲ',
    activeTank: 'ସକ୍ରିୟ ଟାଙ୍କି',
    current: 'ବର୍ତ୍ତମାନ',
    capacity: 'କ୍ଷମତା',
    available: 'ଉପଲବ୍ଧ',
    inflowRate: 'ପ୍ରବେଶ ହାର',
    empty: 'ଖାଲି',
    full: 'ପୂର୍ଣ୍ଣ',
    minToday: 'ସର୍ବନିମ୍ନ ଆଜି',
    avgToday: 'ହାରାହାରି ଆଜି',
    peakToday: 'ସର୍ବୋଚ୍ଚ ଆଜି',
    unread: 'ଅପଠିତ',
    noAlertsHealthy: 'କୌଣସି ସତର୍କତା ନାହିଁ — ସିଷ୍ଟମ ସୁରକ୍ଷିତ',
    autoUpdatesStream: 'ଲାଇଭ Socket.io ଷ୍ଟ୍ରିମରୁ ସ୍ୱତଃ ଅପଡେଟ',
    quality: 'ଗୁଣବତ୍ତା',
    quality_good: 'ଉତ୍ତମ',
    quality_excellent: 'ଅତି ଉତ୍ତମ',
    quality_moderate: 'ମଧ୍ୟମ',
    collected: 'ସଂଗୃହିତ',
    efficiency: 'ଦକ୍ଷତା',
    distributed: 'ବଣ୍ଟିତ',
    treatmentPhase: 'ପର୍ଯ୍ୟାୟ ୪: ସଂରକ୍ଷିତ ଜଳ → ଶୋଧନ → ପୌର ବିତରଣ',
    sensorsActive: 'ସେନ୍ସର ସକ୍ରିୟ',
    offline: 'ଅଫଲାଇନ',

    // TTS ଡ୍ୟାସବୋର୍ଡ ଧ୍ୱନି କୀ
    tts_listen: 'ଶୁଣନ୍ତୁ',
    tts_listenAll: 'ଡ୍ୟାସବୋର୍ଡ ଶୁଣନ୍ତୁ',
    tts_stop: 'ବନ୍ଦ କରନ୍ତୁ',
    tts_waterLevel: 'ସଜୀବ ଜଳ ନିଷ୍କାସନ ସ୍ତର {level} ଶତକଡ଼ା। ସିଷ୍ଟମ ସ୍ଥିତି {status}।',
    tts_storage: 'ଭୂତଳ ଭଣ୍ଡାର {fill} ଶତକଡ଼ା ପୂର୍ଣ୍ଣ। ବର୍ତ୍ତମାନ ପରିମାଣ {volume} ଲିଟର, ସମ୍ପୂର୍ଣ୍ଣ କ୍ଷମତା {capacity} ଲିଟର। {available} ଲିଟର ଉପಲବ୍ଧ।',
    tts_valve: 'ସୋଲେନୋଇଡ ଭାଲ୍ଭ ସ୍ଥିତି {status}। ମୋଡ ସ୍ୱୟଂଚାଳିତ। ଟ୍ରିଗର ସ୍ତର ୭୫ ଶତକଡ଼ା।',
    tts_floodBannerCritical: 'ଜରୁରୀ ବନ୍ୟା ସୀମା ଅତିକ୍ରମ! ଜଳ ସ୍ତର {level} ଶତକଡ଼ା। ଡାଇଭର୍ଟର ଭାଲ୍ଭ {valve}।',
    tts_floodBannerWarning: 'ଜଳ ସ୍ତର ବୃଦ୍ଧି ହୋଇଛି। ଜଳ ସ୍ତର {level} ଶତକଡ଼ା। ଡାଇଭର୍ଟର ଭାଲ୍ଭ {valve}।',
    tts_dashSummary: 'ଡ୍ୟାସବୋର୍ଡ ସାରାଂଶ। ଜଳ ସ୍ତର {level} ଶତକଡ଼ା, ସ୍ଥିତି {status}। ଭଣ୍ଡାର {fill} ଶତକଡ଼ା ପୂର୍ଣ୍ଣ, {volume} ଲିଟର ସଂରକ୍ଷିତ। ଭାଲ୍ଭ {valve}। {alert}',
    tts_noAlerts: 'କୌଣସି ସକ୍ରିୟ ସତର୍କତା ନାହିଁ। ସିଷ୍ଟମ ସୁରକ୍ଷିତ।',
    tts_alertCount: '{count} ସକ୍ରିୟ ସତର୍କତା।',
    tts_sirenWarning: 'ସାଇରେନ ସତର୍କତା: ଭାଲ୍ଭ ଖୋଲାଯାଇଛି।',

    // Landing Page & Footer Keys
    home: 'ଗୃହ',
    residentPortal: 'ନିବାସୀ ପୋର୍ଟାଲ',
    signIn: 'ସାଇନ୍ ଇନ୍',
    liveApp: 'ଲାଇଭ୍ ଆପ୍',
    heroBadge: 'ସ୍ମାର୍ଟ ଭୂତଳ ଜଳ ନିଷ୍କାସନ, ଅନୁବୀକ୍ଷଣ ଓ ପୁନର୍ ବ୍ୟବହାର ବ୍ୟବସ୍ଥା',
    heroTitle1: 'ନୂତନ ପିଢ଼ିର AI ଓ IoT ମଞ୍ଚ',
    heroTitle2: 'ବନ୍ୟା ରୋକିବା ଓ ଜଳ ପୁନର୍ ବ୍ୟବହାର',
    heroDesc: 'SUOWMRS ସହରାଞ୍ଚଳ ବନ୍ୟା ସମସ୍ୟାକୁ ଜଳ ସମ୍ପଦରେ ପରିଣତ କରେ। ନାଳର ସଜୀବ ଅନୁବୀକ୍ଷଣରୁ ଭୂତଳ ମୋଡ଼ ଓ AI ପୂର୍ବାନୁମାନ ପର୍ଯ୍ୟନ୍ତ।',
    sensorsMonitored: 'ସେନ୍ସର ଅନୁବୀକ୍ଷିତ',
    liveWaterLevel: 'ସଜୀବ ଜଳ ସ୍ତର',
    storedWater: 'ସଂରକ୍ଷିତ ଜଳ',
    autoValveStatus: 'ଅଟୋ ଭାଲ୍ଭ ସ୍ଥିତି',
    totalFloodPrevented: 'ମୋଟ ବନ୍ୟା ରୋକାଯାଇଥିବା ପରିମାଣ',
    activeIoTNodes: 'ସକ୍ରିୟ IoT ସେନ୍ସର ନୋଡ୍',
    systemUptime: 'ସିଷ୍ଟମ ଅପଟାଇମ',
    treatedWaterReused: 'ଶୋଧିତ ଜଳ ପୁନର୍ବ୍ୟବହୃତ',
    ecosystemBlueprint: '7-ପର୍ଯ୍ୟାୟ SUOWMRS ବ୍ୟବସ୍ଥା',
    tailoredExperience: '3 ଆବଶ୍ୟକୀୟ ଭୂମିକା ପାଇଁ ନିର୍ମିତ',
    openResidentView: 'ନିବାସୀ ଦୃଶ୍ୟ ଖୋଲନ୍ତୁ',
    technicianHub: 'ଟେକ୍ନିସିଆନ ହବ୍',
    footerFoundation: 'SUOWMRS ସ୍ମାର୍ଟ ଜଳ ମଞ୍ଚ',
    allRightsReserved: 'ସର୍ବାଧିକାର ସୁରକ୍ଷିତ।',
    step1Title: '୧. IoT ସେନ୍ସିଂ',
    step1Desc: 'ଅଲ୍ଟ୍ରାସୋନିକ ଗଭୀରତା ସେନ୍ସର ପ୍ରତି ୫ ସେକେଣ୍ଡରେ ନାଳର ଜଳ ସ୍ତର ଟ୍ରାକ୍ କରନ୍ତି।',
    step2Title: '୨. ସ୍ୱୟଂଚାଳିତ ମୋଡ଼',
    step2Desc: '୭୫% ଗଭୀରତାରେ ସୋଲେନୋଇଡ ଭାଲ୍ଭ ଆପେ ଖୋଲି ଜଳକୁ ଭୂତଳକୁ ପଠାଏ।',
    step3Title: '୩. ବିଶୋଧନ',
    step3Desc: 'ସଂଗୃହିତ ଜଳ ଆବର୍ଜନା ଓ ଅଳିଆ ସଫା ପାଇଁ ବହୁ-ସ୍ତରୀୟ ଶୋଧନ ଦେଇ ଗତି କରେ।',
    step4Title: '୪. ପୌର ପୁନର୍ବ୍ୟବହାର',
    step4Desc: 'ଶୋଧିତ ଜଳ ବଗିଚା, ଜଳସେଚନ, ରାସ୍ତା ସଫା ଓ ନିଆଁ ଲିଭାଇବା ପାଇଁ ବଣ୍ଟନ କରାଯାଏ।',

    // 7 Phases
    phase1Title: '୧. IoT ନାଳ ଅନୁବୀକ୍ଷଣ',
    phase1Desc: 'ଅଲ୍ଟ୍ରାସୋନିକ ସେନ୍ସର ପ୍ରତି ୫ ସେକେଣ୍ଡରେ ଜଳ ଗଭୀରତା ମାପନ୍ତି।',
    phase2Title: '୨. ସ୍ୱୟଂଚାଳିତ ମୋଡ଼ ଭାଲ୍ଭ',
    phase2Desc: '୭୫% ଗଭୀରତାରେ ସୋଲେନୋଇଡ ଭାଲ୍ଭ ସ୍ୱତଃ ଖୋଲିଯାଏ।',
    phase3Title: '୩. ସତର୍କତା ଓ ପୂର୍ବ ସୂଚନା',
    phase3Desc: 'ନାଗରିକ ଓ ଜରୁରୀକାଳୀନ ଦଳକୁ ତୁରନ୍ତ SMS ଓ ପୋର୍ଟାଲ୍ ସୂଚନା।',
    phase4Title: '୪. ଭୂତଳ ଜଳ ଭଣ୍ଡାର',
    phase4Desc: 'ଉଚ୍ଚ କ୍ଷମତା ସମ୍ପନ୍ନ ଭୂତଳ ଭଣ୍ଡାର ୫୦,୦୦୦L ରୁ ଅଧିକ ଜଳ ସଂରକ୍ଷଣ କରେ।',
    phase5Title: '୫. ଶୋଧନ ଓ ଗୁଣବତ୍ତା ଯାଞ୍ଚ',
    phase5Desc: 'ବହୁ-ସ୍ତରୀୟ ବିଶୋଧନ ଜଳକୁ ପୁନର୍ ବ୍ୟବହାର ଯୋଗ୍ୟ କରେ।',
    phase6Title: '୬. ମ୍ୟୁନିସିପାଲିଟି ନିୟନ୍ତ୍ରଣ କେନ୍ଦ୍ର',
    phase6Desc: 'ଇଞ୍ଜିନିୟରମାନଙ୍କ ପାଇଁ କେନ୍ଦ୍ରୀୟ GIS ମାନଚିତ୍ର ଓ ସିଷ୍ଟମ ପୋର୍ଟାଲ।',
    phase7Title: '୭. AI ବନ୍ୟା ପୂର୍ବାନୁମାନ',
    phase7Desc: 'AI ସିଷ୍ଟମ ୪ ଘଣ୍ଟା ପୂର୍ବରୁ ବନ୍ୟା ବିପଦର ପୂର୍ବାନୁମାନ କରେ।',

    // Roles
    role1Title: 'ନିବାସୀ କାର୍ଯ୍ୟ',
    role1Desc: 'ସଜୀବ ଜଳ ମାପକ, ବନ୍ୟା ପୂର୍ବ ସୂଚନା, SOS ଜରୁରୀକାଳୀନ ସେବା, ନାଗରିକ ଅଭିଯୋଗ ଓ ଜଳ ପୁନର୍ବ୍ୟବହାର।',
    role2Title: 'ଟେକ୍ନିସିଆନ ସ୍ୟୁଟ',
    role2Desc: 'ହାର୍ଡୱେର୍ ଟେଲିମେଟ୍ରି, ESP32 କାଲିବ୍ରେସନ୍, ଭାଲ୍ଭ ନିୟନ୍ତ୍ରଣ ଓ ରକ୍ଷଣାବେକ୍ଷଣ ସମୟସୂଚୀ।',
    role3Title: 'ମ୍ୟୁନିସିପାଲ ପ୍ରଶାସନ',
    role3Desc: 'ସହର-ବ୍ୟାପୀ GIS ବନ୍ୟା ମାନଚିତ୍ର, ବହୁ-ସିଷ୍ଟମ ସ୍ଥିତି, ଜରୁରୀ ସେବା ଓ AI ବିଶ୍ଳେଷଣ।',

    // FAQs
    faq1Q: 'SUOWMRS କିପରି ସ୍ୱୟଂଚାଳିତ ଭାବରେ ବନ୍ୟା ଚିହ୍ନଟ ଓ ରୋକିଥାଏ?',
    faq1A: 'ନାଳ ଭିତରେ ଥିବା IoT ଅଲ୍ଟ୍ରାସୋନିକ ସେନ୍ସର ପ୍ରତି ମୁହୂର୍ତ୍ତରେ ଜଳ ଗଭୀରତା ମାପନ୍ତି। ଜଳ ସ୍ତର ୭୫% ଟପିଲେ, ସୋଲେନୋଇଡ ଭାଲ୍ଭ ଆପେ ଖୋଲି ପାଣିକୁ ରାସ୍ତାକୁ ଆସିବା ପୂର୍ବରୁ ଭୂତଳ ଭଣ୍ଡାରକୁ ପଠାଇଦିଏ।',
    faq2Q: 'ସଂଗୃହିତ ବନ୍ୟା ଜଳ ପୌର ପୁନର୍ ବ୍ୟବହାର ପାଇଁ ସୁରକ୍ଷିତ କି?',
    faq2A: 'ହଁ! ସଂଗୃହିତ ଜଳ ବହୁ-ସ୍ତରୀୟ ବିଶୋଧନ ଦେଇ ଗତି କରେ। ଏହି ପରିଷ୍କାର ଜଳ ବଗିଚା, ଜଳସେଚନ, ରାସ୍ତା ସଫା ଓ ଅଗ୍ନିଶମ ସେବା ପାଇଁ ବ୍ୟବହାର କରାଯାଏ।',
    faq3Q: 'AI ବନ୍ୟା ପୂର୍ବାନୁମାନର ଭୂମିକା କ’ଣ?',
    faq3A: 'AI ଇଞ୍ଜିନ୍ IoT ଟେଲିମେଟ୍ରି, ବର୍ଷା ତଥ୍ୟ ଓ ପାଣିପାଗ ପୂର୍ବାନୁମାନ ମିଶାଇ ୪ ଘଣ୍ଟା ପୂର୍ବରୁ ବନ୍ୟା ସମ୍ଭାବନା ଆକଳନ କରେ।',
    faq4Q: 'ଟେକ୍ନିସିଆନମାନେ ଦୂରରୁ ହାର୍ଡୱେର ଯାଞ୍ଚ କରିପାରିବେ କି?',
    faq4A: 'ନିଶ୍ଚିତ ଭାବରେ। ଟେକ୍ନିସିଆନ ସ୍ୟୁଟ୍ ମାଧ୍ୟମରେ ESP32 ନିୟନ୍ତ୍ରକ, ସେନ୍ସର ଓ ଭାଲ୍ଭର ସ୍ଥିତି ଦୂରରୁ ନିୟନ୍ତ୍ରଣ ଓ ଯାଞ୍ଚ କରାଯାଇପାରିବ।',

    // Features Showcase Section
    featuresBadge: 'ସିଷ୍ଟମ କ୍ଷମତା',
    featuresTitle: 'ସମ୍ପୂର୍ଣ୍ଣ ବୈଶିଷ୍ଟ୍ୟ ଓ ପ୍ଲାଟଫର୍ମ ମଡ୍ୟୁଲ୍',
    featuresSubtitle: 'ଆପଣଙ୍କ ସହରର ବନ୍ୟା ଜଳ ଅନୁବୀକ୍ଷଣ, ନିୟନ୍ତ୍ରଣ ଓ ପୁନର୍ ବ୍ୟବହାର ପାଇଁ ସବୁକିଛି।',
    feat1Title: 'IoT ଜଳ ଟେଲିମେଟ୍ରି',
    feat1Desc: 'ସହରର ୱାର୍ଡଗୁଡ଼ିକରେ ସଜୀବ ଅଲ୍ଟ୍ରାସୋନିକ ଗଭୀରତା, ପ୍ରବାହ ହାର ଓ RSSI ସିଗନାଲ।',
    feat2Title: 'ଭୂତଳ ଜଳ ଭଣ୍ଡାର',
    feat2Desc: '୫୦,୦୦୦L ରୁ ଅଧିକ ଜଳ ସଂରକ୍ଷଣ କରୁଥିବା ଭୂତଳ ଭଣ୍ଡାର ଓ ସଜୀବ ଗେଜ୍।',
    feat3Title: 'ଜଳ ଶୋଧନ ଓ ପୁନର୍ ବ୍ୟବହାର',
    feat3Desc: 'ବଗିଚା, ରାସ୍ତା ସଫା, ଜଳସେଚନ ଓ ଅଗ୍ନିଶମ ସେବା ପାଇଁ ବହୁ-ସ୍ତରୀୟ ଶୋଧନ।',
    feat4Title: 'AI ବନ୍ୟା ପୂର୍ବାନୁମାନ',
    feat4Desc: 'AI ଦ୍ୱାରା ୪ ଘଣ୍ଟା ପୂର୍ବରୁ ଜଳ ନିଷ୍କାସନ ସଂପୃକ୍ତି ସୂଚକାଙ୍କ (DSI) ଆକଳନ।',
    feat5Title: 'GIS ବନ୍ୟା ମାନଚିତ୍ର ଓ ଗ୍ରିଡ',
    feat5Desc: 'ଇଣ୍ଟରାକ୍ଟିଭ୍ ମାନଚିତ୍ର, ୱାର୍ଡ ବନ୍ୟା ହିଟମ୍ୟାପ୍ ଓ ଜରୁରୀକାଳୀନ ଦଳ ପ୍ରେରଣ।',
    feat6Title: 'ନାଗରିକ ପୋର୍ଟାଲ ଓ SOS',
    feat6Desc: 'ତୁରନ୍ତ ଜରୁରୀକାଳୀନ SOS ଓ ନାଗରିକ ଅଭିଯୋଗ ରିପୋର୍ଟ ପୋର୍ଟାଲ।',
    feat7Title: 'ଟେକ୍ନିସିଆନ ରକ୍ଷଣାବେକ୍ଷଣ ସ୍ୟୁଟ',
    feat7Desc: 'ESP32 ନିୟନ୍ତ୍ରକ, ସେନ୍ସର କାଲିବ୍ରେସନ୍, ରିଲେ ନିୟନ୍ତ୍ରଣ ଓ ଟିକେଟ।',
    feat8Title: 'ପାଣିପାଗ ଓ ବର୍ଷା ପୂର୍ବାନୁମାନ',
    feat8Desc: 'ବର୍ଷା ରାଡାର, ବର୍ଷା ସମ୍ଭାବନା ଓ ମୌସୁମୀ ବିପଦ ବିଶ୍ଳେଷଣ।',

    automatedLifecycle: 'ସ୍ୱୟଂଚାଳିତ ଚକ୍ର',
    howItWorksTitle: '୪ ପର୍ଯ୍ୟାୟରେ SUOWMRS କିପରି କାମ କରେ',
    architecturalBlueprint: 'ବ୍ୟବସ୍ଥାର ରୂପରେଖ',
    explorePhase: 'ପର୍ଯ୍ୟାୟ ଦେଖନ୍ତୁ',
    faqTitle: 'ବାରମ୍ବାର ପଚରାଯାଉଥିବା ପ୍ରଶ୍ନ',
    faqSubtitle: 'ଆପଣଙ୍କର ପ୍ରଶ୍ନ ଅଛି? ଆମ ପାଖରେ ଉତ୍ତର ଅଛି।',

    // Common & Alerts Page UI keys
    markAllRead: 'ସବୁ ପଢ଼ା ହୋଇଗଲା ବୋଲି ଚିହ୍ନଟ କରନ୍ତୁ',
    searchAlertsPlaceholder: 'ବାର୍ତ୍ତା କିମ୍ବା ସ୍ଥାନ ଅନୁଯାୟୀ ସତର୍କତା ଖୋଜନ୍ତୁ...',
    allClear: 'ସବୁ ସୁରକ୍ଷିତ',
    noAlertsFilter: 'ବର୍ତ୍ତମାନର ଫିଲ୍ଟର ସହିତ କୌଣସି ସତର୍କତା ମେଳ ଖାଉନାହିଁ।',
    alertStreamSubtitle: 'ରିଅଲ-ଟାଇମ୍ ସତର୍କତା ଧାରା · ମୋଟ {total} ରେକର୍ଡ · ପ୍ରତି ୩୦ ସେକେଣ୍ଡରେ ସ୍ୱତଃ ରିଫ୍ରେଶ',
    justNow: 'ଏଇ ମାତ୍ର',
    minutesAgo: '{m} ମି. ପୂର୍ବରୁ',
    hoursAgo: '{h} ଘଣ୍ଟା ପୂର୍ବରୁ',
    daysAgo: '{d} ଦିନ ପୂର୍ବରୁ',
    depth: 'ଗଭୀରତା',
    status: 'ସ୍ଥିତି',
    todayPeak: 'ଆଜିର ସର୍ବୋଚ୍ଚ',
    todayAvg: 'ଆଜିର ହାରାହାରି',
    state: 'ଅବସ୍ଥା',
    triggerLevel: 'ଟ୍ରିଗର ସ୍ତର',
    mode: 'ମୋଡ୍',
    relay: 'ରିଲେ',
    criticalFloodBanner: '🚨 ଗମ୍ଭୀର ବନ୍ୟା ସୀମା ଅତିକ୍ରମ କରିଛି!',
    elevatedWaterBanner: '⚠️ ଜଳ ସ୍ତର ବୃଦ୍ଧି ପାଇଛି',
    excessInflow: 'ଅତିରିକ୍ତ ପ୍ରବାହ',
    primarySumpLevel: 'ପ୍ରାଥମିକ ସମ୍ପ ସ୍ତର',
    peak24hWaterLevel: '୨୪ ଘଣ୍ଟାର ସର୍ବୋଚ୍ଚ ଜଳ ସ୍ତର',
    maxRecordedToday: 'ଆଜି ରେକର୍ଡ ହୋଇଥିବା ସର୍ବାଧିକ',
    flowVelocity: 'ଜଳ ନିଷ୍କାସନ ପ୍ରବାହ ବେଗ',
    normalDischargeSpeed: 'ସାଧାରଣ ନିଷ୍କାସନ ଗତି',
    sensorTelemetry: 'IoT ସେନ୍ସର ଟେଲିମେଟ୍ରି',
    linePowerStable: 'ଲାଇନ୍ ପାୱାର୍ ସ୍ଥିର',
    page: 'ପୃଷ୍ଠା',
    of: 'ର',
    pageOf: 'ପୃଷ୍ଠା {page} / {pages} · ମୋଟ {total} ସତର୍କତା',
    previous: 'ପୂର୍ବବର୍ତ୍ତୀ',
    next: 'ପରବର୍ତ୍ତୀ',
    showingPage: 'ପୃଷ୍ଠା {page} / {pages} ପ୍ରଦର୍ଶିତ ({total} ମୋଟ ସିଷ୍ଟମ୍)',

    // Weather Page keys
    currentConditions: 'ବର୍ତ୍ତମାନର ସ୍ଥିତି',
    rainfallSuffix: 'ମିମି/ଘଣ୍ଟା ବର୍ଷା',
    intensitySuffix: 'ତୀବ୍ରତା',
    humiditySuffix: 'ଆର୍ଦ୍ରତା',
    floodRiskLevel: 'ବନ୍ୟା ବିପଦ ସ୍ତର',
    temperature: 'ତାପମାତ୍ରା',
    humidity: 'ଆର୍ଦ୍ରତା',
    windSpeed: 'ପବନର ବେଗ',
    cloudCover: 'ମେଘ ଆବରଣ',
    hourlyRainfallForecast: 'ପ୍ରତି ଘଣ୍ଟାର ବର୍ଷା ପୂର୍ବାନୁମାନ',
    forecastSummary: 'ପୂର୍ବାନୁମାନ ସାରାଂଶ',
    expectedTotalRainfall: 'ଅନୁମାନିତ ମୋଟ ବର୍ଷା',
    overNextHours: 'ଆଗାମୀ {hours} ଘଣ୍ଟା ମଧ୍ୟରେ',
    currentIntensity: 'ବର୍ତ୍ତମାନର ତୀବ୍ରତା',
    forecastDuration: 'ପୂର୍ବାନୁମାନ ଅବଧି',
    untilConditionsClear: 'ସ୍ଥିତି ସ୍ୱାଭାବିକ ହେବା ପର୍ଯ୍ୟନ୍ତ',
    drainageImpact: 'ଜଳ ନିଷ୍କାସନ ପ୍ରଭାବ',
    estimatedDrainageLoad: 'ଅନୁମାନିତ ନିଷ୍କାସନ ଭାର',
    weatherEngineNote: 'ପାଣିପାଗ ତଥ୍ୟ ରିଅଲ-ଟାଇମ୍ ବିପଦ ଗଣନା ପାଇଁ AI ବନ୍ୟା ପୂର୍ବାନୁମାନ ଇଞ୍ଜିନ୍ (ପର୍ଯ୍ୟାୟ ୭) କୁ ସଂଯୋଗ ହୋଇଛି।',
    weatherSubtitle: '{city}, {state} · ଜଳ ବିଜ୍ଞାନ ବିପଦ ସମନ୍ୱୟ · ସ୍ୱତଃ ରିଫ୍ରେଶ ୬୦s',
    now: 'ଏବେ',
    risk_high_desc: 'ପ୍ରବଳ ବର୍ଷା ଚିହ୍ନଟ। ଜଳ ନିଷ୍କାସନ ବ୍ୟବସ୍ଥା ଉପରେ ଚାପ। ବନ୍ୟା ବିପଦ ବୃଦ୍ଧି।',
    risk_moderate_desc: 'ମଧ୍ୟମ ଧରଣର ବର୍ଷା। ଜଳ ସ୍ତର ଉପରେ ନଜର ରଖନ୍ତୁ।',
    risk_low_desc: 'ହାଲୁକା ବର୍ଷା। ସିଷ୍ଟମ୍ ସ୍ୱାଭାବିକ ଭାବେ ଚାଲୁଅଛି। କୌଣସି ବିପଦ ନାହିଁ।',
    risk_none_desc: 'ବର୍ଷା ହୋଇନାହିଁ। ପାଗ ସଫା ଅଛି। ସବୁ ସିଷ୍ଟମ୍ ଗ୍ରୀନ୍।',
    cond_heavy_monsoon: 'ସକ୍ରିୟ ଜଳବନ୍ଦୀ ସତର୍କତା ସହିତ ମୌସୁମୀ ଝଡ଼ବର୍ଷା',
    cond_light_rain: 'ହାଲୁକା ମୌସୁମୀ ବର୍ଷା',
    cond_moderate_rain: 'ମଧ୍ୟମ ବର୍ଷା',
    cond_clear: 'ଫର୍ଚ୍ଚା ପାଗ',
    cond_thunderstorm: 'ପ୍ରବଳ କାଳବୈଶାଖୀ ସତର୍କତା',
    intensity_clear: 'ସଫା',
    intensity_light: 'ହାଲୁକା ବର୍ଷା',
    intensity_moderate: 'ମଧ୍ୟମ',
    intensity_heavy: 'ପ୍ରବଳ ବର୍ଷା',
    intensity_violent: 'ଅତି ଭୟଙ୍କର',
    impact_critical: 'ଗମ୍ଭୀର',
    impact_elevated: 'ବୃଦ୍ଧିପ୍ରାପ୍ତ',
    impact_normal: 'ସାଧାରଣ',
    quality_good: 'ଭଲ',
    quality_excellent: 'ଉତ୍କୃଷ୍ଟ',
    quality_moderate: 'ମଧ୍ୟମ',
    quality_poor: 'ଖରାପ',
    pipeline: 'ଶୋଧନ ପାଇପଲାଇନ',
    waterQuality: 'ଜଳ ଗୁଣବତ୍ତା',
    purificationEfficiency: 'ଶୁଦ୍ଧିକରଣ ଦକ୍ଷତା',
    distributed: 'ବଣ୍ଟନ କରାଯାଇଛି',
    allocatedSuffix: 'ଆବଣ୍ଟିତର',
    swal_valve_open_title: 'ସୋଲେନଏଡ୍ ଡାଇଭର୍ଟର ଭାଲ୍ଭ ଖୋଲିବେ?',
    swal_valve_close_title: 'ସୋଲେନଏଡ୍ ଡାଇଭର୍ଟର ଭାଲ୍ଭ ବନ୍ଦ କରିବେ?',
    swal_valve_open_desc: 'ମାନୁଆଲ ଭାବେ ଭାଲ୍ଭ ଖୋଲିଲେ ତୁରନ୍ତ ବନ୍ୟା ଜଳ ଭୂତଳ ସଂରକ୍ଷଣ ଜଳଭଣ୍ଡାରକୁ ମୋଡ଼ି ହୋଇଯିବ।',
    swal_valve_close_desc: 'ଭାଲ୍ଭ ବନ୍ଦ କଲେ ଭୂତଳ ସଂରକ୍ଷଣକୁ ଜଳ ପ୍ରବାହ ବନ୍ଦ ହୋଇ ମୁଖ୍ୟ ଡ୍ରେନେଜ୍ ଲାଇନ୍ ଚାଲୁ ରହିବ।',
    swal_confirm_open_valve: 'ଭାଲ୍ଭ ଖୋଲିବା ନିଶ୍ଚିତ କରନ୍ତୁ',
    swal_confirm_close_valve: 'ଭାଲ୍ଭ ବନ୍ଦ କରିବା ନିଶ୍ଚିତ କରନ୍ତୁ',
    swal_cancel: 'ବାତିଲ୍ କରନ୍ତୁ',
    swal_confirm: 'ନିଶ୍ଚିତ କରନ୍ତୁ',
    swal_diversion_title: 'ଜରୁରୀକାଳୀନ ଜଳ ପ୍ରବାହ ମୋଡ଼ିବା ଆରମ୍ଭ କରିବେ?',
    swal_diversion_heading: 'ଜରୁରୀ ବର୍ଷା ଜଳ ନିଷ୍କାସନ କାର୍ଯ୍ୟାନୁଷ୍ଠାନ',
    swal_diversion_desc: 'ଭୂତଳ ସୋଲେନଏଡ୍ ଡାଇଭର୍ଟର ଭାଲ୍ଭ ଚାଳନ କଲେ {systemId} ରୁ ଅତିରିକ୍ତ ବର୍ଷାଜଳ ତୁରନ୍ତ ଭୂତଳ ଜଳଭଣ୍ଡାରକୁ ପ୍ରବାହିତ ହେବ।',
    swal_diversion_confirm: 'ହଁ, ବର୍ତ୍ତମାନ ଜଳ ମୋଡ଼ନ୍ତୁ',
    swal_location: 'ସ୍ଥାନ',
    swal_current_water_level: 'ବର୍ତ୍ତମାନର ଜଳ ସ୍ତର',
    swal_storage_cistern: 'ସଂରକ୍ଷଣ ଜଳଭଣ୍ଡାର',
    swal_critical_badge: 'ଜରୁରୀ',
    swal_capacity_available: 'କ୍ଷମତା ଉପଲବ୍ଧ',
    swal_sos_title: 'ଜରୁରୀକାଳୀନ SOS ପ୍ରେରଣ କରିବେ?',
    swal_sos_heading: 'ଗମ୍ଭୀର ବିପର୍ଯ୍ୟୟ ପ୍ରତିକ୍ରିୟା ସତର୍କତା',
    swal_sos_desc: 'ଏହା ପୌରସଂସ୍ଥା ବନ୍ୟା ନିୟନ୍ତ୍ରଣ କକ୍ଷ ଏବଂ ସ୍ଥାନୀୟ ଜରୁରୀକାଳୀନ କର୍ମଚାରୀଙ୍କୁ ତୁରନ୍ତ ଉଚ୍ଚ ପ୍ରାଥମିକତା ସତର୍କତା କୋର୍ଡିନେଟ୍ ପଠାଇବ।',
    swal_sos_confirm: 'ହଁ, SOS ପଠାନ୍ତୁ',
    swal_reboot_title: 'ESP32 କଣ୍ଟ୍ରୋଲର୍ ରିବୁଟ୍ କରିବେ?',
    swal_reboot_desc: 'ମାଇକ୍ରୋକଣ୍ଟ୍ରୋଲର୍ ପୁନରାରମ୍ଭ ହେବା ପର୍ଯ୍ୟନ୍ତ ପ୍ରାୟ ୩-୫ ସେକେଣ୍ଡ ପାଇଁ ଟେଲିମେଟ୍ରି ଷ୍ଟ୍ରିମିଂ ବନ୍ଦ ରହିବ।',
    swal_reboot_confirm: 'ହଁ, ନୋଡ୍ ରିବୁଟ୍ କରନ୍ତୁ',
    swal_reboot_success_title: 'ରିବୁଟ୍ ସିଗ୍ନାଲ୍ ପ୍ରେରିତ',
    swal_reboot_success_desc: 'ESP32 କଣ୍ଟ୍ରୋଲରକୁ ସଫ୍ଟ ସିଷ୍ଟମ୍ ରିସେଟ୍ କରିବାକୁ ନିର୍ଦ୍ଦେଶ ଦିଆଯାଇଛି।',
  },
  te: {
    appName: 'SUOWMRS',
    appSubtitle: 'నీటి పర్యవేక్షణ & పునర్వినియోగం',
    dashboard: 'అవలోకనం',
    waterMonitoring: 'నీటి పర్యవేక్షణ',
    alerts: 'హెచ్చరికలు & చరిత్ర',
    storage: 'భూగర్భ నిల్వ',
    waterReuse: 'నీటి పునర్వినియోగం',
    weather: 'వాతావరణ అంచనా',
    complaints: 'పౌర పోర్టల్',
    sos: 'అత్యవసర SOS',
    maintenance: 'నిర్వహణ కేంద్రం',
    systemHealth: 'సిస్టమ్ ఆరోగ్యం',
    sensors: 'సెన్సర్లు & వాల్వులు',
    esp32Diagnostics: 'ESP32 కంట్రోలర్',
    sensorDiagnostics: 'సెన్సార్లు & అమరిక',
    componentsHealth: 'యాక్చుయేటర్లు & రిలేలు',
    workOrders: 'పని ఆర్డర్లు & టిక్కెట్లు',
    adminDashboard: 'మున్సిపాలిటీ నియంత్రణ',
    userApprovals: 'వినియోగదారుల ఆమోదాలు',
    adminMap: 'GIS వరద మ్యాపింగ్',
    adminSystems: 'మల్టీ-సిస్టమ్ గ్రిడ్',
    adminComplaints: 'పౌర నివేదికలు',
    adminAnalytics: 'అంచనా విశ్లేషణ',
    aiPrediction: 'AI వరద అంచనా',
    myProfile: 'నా ప్రొఫైల్ & పాస్‌వర్డ్',
    signOut: 'సైన్ అవుట్',
    userVerificationTitle: 'వినియోగదారు ధృవీకరణ & ఆమోదాలు',
    userVerificationDesc: 'యాక్సెస్ మంజూరు చేయడానికి ముందు కొత్త నివాసి మరియు టెక్నీషియన్ రిజిస్ట్రేషన్లను ధృవీకరించండి.',
    pending: 'పెండింగ్‌లో ఉంది',
    verified: 'ధృవీకరించబడింది',
    rejected: 'తిరస్కరించబడింది',
    all: 'అన్నీ',
    refresh: 'రిఫ్రెష్',
    searchUser: 'వినియోగదారులను శోధించండి...',
    residentOps: 'నివాసి కార్యకలాపాలు',
    technicianSuite: 'టెక్నీషియన్ స్యూట్',
    municipalityAdmin: 'మున్సిపాలిటీ అడ్మిన్',
    live: 'నేరుగా',
    demoUser: 'డెమో వినియోగదారు',
    waterMonitoringTitle: 'నీటి పర్యవేక్షణ డాష్‌బోర్డ్',
    emergencySos: 'అత్యవసర SOS',
    reportIssue: 'సమస్యను నివేదించండి',
    waterLevel: 'నీటి స్థాయి',
    undergroundStorage: 'భూగర్భ నిల్వ',
    solenoidValve: 'సోలెనాయిడ్ వాల్వ్',
    liveDrainageTrend: 'నేరుగా నీటి స్థాయి ధోరణి',
    alertFeed: 'హెచ్చరిక ఫీడ్',
    treatmentTitle: 'నీటి శుద్ధి & పునర్వినియోగ జీవిత చక్రం',
    approvedReuseChannels: 'ఆమోదించిన పునర్వినియోగ ఛానెల్లు',
    gardening: 'తోటపని',
    cleaning: 'శుభ్రత',
    irrigation: 'నీటిపారుదల',
    construction: 'నిర్మాణం',
    industrial: 'పారిశ్రామిక',
    manualOverride: 'మాన్యువల్ ఓవర్‌రైడ్',
    openValve: 'వాల్వ్ తెరవండి',
    closeValve: 'వాల్వ్ మూయండి',
    totalStored: 'మొత్తం నిల్వ',
    treatedWater: 'శుద్ధి చేసిన నీరు',
    availableReuse: 'పునర్వినియోగానికి అందుబాటులో',
    language: 'భాష',
    role: 'పాత్ర',
    // Dynamic Backend Data & Alerts
    alert_normal: 'నీటి స్థాయి {level}% వద్ద సాధారణం. డ్రైనేజ్ ప్రవాహం స్థిరంగా ఉంది.',
    alert_warning: 'హెచ్చరిక: నీటి స్థాయి {level}% కి పెరుగుతోంది. నిశితంగా పర్యవేక్షిస్తున్నారు.',
    alert_danger: 'అధిక ప్రమాదం: నీటి స్థాయి {level}% వద్ద ఉంది! డైవర్టర్ వాల్వ్ ఆటోమేటిక్‌గా తెరవబడింది.',
    alert_critical: 'తీవ్రమైన వరద హెచ్చరిక: నీటి స్థాయి {level}% వద్ద ఉంది! అత్యవసర ప్రోటోకాల్ సక్రియం.',
    status_normal: 'సాధారణం',
    status_warning: 'హెచ్చరిక',
    status_danger: 'అధిక ప్రమాదం',
    status_critical: 'తీవ్రమైన వరద',
    status_high: 'అధిక ప్రమాదం',
    status_moderate: 'మధ్యస్థం',
    status_low: 'తక్కువ',
    status_none: 'సురక్షితం',
    valve_diverting: 'ప్రవాహాన్ని మళ్లిస్తోంది',
    valve_standby: 'స్టాండ్‌బై',
    valve_auto: 'ఆటోమేటిక్',
    valve_manual: 'మాన్యువల్',
    activeTank: 'యాక్టివ్ ట్యాంక్',
    current: 'ప్రస్తుతం',
    capacity: 'సామర్థ్యం',
    available: 'అందుబాటులో ఉంది',
    inflowRate: 'ఇన్‌ఫ్లో రేటు',
    empty: 'ఖాళీ',
    full: 'నిండినది',
    minToday: 'ఈ రోజు కనిష్టం',
    avgToday: 'ఈ రోజు సగటు',
    peakToday: 'ఈ రోజు గరిష్టం',
    unread: 'చదవనివి',
    noAlertsHealthy: 'హెచ్చరికలు లేవు — సిస్టమ్ సురక్షితం',
    autoUpdatesStream: 'లైవ్ Socket.io స్ట్రీమ్ నుండి ఆటో-అప్‌డేట్‌లు',
    quality: 'నాణ్యత',
    quality_good: 'మంచిది',
    quality_excellent: 'అద్భుతమైనది',
    quality_moderate: 'మధ్యస్థం',
    collected: 'సేకరించబడినది',
    efficiency: 'సమర్థత',
    distributed: 'పంపిణీ చేయబడింది',
    treatmentPhase: 'దశ 4: నిల్వ ప్రవాహం → వడపోత → ఆమోదిత మున్సిపల్ పంపిణీ',
    sensorsActive: 'సెన్సార్లు సక్రియం',
    offline: 'ఆఫ్‌లైన్',

    // TTS డ్యాష్‌బోర్డ్ ధ్వని కీలు
    tts_listen: 'వినండి',
    tts_listenAll: 'డ్యాష్‌బోర్డ్ వినండి',
    tts_stop: 'ఆపండి',
    tts_waterLevel: 'లైవ్ డ్రైనేజ్ నీటి స్థాయి {level} శాతం. సిస్టమ్ స్థితి {status}.',
    tts_storage: 'భూగర్భ నిల్వ {fill} శాతం నిండింది. ప్రస్తుత పరిమాణం {volume} లీటర్లు, మొత్తం సామర్థ్యం {capacity} లీటర్లు. {available} లీటర్లు అందుబాటులో.',
    tts_valve: 'సోలెనాయిడ్ వాల్వ్ స్థితి {status}. మోడ్ స్వయంచాలకం. ట్రిగ్గర్ స్థాయి 75 శాతం.',
    tts_floodBannerCritical: 'తీవ్రమైన వరద స్థాయి దాటింది! నీటి స్థాయి {level} శాతం. డైవర్టర్ వాల్వ్ {valve}.',
    tts_floodBannerWarning: 'నీటి స్థాయి పెరిగింది. నీటి స్థాయి {level} శాతం. డైవర్టర్ వాల్వ్ {valve}.',
    tts_dashSummary: 'డ్యాష్‌బోర్డ్ సారాంశం. నీటి స్థాయి {level} శాతం, స్థితి {status}. నిల్వ {fill} శాతం, {volume} లీటర్లు నిల్వ. వాల్వ్ {valve}. {alert}',
    tts_noAlerts: 'సక్రియ అలర్ట్లు లేవు. సిస్టమ్ ఆరోగ్యంగా ఉంది.',
    tts_alertCount: '{count} సక్రియ అలర్ట్లు.',
    tts_sirenWarning: 'సైరన్ హెచ్చరిక: వాల్వ్ తెరవబడింది.',

    // Common & Alerts Page UI keys
    markAllRead: 'అన్నీ చదివినట్లు గుర్తించు',
    searchAlertsPlaceholder: 'సందేశం లేదా స్థానం ద్వారా హెచ్చరికలను శోధించండి...',
    allClear: 'అంతా సురక్షితం',
    noAlertsFilter: 'ప్రస్తుత ఫిల్టర్‌తో ఏ హెచ్చరికలు సరిపోలడం లేదు.',
    alertStreamSubtitle: 'రియల్ టైమ్ హెచ్చరిక స్ట్రీమ్ · మొత్తం {total} రికార్డులు · ప్రతి 30 సెకన్లకు ఆటో-రిఫ్రెష్',
    justNow: 'ఇప్పుడే',
    minutesAgo: '{m} ని. క్రితం',
    hoursAgo: '{h} గం. క్రితం',
    daysAgo: '{d} రోజుల క్రితం',
    depth: 'లోతు',
    status: 'స్థితి',
    todayPeak: 'నేటి గరిష్టం',
    todayAvg: 'నేటి సగటు',
    state: 'స్థితి',
    triggerLevel: 'ట్రిగ్గర్ స్థాయి',
    mode: 'మోడ్',
    relay: 'రిలే',
    criticalFloodBanner: '🚨 క్లిష్టమైన వరద పరిమితి మించిపోయింది!',
    elevatedWaterBanner: '⚠️ పెరిగిన నీటి స్థాయి గుర్తించబడింది',
    excessInflow: 'అదనపు ప్రవాహం',
    primarySumpLevel: 'ప్రాథమిక సంప్ స్థాయి',
    peak24hWaterLevel: '24 గంటల గరిష్ట నీటి స్థాయి',
    maxRecordedToday: 'నేడు నమోదైన గరిష్టం',
    flowVelocity: 'డ్రైనేజీ ప్రవాహ వేగం',
    normalDischargeSpeed: 'సాధారణ డిశ్చార్జ్ వేగం',
    sensorTelemetry: 'IoT సెన్సార్ టెలిమెట్రీ',
    linePowerStable: 'లైన్ పవర్ స్థిరంగా ఉంది',
    page: 'పేజీ',
    of: 'లో',
    pageOf: 'పేజీ {page} / {pages} · మొత్తం {total} హెచ్చరికలు',
    previous: 'మునుపటి',
    next: 'తదుపరి',
    showingPage: 'పేజీ {page} / {pages} చూపిస్తోంది ({total} మొత్తం సిస్టమ్‌లు)',

    // Weather Page keys
    currentConditions: 'ప్రస్తుత పరిస్థితులు',
    rainfallSuffix: 'మిమీ/గం వర్షపాతం',
    intensitySuffix: 'తీవ్రత',
    humiditySuffix: 'తేమ',
    floodRiskLevel: 'వరద ప్రమాద స్థాయి',
    temperature: 'ఉష్ణోగ్రత',
    humidity: 'తేమ',
    windSpeed: 'గాలి వేగం',
    cloudCover: 'మేఘావృతం',
    hourlyRainfallForecast: 'గంటవారీ వర్షపాత అంచనా',
    forecastSummary: 'వాతావరణ సారాంశం',
    expectedTotalRainfall: 'అంచనా వేసిన మొత్తం వర్షపాతం',
    overNextHours: 'రాబోయే {hours} గంటల్లో',
    currentIntensity: 'ప్రస్తుత తీవ్రత',
    forecastDuration: 'అంచనా వ్యవధి',
    untilConditionsClear: 'వాతావరణం చక్కబడే వరకు',
    drainageImpact: 'డ్రైనేజీ ప్రభావం',
    estimatedDrainageLoad: 'అంచనా వేసిన డ్రైనేజీ భారం',
    weatherEngineNote: 'వాతావరణ సమాచారం నేరుగా AI వరద అంచనా ఇంజిన్ (దశ 7) కు అనుసంధానించబడింది.',
    weatherSubtitle: '{city}, {state} · హైడ్రోలాజికల్ రిస్క్ అనుసంధానం · ఆటో రిఫ్రెష్ 60s',
    now: 'ఇప్పుడు',
    risk_high_desc: 'భారీ వర్షపాతం నమోదైంది. డ్రైనేజీ వ్యవస్థలపై ఒత్తిడి. వరద ప్రమాదం ఎక్కువ.',
    risk_moderate_desc: 'మధ్యస్థ వర్షపాతం. నీటి స్థాయిలను పర్యవేక్షించండి.',
    risk_low_desc: 'తేలికపాటి వర్షం. వ్యవస్థలు సాధారణంగా పనిచేస్తున్నాయి. ముప్పు లేదు.',
    risk_none_desc: 'వర్షం లేదు. స్పష్టమైన వాతావరణం. అన్నీ సురక్షితం.',
    cond_heavy_monsoon: 'నీటి ముంపు హెచ్చరికతో కూడిన భారీ వర్షం',
    cond_light_rain: 'తేలికపాటి వర్షపు జల్లులు',
    cond_moderate_rain: 'మధ్యస్థ వర్షపాతం',
    cond_clear: 'స్వచ్ఛమైన ఆకాశం',
    cond_thunderstorm: 'తీవ్రమైన ఉరుములతో కూడిన తుఫాను',
    intensity_clear: 'స్పష్టం',
    intensity_light: 'తేలికపాటి వర్షం',
    intensity_moderate: 'మధ్యస్థం',
    intensity_heavy: 'భారీ వర్షం',
    intensity_violent: 'తీవ్రమైనది',
    impact_critical: 'క్లిష్టమైనది',
    impact_elevated: 'పెరిగినది',
    impact_normal: 'సాధారణం',
    quality_good: 'మంచిది',
    quality_excellent: 'అద్భుతమైనది',
    quality_moderate: 'మధ్యస్థం',
    quality_poor: 'చెడ్డది',
    pipeline: 'శుద్ధి పైప్‌లైన్',
    waterQuality: 'నీటి నాణ్యత',
    purificationEfficiency: 'శుద్ధి సామర్థ్యం',
    distributed: 'పంపిణీ చేయబడింది',
    allocatedSuffix: 'కేటాయించిన దానిలో',
    swal_valve_open_title: 'సోలేనోయిడ్ డైవర్టర్ వాల్వ్ తెరవాలా?',
    swal_valve_close_title: 'సోలేనోయిడ్ డైవర్టర్ వాల్వ్ మూసివేయాలా?',
    swal_valve_open_desc: 'వాల్వ్‌ను మాన్యువల్‌గా తెరవడం వల్ల డ్రైనేజీ నీరు వెంటనే భూగర్భ నిల్వ రిజర్వాయర్‌లోకి మళ్లించబడుతుంది.',
    swal_valve_close_desc: 'వాల్వ్‌ను మూసివేయడం వలన భూగర్భ నిల్వ మళ్లింపు ఆగిపోతుంది మరియు ప్రధాన తుఫాను డ్రైనేజీ మార్గం సక్రియంగా ఉంటుంది.',
    swal_confirm_open_valve: 'వాల్వ్ తెరవడం నిర్ధారించండి',
    swal_confirm_close_valve: 'వాల్వ్ మూసివేత నిర్ధారించండి',
    swal_cancel: 'రద్దు చేయండి',
    swal_confirm: 'నిర్ధారించండి',
    swal_diversion_title: 'అత్యవసర నీటి మళ్లింపును ప్రారంభించాలా?',
    swal_diversion_heading: 'తీవ్రమైన తుఫాను డ్రైనేజీ చర్య',
    swal_diversion_desc: 'భూగర్భ సోలేనోయిడ్ డైవర్టర్ వాల్వ్‌ను యాక్టివేట్ చేయడం ద్వారా {systemId} నుండి అదనపు తుఫాను నీరు వెంటనే భూగర్భ సిస్టర్న్ బఫర్‌లోకి మళ్లించబడుతుంది.',
    swal_diversion_confirm: 'అవును, నీటిని ఇప్పుడే మళ్లించండి',
    swal_location: 'స్థానం',
    swal_current_water_level: 'ప్రస్తుత నీటి స్థాయి',
    swal_storage_cistern: 'నిల్వ సిస్టర్న్',
    swal_critical_badge: 'క్లిష్టమైనది',
    swal_capacity_available: 'సామర్థ్యం అందుబాటులో ఉంది',
    swal_sos_title: 'అత్యవసర SOS డిస్పాచ్‌ను ట్రిగ్గర్ చేయాలా?',
    swal_sos_heading: 'తీవ్రమైన విపత్తు ప్రతిస్పందన హెచ్చరిక',
    swal_sos_desc: 'ఇది మునిసిపల్ వరద నియంత్రణ గది మరియు స్థానిక అత్యవసర సిబ్బందికి అధిక-ప్రాధాన్యత హెచ్చరిక కోఆర్డినేట్‌లను వెంటనే ప్రసారం చేస్తుంది.',
    swal_sos_confirm: 'అవును, SOS పంపండి',
    swal_reboot_title: 'ESP32 కంట్రోలర్‌ను రీబూట్ చేయాలా?',
    swal_reboot_desc: 'మైక్రోకంట్రోలర్ పునఃప్రారంభించబడే సమయంలో టెలిమెట్రీ స్ట్రీమింగ్ సుమారు 3-5 సెకన్లు పాజ్ అవుతుంది.',
    swal_reboot_confirm: 'అవును, నోడ్‌ను రీబూట్ చేయండి',
    swal_reboot_success_title: 'రీబూట్ సిగ్నల్ పంపబడింది',
    swal_reboot_success_desc: 'సాఫ్ట్ సిస్టమ్ రీసెట్ చేయడానికి ESP32 కంట్రోలర్‌కు సూచించబడింది.',
  },
  ta: {
    appName: 'SUOWMRS',
    appSubtitle: 'நீர் கண்காணிப்பு & மறுபயன்பாடு',
    dashboard: 'கண்ணோட்டம்',
    waterMonitoring: 'நீர் கண்காணிப்பு',
    alerts: 'எச்சரிக்கைகள் & வரலாறு',
    storage: 'நிலத்தடி சேமிப்பு',
    waterReuse: 'நீர் மறுபயன்பாடு',
    weather: 'வானிலை முன்னறிவிப்பு',
    complaints: 'குடிமக்கள் போர்டல்',
    sos: 'அவசர SOS',
    maintenance: 'பராமரிப்பு மையம்',
    systemHealth: 'கணினி ஆரோக்கியம்',
    sensors: 'சென்சார்கள் & வால்வுகள்',
    esp32Diagnostics: 'ESP32 கட்டுப்படுத்தி',
    sensorDiagnostics: 'சென்சார்கள் & அளவுத்திருத்தம்',
    componentsHealth: 'ஆக்சுவேட்டர்கள் & ரிலேக்கள்',
    workOrders: 'பணி ஆணைகள் & டிக்கெட்டுகள்',
    adminDashboard: 'நகராட்சி கட்டுப்பாடு',
    userApprovals: 'பயனர் ஒப்புதல்கள்',
    adminMap: 'GIS வெள்ள வரைபடம்',
    adminSystems: 'பல-அமைப்பு கட்டம்',
    adminComplaints: 'குடிமக்கள் அறிக்கைகள்',
    adminAnalytics: 'கணிப்பு பகுப்பாய்வு',
    aiPrediction: 'AI வெள்ள முன்னறிவிப்பு',
    myProfile: 'எனது சுயவிவரம் & கடவுச்சொல்',
    signOut: 'வெளியேறு',
    userVerificationTitle: 'பயனர் சரிபார்ப்பு & ஒப்புதல்கள்',
    userVerificationDesc: 'அணுகல் வழங்குவதற்கு முன் புதிய குடியிருப்பாளர் மற்றும் தொழில்நுட்ப வல்லுநர் பதிவுகளை சரிபார்க்கவும்.',
    pending: 'நிலுவையில் உள்ளது',
    verified: 'சரிபார்க்கப்பட்டது',
    rejected: 'நிராகரிக்கப்பட்டது',
    all: 'அனைத்தும்',
    refresh: 'புதுப்பி',
    searchUser: 'பயனர்களைத் தேடு...',
    residentOps: 'குடியிருப்பாளர் செயல்பாடுகள்',
    technicianSuite: 'தொழில்நுட்பவியலாளர் தொகுப்பு',
    municipalityAdmin: 'நகராட்சி நிர்வாகம்',
    live: 'நேரடி',
    demoUser: 'டெமோ பயனர்',
    waterMonitoringTitle: 'நீர் கண்காணிப்பு டாஷ்போர்டு',
    emergencySos: 'அவசர SOS',
    reportIssue: 'சிக்கலை புகாரளிக்கவும்',
    waterLevel: 'நீர் மட்டம்',
    undergroundStorage: 'நிலத்தடி சேமிப்பு',
    solenoidValve: 'சோலினாய்டு வால்வு',
    liveDrainageTrend: 'நேரடி நீர் மட்ட போக்கு',
    alertFeed: 'எச்சரிக்கை ஊட்டம்',
    treatmentTitle: 'நீர் சுத்திகரிப்பு & மறுபயன்பாட்டு சுழற்சி',
    approvedReuseChannels: 'அங்கீகரிக்கப்பட்ட மறுபயன்பாட்டு சேனல்கள்',
    gardening: 'தோட்டக்கலை',
    cleaning: 'சுத்தம்',
    irrigation: 'நீர்ப்பாசனம்',
    construction: 'கட்டுமானம்',
    industrial: 'தொழில்துறை',
    manualOverride: 'கைமுறை மேலெழுதல்',
    openValve: 'வால்வு திறக்கவும்',
    closeValve: 'வால்வு மூடவும்',
    totalStored: 'மொத்தம் சேமிக்கப்பட்டது',
    treatedWater: 'சுத்திகரிக்கப்பட்ட நீர்',
    availableReuse: 'மறுபயன்பாட்டிற்கு கிடைக்கும்',
    language: 'மொழி',
    role: 'பங்கு',
    // Dynamic Backend Data & Alerts
    alert_normal: 'நீர் மட்டம் {level}% இல் சாதாரணமாக உள்ளது. வடிகால் சீராக உள்ளது.',
    alert_warning: 'எச்சரிக்கை: நீர் மட்டம் {level}% ஆக உயர்கிறது. தீவிர கண்காணிப்பு.',
    alert_danger: 'அதிக ஆபத்து: நீர் மட்டம் {level}%! மாற்று வால்வு தானாக திறக்கப்பட்டது.',
    alert_critical: 'தீவிர வெள்ள எச்சரிக்கை: நீர் மட்டம் {level}%! அவசரகால நெறிமுறை செயல்படுத்தப்பட்டது.',
    status_normal: 'இயல்பு',
    status_warning: 'எச்சரிக்கை',
    status_danger: 'அதிக ஆபத்து',
    status_critical: 'தீவிர வெள்ளம்',
    status_high: 'அதிக ஆபத்து',
    status_moderate: 'மிதமானது',
    status_low: 'குறைவு',
    status_none: 'பாதுகாப்பானது',
    valve_diverting: 'நீர் திருப்பப்படுகிறது',
    valve_standby: 'தயார் நிலை',
    valve_auto: 'தானியங்கி',
    valve_manual: 'கைமுறை',
    activeTank: 'செயலில் உள்ள தொட்டி',
    current: 'தற்போதைய',
    capacity: 'கொள்ளளவு',
    available: 'கிடைக்கக்கூடியது',
    inflowRate: 'உள்வரவு விகிதம்',
    empty: 'வெற்று',
    full: 'முழு',
    minToday: 'இன்று குறைந்தபட்சம்',
    avgToday: 'இன்று சராசரி',
    peakToday: 'இன்று உச்சம்',
    unread: 'படிக்காதவை',
    noAlertsHealthy: 'எச்சரிக்கைகள் இல்லை — கணினி பாதுகாப்பானது',
    autoUpdatesStream: 'நேரலை Socket.io ஸ்ட்ரீமிலிருந்து தானாக புதுப்பிக்கப்படும்',
    quality: 'தரம்',
    quality_good: 'நல்லது',
    quality_excellent: 'சிறந்தது',
    quality_moderate: 'மிதமான',
    collected: 'சேகரிக்கப்பட்டது',
    efficiency: 'திறன்',
    distributed: 'விநியோகிக்கப்பட்டது',
    treatmentPhase: 'கட்டம் 4: சேமிக்கப்பட்ட நீர் → வடிகட்டுதல் → அங்கீகரிக்கப்பட்ட நகராட்சி விநியோகம்',
    sensorsActive: 'சென்சார்கள் செயலில் உள்ளன',
    offline: 'ஆஃப்லைன்',

    // TTS டாஷ்போர்ட் குரல் வட்டக் கீகள்
    tts_listen: 'கேளுங்கள்',
    tts_listenAll: 'டாஷ்போர்ட் கேளுங்கள்',
    tts_stop: 'நிறுத்துங்கள்',
    tts_waterLevel: 'நேரடி கழிவுநீர் நிலை {level} சதவிகிதம். கணினி நிலை {status}.',
    tts_storage: 'நிலத்தடி சேமிப்பகம் {fill} சதவிகிதம் நிறைந்துள்ளது. தற்போதைய அளவு {volume} லிட்டர், மொத்த திறன் {capacity} லிட்டர். {available} லிட்டர் கிடைக்கின்றது.',
    tts_valve: 'சோலெனாய்ட் வால்வ் நிலை {status}. மோட் தானியங்கி. டிரிக்கர் நிலை 75 சதவிகிதம்.',
    tts_floodBannerCritical: 'கடுமையான வெள்ள அளவு மிகுந்தது! நீர் நிலை {level} சதவிகிதம். டைவர்ட்டர் வால்வ் {valve}.',
    tts_floodBannerWarning: 'நீர் நிலை உயர்ந்துள்ளது. நீர் நிலை {level} சதவிகிதம். டைவர்ட்டர் வால்வ் {valve}.',
    tts_dashSummary: 'டாஷ்போர்ட் சுருக்கம். நீர் நிலை {level} சதவிகிதம், நிலை {status}. சேமிப்பகம் {fill} சதவிகிதம், {volume} லிட்டர் சேமிக்கப்பட்டது. வால்வ் {valve}. {alert}',
    tts_noAlerts: 'செயல்பாட்டிலுள்ள எச்சரிக்கைகள் இல்லை. கணினி ஆரோக்கியமாக உள்ளது.',
    tts_alertCount: '{count} செயல்பாட்டிலுள்ள எச்சரிக்கைகள்.',
    tts_sirenWarning: 'சைரன் எச்சரிக்கை: வால்வ் திறக்கப்பட்டது.',

    // Common & Alerts Page UI keys
    markAllRead: 'அனைத்தையும் படித்ததாகக் குறிக்கவும்',
    searchAlertsPlaceholder: 'செய்தி அல்லது இருப்பிடம் மூலம் விழிப்பூட்டல்களைத் தேடுங்கள்...',
    allClear: 'எல்லாம் பாதுகாப்பானது',
    noAlertsFilter: 'தற்போதைய வடிகட்டியுடன் எந்த விழிப்பூட்டல்களும் பொருந்தவில்லை.',
    alertStreamSubtitle: 'நிகழ்நேர விழிப்பூட்டல் ஸ்ட்ரீம் · மொத்தம் {total} பதிவுகள் · ஒவ்வொரு 30 வினாடிக்கும் தானியங்கி புதுப்பிப்பு',
    justNow: 'இப்போதுதான்',
    minutesAgo: '{m} நிமிடம் முன்பு',
    hoursAgo: '{h} மணி முன்பு',
    daysAgo: '{d} நாட்கள் முன்பு',
    depth: 'ஆழம்',
    status: 'நிலை',
    todayPeak: 'இன்றைய உச்சம்',
    todayAvg: 'இன்றைய சராசரி',
    state: 'நிலை',
    triggerLevel: 'தூண்டுதல் நிலை',
    mode: 'முறை',
    relay: 'ரிலே',
    criticalFloodBanner: '🚨 தீவிர வெள்ள அபாய வரம்பு தாண்டியது!',
    elevatedWaterBanner: '⚠️ உயர்ந்த நீர் மட்டம் கண்டறியப்பட்டது',
    excessInflow: 'உபரி உள்வரவு',
    primarySumpLevel: 'முதன்மை சம்ப் அளவு',
    peak24hWaterLevel: '24 மணி நேர உச்ச நீர் மட்டம்',
    maxRecordedToday: 'இன்று பதிவு செய்யப்பட்ட அதிகபட்சம்',
    flowVelocity: 'வடிகால் ஓட்ட வேகம்',
    normalDischargeSpeed: 'இயல்பான வெளியேற்ற வேகம்',
    sensorTelemetry: 'IoT சென்சார் டெலிமெட்ரி',
    linePowerStable: 'மின்சாரம் சீராக உள்ளது',
    page: 'பக்கம்',
    of: 'இல்',
    pageOf: 'பக்கம் {page} / {pages} · மொத்தம் {total} விழிப்பூட்டல்கள்',
    previous: 'முந்தைய',
    next: 'அடுத்தது',
    showingPage: 'பக்கம் {page} / {pages} காட்டப்படுகிறது ({total} மொத்த அமைப்புகள்)',

    // Weather Page keys
    currentConditions: 'தற்போதைய நிலைமைகள்',
    rainfallSuffix: 'மிமீ/மணி மழைப்பொழிவு',
    intensitySuffix: 'தீவிரம்',
    humiditySuffix: 'ஈரப்பதம்',
    floodRiskLevel: 'வெள்ள அபாய நிலை',
    temperature: 'வெப்பநிலை',
    humidity: 'ஈரப்பதம்',
    windSpeed: 'காற்றின் வேகம்',
    cloudCover: 'மேக மூட்டம்',
    hourlyRainfallForecast: 'மணிநேர மழை முன்னறிவிப்பு',
    forecastSummary: 'முன்னறிவிப்பு சுருக்கம்',
    expectedTotalRainfall: 'எதிர்பார்க்கப்படும் மொத்த மழை',
    overNextHours: 'அடுத்த {hours} மணி நேரத்தில்',
    currentIntensity: 'தற்போதைய தீவிரம்',
    forecastDuration: 'முன்னறிவிப்பு காலம்',
    untilConditionsClear: 'நிலைமை சீராகும் வரை',
    drainageImpact: 'வடிகால் தாக்கம்',
    estimatedDrainageLoad: 'மதிப்பிடப்பட்ட வடிகால் சுமை',
    weatherEngineNote: 'வானிலை தகவல்கள் நிகழ்நேர அபாய கணக்கீட்டிற்கு AI வெள்ள கணிப்பு இயந்திரத்திற்கு செல்கின்றன.',
    weatherSubtitle: '{city}, {state} · நீரியல் அபாய ஒருங்கிணைப்பு · தானியங்கி புதுப்பிப்பு 60 வினாடி',
    now: 'இப்போது',
    risk_high_desc: 'கனமழை கண்டறியப்பட்டது. வடிகால் அமைப்புகளில் அதிக அழுத்தம். வெள்ள அபாயம் அதிகரித்துள்ளது.',
    risk_moderate_desc: 'மிதமான மழை. நீர் மட்டத்தை கண்காணிக்கவும்.',
    risk_low_desc: 'லேசான மழை. அமைப்புகள் வழக்கம் போல் செயல்படுகின்றன. உடனடி அபாயம் இல்லை.',
    risk_none_desc: 'மழை இல்லை. தெளிவான வானிலை. அனைத்தும் பாதுகாப்பானது.',
    cond_heavy_monsoon: 'வெள்ள அபாய எச்சரிக்கையுடன் கூடிய பருவமழை புயல்',
    cond_light_rain: 'லேசான பருவமழை',
    cond_moderate_rain: 'மிதமான மழை',
    cond_clear: 'தெளிவான வானம்',
    cond_thunderstorm: 'கடும் இடியுடன் கூடிய மழை எச்சரிக்கை',
    intensity_clear: 'தெளிவானது',
    intensity_light: 'லேசான மழை',
    intensity_moderate: 'மிதமானது',
    intensity_heavy: 'கனமழை',
    intensity_violent: 'தீவிரமானது',
    impact_critical: 'தீவிரமானது',
    impact_elevated: 'உயர்ந்தது',
    impact_normal: 'இயல்பானது',
    quality_good: 'நல்லது',
    quality_excellent: 'சிறப்பானது',
    quality_moderate: 'மிதமானது',
    quality_poor: 'மோசமானது',
    pipeline: 'சுத்திகரிப்பு குழாய்',
    waterQuality: 'நீரின் தரம்',
    purificationEfficiency: 'சுத்திகரிப்பு திறன்',
    distributed: 'விநியோகிக்கப்பட்டது',
    allocatedSuffix: 'ஒதுக்கப்பட்டதில்',
    swal_valve_open_title: 'சோலனாய்டு டைவர்ட்டர் வால்வை திறக்கவா?',
    swal_valve_close_title: 'சோலனாய்டு டைவர்ட்டர் வால்வை மூடவா?',
    swal_valve_open_desc: 'வால்வை கைமுறையாக திறப்பது வடிகால் நீரை உடனடியாக நிலத்தடி நீர்த்தேக்கத்திற்கு திருப்பும்.',
    swal_valve_close_desc: 'வால்வை மூடுவது நிலத்தடி சேமிப்பு திருப்பலை நிறுத்தி, முக்கிய புயல் வடிகால் பாதையை செயலில் வைத்திருக்கும்.',
    swal_confirm_open_valve: 'வால்வு திறப்பை உறுதிசெய்க',
    swal_confirm_close_valve: 'வால்வு மூடுவதை உறுதிசெய்க',
    swal_cancel: 'ரத்து செய்க',
    swal_confirm: 'உறுதிசெய்க',
    swal_diversion_title: 'அவசர கால நீர் திருப்பலைத் தொடங்கவா?',
    swal_diversion_heading: 'தீவிர புயல் வடிகால் நடவடிக்கை',
    swal_diversion_desc: 'நிலத்தடி சோலனாய்டு டைவர்ட்டர் வால்வை இயக்குவது {systemId} இலிருந்து அதிகப்படியான புயல் நீரை உடனடியாக நிலத்தடி தொட்டிக்கு அனுப்பும்.',
    swal_diversion_confirm: 'ஆம், தண்ணீரை இப்போது திருப்புக',
    swal_location: 'இடம்',
    swal_current_water_level: 'தற்போதைய நீர் மட்டம்',
    swal_storage_cistern: 'சேமிப்பு தொட்டி',
    swal_critical_badge: 'தீவிரமானது',
    swal_capacity_available: 'கொள்ளளவு உள்ளது',
    swal_sos_title: 'அவசர கால SOS அனுப்புதலைத் தொடங்கவா?',
    swal_sos_heading: 'தீவிர பேரிடர் மீட்பு எச்சரிக்கை',
    swal_sos_desc: 'இது நகராட்சி வெள்ள கட்டுப்பாட்டு அறை மற்றும் உள்ளூர் அவசர பணியாளர்களுக்கு உயர் முன்னுரிமை எச்சரிக்கை ஒருங்கிணைப்புகளை உடனடியாக அனுப்பும்.',
    swal_sos_confirm: 'ஆம், SOS அனுப்பு',
    swal_reboot_title: 'ESP32 கன்ட்ரோலரை மறுதொடக்கம் செய்யவா?',
    swal_reboot_desc: 'மைக்ரோகண்ட்ரோலர் மறுதொடக்கம் செய்யப்படும் போது டெலிமெட்ரி ஸ்ட்ரீமிங் சுமார் 3-5 வினாடிகள் இடைநிறுத்தப்படும்.',
    swal_reboot_confirm: 'ஆம், முனையத்தை மறுதொடக்கம் செய்',
    swal_reboot_success_title: 'மறுதொடக்க சிக்னல் அனுப்பப்பட்டது',
    swal_reboot_success_desc: 'ESP32 கன்ட்ரோலருக்கு மென்மையான கணினி மீட்டமைப்பை செய்ய அறிவுறுத்தப்பட்டுள்ளது.',
  },
  bn: {
    appName: 'SUOWMRS',
    appSubtitle: 'জল পর্যবেক্ষণ ও পুনর্ব্যবহার',
    dashboard: 'সংক্ষিপ্ত বিবরণ',
    waterMonitoring: 'জল পর্যবেক্ষণ',
    alerts: 'সতর্কতা ও ইতিহাস',
    storage: 'ভূগর্ভস্থ সঞ্চয়',
    waterReuse: 'জল পুনর্ব্যবহার',
    weather: 'আবহাওয়ার পূর্বাভাস',
    complaints: 'নাগরিক পোর্টাল',
    sos: 'জরুরি SOS',
    maintenance: 'রক্ষণাবেক্ষণ কেন্দ্র',
    systemHealth: 'সিস্টেম স্বাস্থ্য',
    sensors: 'সেন্সর ও ভাল্ব',
    esp32Diagnostics: 'ESP32 কন্ট্রোলার',
    sensorDiagnostics: 'সেন্সর ও ক্রমাঙ্কন',
    componentsHealth: 'অ্যাকচুয়েটর ও রিলে',
    workOrders: 'কাজের আদেশ ও টিকিট',
    adminDashboard: 'পৌরসভা নিয়ন্ত্রণ',
    userApprovals: 'ব্যবহারকারী অনুমোদন',
    adminMap: 'GIS বন্যা মানচিত্র',
    adminSystems: 'মাল্টি-সিস্টেম গ্রিড',
    adminComplaints: 'নাগরিক প্রতিবেদন',
    adminAnalytics: 'পূর্বাভাস বিশ্লেষণ',
    aiPrediction: 'এআই বন্যা পূর্বাভাস',
    myProfile: 'আমার প্রোফাইল এবং পাসওয়ার্ড',
    signOut: 'সাইন আউট',
    userVerificationTitle: 'ব্যবহারকারী যাচাইকরণ এবং অনুমোদন',
    userVerificationDesc: 'নেটওয়ার্ক অ্যাক্সেস দেওয়ার আগে নতুন বাসিন্দা এবং টেকনিশিয়ান রেজিস্ট্রেশন যাচাই করুন।',
    pending: 'বিবেচনাধীন',
    verified: 'যাচাইকৃত',
    rejected: 'প্রত্যাখ্যাত',
    all: 'সব',
    refresh: 'রিফ্রেশ',
    searchUser: 'ব্যবহারকারী খুঁজুন...',
    residentOps: 'বাসিন্দা কার্যক্রম',
    technicianSuite: 'টেকনিশিয়ান স্যুট',
    municipalityAdmin: 'পৌরসভা প্রশাসন',
    live: 'সরাসরি',
    demoUser: 'ডেমো ব্যবহারকারী',
    waterMonitoringTitle: 'জল পর্যবেক্ষণ ড্যাশবোর্ড',
    emergencySos: 'জরুরি SOS',
    reportIssue: 'সমস্যা রিপোর্ট করুন',
    waterLevel: 'জলের স্তর',
    undergroundStorage: 'ভূগর্ভস্থ সঞ্চয়',
    solenoidValve: 'সোলেনয়েড ভাল্ব',
    liveDrainageTrend: 'সরাসরি জলের স্তর প্রবণতা',
    alertFeed: 'সতর্কতা ফিড',
    treatmentTitle: 'জল পরিশোধন ও পুনর্ব্যবহার জীবনচক্র',
    approvedReuseChannels: 'অনুমোদিত পুনর্ব্যবহার চ্যানেল',
    gardening: 'বাগান',
    cleaning: 'পরিষ্কার',
    irrigation: 'সেচ',
    construction: 'নির্মাণ',
    industrial: 'শিল্প',
    manualOverride: 'ম্যানুয়াল ওভাররাইড',
    openValve: 'ভাল্ব খুলুন',
    closeValve: 'ভাল্ব বন্ধ করুন',
    totalStored: 'মোট সঞ্চিত',
    treatedWater: 'পরিশোধিত জল',
    availableReuse: 'পুনর্ব্যবহারের জন্য উপলব্ধ',
    language: 'ভাষা',
    role: 'ভূমিকা',
    // Dynamic Backend Data & Alerts
    alert_normal: 'জলের স্তর {level}% এ স্বাভাবিক। নিকাশী নিষ্কাশন স্থিতিশীল।',
    alert_warning: 'সতর্কতা: জলের স্তর বেড়ে {level}% হয়েছে। নিবিড় নজরদারি।',
    alert_danger: 'উচ্চ ঝুঁকি: জলের স্তর {level}%! ডাইভার্টার ভালভ স্বয়ংক্রিয়ভাবে খোলা হয়েছে।',
    alert_critical: 'গুরুতর বন্যা সতর্কতা: জলের স্তর {level}%! জরুরি প্রোটোকল সক্রিয়।',
    status_normal: 'স্বাভাবিক',
    status_warning: 'সতর্কতা',
    status_danger: 'উচ্চ ঝুঁকি',
    status_critical: 'গুরুতর বন্যা',
    status_high: 'উচ্চ ঝুঁকি',
    status_moderate: 'মাঝারি',
    status_low: 'কম',
    status_none: 'নিরাপদ',
    valve_diverting: 'প্রবাহ পরিবর্তন হচ্ছে',
    valve_standby: 'স্ট্যান্ডবাই',
    valve_auto: 'স্বয়ংক্রিয়',
    valve_manual: 'ম্যানুয়াল',
    activeTank: 'সক্রিয় ট্যাঙ্ক',
    current: 'বর্তমান',
    capacity: 'ক্ষমতা',
    available: 'উপলব্ধ',
    inflowRate: 'প্রবাহের হার',
    empty: 'খালি',
    full: 'পূর্ণ',
    minToday: 'আজকের সর্বনিম্ন',
    avgToday: 'আজকের গড়',
    peakToday: 'আজকের সর্বোচ্চ',
    unread: 'অপঠিত',
    noAlertsHealthy: 'কোনো সতর্কতা নেই — সিস্টেম সুরক্ষিত',
    autoUpdatesStream: 'লাইভ Socket.io স্ট্রিম থেকে স্বয়ংক্রিয় আপডেট',
    quality: 'মান',
    quality_good: 'ভালো',
    quality_excellent: 'চমৎকার',
    quality_moderate: 'মাঝারি',
    collected: 'সংগৃহীত',
    efficiency: 'দক্ষতা',
    distributed: 'বিতরণকৃত',
    treatmentPhase: 'পর্যায় ৪: সঞ্চিত অন্তর্মুখী জল → পরিস্রাবণ → অনুমোদিত পৌর বন্টন',
    sensorsActive: 'সেন্সর সক্রিয়',
    offline: 'অফলাইন',

    // TTS ড্যাশবোর্ড ধ্বনি কী
    tts_listen: 'শুনুন',
    tts_listenAll: 'ড্যাশবোর্ড শুনুন',
    tts_stop: 'থামুন',
    tts_waterLevel: 'লাইভ নিষ্কাশন জল স্তর {level} শতাংশ। সিস্টেম অবস্থা {status}।',
    tts_storage: 'ভূগর্ভ সংরক্ষণাগার {fill} শতাংশ পূর্ণ। বর্তমান পরিমাণ {volume} লিটার, মোট ধারণক্ষমতা {capacity} লিটার। {available} লিটার পাওয়া যাবে।',
    tts_valve: 'সোলেনয়ড ভাল্ভের অবস্থা {status}। মোড স্বয়ংক্রিয়। ট্রিগার স্তর 75 শতাংশ।',
    tts_floodBannerCritical: 'গুরুতর বন্যা সীমা অতিক্রম! জল স্তর {level} শতাংশ। ডাইভার্টার ভাল্ভ {valve}।',
    tts_floodBannerWarning: 'জল স্তর বেড়েছে। জল স্তর {level} শতাংশ। ডাইভার্টার ভাল্ভ {valve}।',
    tts_dashSummary: 'ড্যাশবোর্ড সারসংক্ষেপ। জল স্তর {level} শতাংশ, অবস্থা {status}। সংরক্ষণাগার {fill} শতাংশ, {volume} লিটার সংরক্ষিত। ভাল্ভ {valve}। {alert}',
    tts_noAlerts: 'কোনো সক্রিয় সতর্কতা নেই। সিস্টেম সুরক্ষিত।',
    tts_alertCount: '{count} সক্রিয় সতর্কতা।',
    tts_sirenWarning: 'সাইরেন সতর্কতা: ভাল্ভ খোলা হয়েছে।',

    // Common & Alerts Page UI keys
    markAllRead: 'সব পড়া হিসেবে চিহ্নিত করুন',
    searchAlertsPlaceholder: 'বার্তা বা অবস্থান অনুযায়ী সতর্কতা খুঁজুন...',
    allClear: 'সব ঠিক আছে',
    noAlertsFilter: 'বর্তমান ফিল্টারের সাথে কোনো সতর্কতা মিলছে না।',
    alertStreamSubtitle: 'রিয়েল-টাইম সতর্কতা স্ট্রিম · মোট {total} রেকর্ড · প্রতি ৩০ সেকেন্ডে স্বয়ংক্রিয় রিফ্রেশ',
    justNow: 'এইমাত্র',
    minutesAgo: '{m} মি. আগে',
    hoursAgo: '{h} ঘণ্টা আগে',
    daysAgo: '{d} দিন আগে',
    depth: 'গভীরতা',
    status: 'অবস্থা',
    todayPeak: 'আজকের সর্বোচ্চ',
    todayAvg: 'আজকের গড়',
    state: 'অবস্থা',
    triggerLevel: 'ট্রিগার স্তর',
    mode: 'মোড',
    relay: 'রিলে',
    criticalFloodBanner: '🚨 বিপজ্জনক বন্যা সীমা অতিক্রম করেছে!',
    elevatedWaterBanner: '⚠️ উচ্চ জলস্তর সনাক্ত করা হয়েছে',
    excessInflow: 'অতিরিক্ত অন্তর্বাহ',
    primarySumpLevel: 'প্রাথমিক সাম্প স্তর',
    peak24hWaterLevel: '২৪ ঘণ্টার সর্বোচ্চ জলস্তর',
    maxRecordedToday: 'আজকে রেকর্ড করা সর্বোচ্চ',
    flowVelocity: 'নিষ্কাশন প্রবাহ বেগ',
    normalDischargeSpeed: 'স্বাভাবিক নিষ্কাশন গতি',
    sensorTelemetry: 'IoT সেন্সর টেলিমেট্রি',
    linePowerStable: 'লাইন পাওয়ার স্থিতিশীল',
    page: 'পৃষ্ঠা',
    of: 'এর',
    pageOf: 'পৃষ্ঠা {page} / {pages} · মোট {total} সতর্কতা',
    previous: 'পূর্ববর্তী',
    next: 'পরবর্তী',
    showingPage: 'পৃষ্ঠা {page} / {pages} প্রদর্শন করা হচ্ছে ({total} মোট সিস্টেম)',

    // Weather Page keys
    currentConditions: 'বর্তমান পরিস্থিতি',
    rainfallSuffix: 'মিমি/ঘণ্টা বৃষ্টিপাত',
    intensitySuffix: 'তীব্রতা',
    humiditySuffix: 'আর্দ্রতা',
    floodRiskLevel: 'বন্যা ঝুঁকি স্তর',
    temperature: 'তাপমাত্রা',
    humidity: 'আর্দ্রতা',
    windSpeed: 'বাতাসের গতি',
    cloudCover: 'মেঘের আচ্ছাদন',
    hourlyRainfallForecast: 'ঘণ্টাভিত্তিক বৃষ্টিপাতের পূর্বাভাস',
    forecastSummary: 'পূর্বাভাস সারসংক্ষেপ',
    expectedTotalRainfall: 'প্রত্যাশিত মোট বৃষ্টিপাত',
    overNextHours: 'পরবর্তী {hours} ঘণ্টায়',
    currentIntensity: 'বর্তমান তীব্রতা',
    forecastDuration: 'পূর্বাভাস সময়কাল',
    untilConditionsClear: 'পরিস্থিতি স্বাভাবিক না হওয়া পর্যন্ত',
    drainageImpact: 'নিষ্কাশন প্রভাব',
    estimatedDrainageLoad: 'আনুমানিক নিষ্কাশন চাপ',
    weatherEngineNote: 'আবহাওয়ার তথ্য সরাসরি AI বন্যা পূর্বাভাস ইঞ্জিনে (পর্যায় ৭) যুক্ত হয়।',
    weatherSubtitle: '{city}, {state} · হাইড্রোলজিক্যাল ঝুঁকি সমন্বয় · স্বয়ংক্রিয় রিফ্রেশ ৬০s',
    now: 'এখন',
    risk_high_desc: 'ভারী বৃষ্টিপাত সনাক্ত হয়েছে। নিষ্কাশন ব্যবস্থায় তীব্র চাপ। বন্যার ঝুঁকি বেশি।',
    risk_moderate_desc: 'মাঝারি বৃষ্টিপাত। জলস্তর পর্যবেক্ষণ করুন।',
    risk_low_desc: 'হালকা বৃষ্টি। সিস্টেম স্বাভাবিকভাবে কাজ করছে। কোনো তাৎক্ষণিক ঝুঁকি নেই।',
    risk_none_desc: 'বৃষ্টিপাত নেই। পরিষ্কার আকাশ। সব সুরক্ষিত।',
    cond_heavy_monsoon: 'সক্রিয় জলমগ্নতা সতর্কতাসহ বর্ষার বজ্রঝড়',
    cond_light_rain: 'হালকা বর্ষার বৃষ্টি',
    cond_moderate_rain: 'মাঝারি বৃষ্টিপাত',
    cond_clear: 'পরিষ্কার আকাশ',
    cond_thunderstorm: 'তীব্র বজ্রঝড় সতর্কতা',
    intensity_clear: 'পরিষ্কার',
    intensity_light: 'হালকা বৃষ্টি',
    intensity_moderate: 'মাঝারি',
    intensity_heavy: 'ভারী বৃষ্টি',
    intensity_violent: 'প্রচণ্ড',
    impact_critical: 'গুরুতর',
    impact_elevated: 'উচ্চ',
    impact_normal: 'স্বাভাবিক',
    quality_good: 'ভালো',
    quality_excellent: 'চমৎকার',
    quality_moderate: 'মাঝারি',
    quality_poor: 'খারাপ',
    pipeline: 'পরিশোধন পাইপলাইন',
    waterQuality: 'জলের গুণমান',
    purificationEfficiency: 'পরিশোধন দক্ষতা',
    distributed: 'বিতরিত',
    allocatedSuffix: 'বরাদ্দকৃতের',
    swal_valve_open_title: 'সোলেলিনয়েড ডাইভার্টার ভালভ খুলবেন?',
    swal_valve_close_title: 'সোলেলিনয়েড ডাইভার্টার ভালভ বন্ধ করবেন?',
    swal_valve_open_desc: 'ম্যানুয়ালি ভালভ খুললে নিষ্কাশন জল অবিলম্বে ভূগর্ভস্থ জলাধারে ঘুরিয়ে দেওয়া হবে।',
    swal_valve_close_desc: 'ভালভ বন্ধ করলে ভূগর্ভস্থ সংরক্ষণ ঘুরানো বন্ধ হবে এবং প্রধান ঝড় নিকাশী পথ সক্রিয় থাকবে।',
    swal_confirm_open_valve: 'ভালভ খোলা নিশ্চিত করুন',
    swal_confirm_close_valve: 'ভালভ বন্ধ নিশ্চিত করুন',
    swal_cancel: 'বাতিল করুন',
    swal_confirm: 'নিশ্চিত করুন',
    swal_diversion_title: 'জরুরি জল পরিবর্তন শুরু করবেন?',
    swal_diversion_heading: 'গুরুতর ঝড় নিষ্কাশন পদক্ষেপ',
    swal_diversion_desc: 'ভূগর্ভস্থ সোলেলিনয়েড ডাইভার্টার ভালভ সক্রিয় করলে {systemId} থেকে অতিরিক্ত বৃষ্টির জল সরাসরি ভূগর্ভস্থ জলাধারে চলে যাবে।',
    swal_diversion_confirm: 'হ্যাঁ, জল এখনই ঘুরিয়ে দিন',
    swal_location: 'অবস্থান',
    swal_current_water_level: 'বর্তমান জলের স্তর',
    swal_storage_cistern: 'সংরক্ষণ জলাধার',
    swal_critical_badge: 'গুরুতর',
    swal_capacity_available: 'ধারণক্ষমতা উপলব্ধ',
    swal_sos_title: 'জরুরি SOS প্রেরণ ট্রিগার করবেন?',
    swal_sos_heading: 'গুরুতর দুর্যোগ প্রতিক্রিয়া সতর্কতা',
    swal_sos_desc: 'এটি অবিলম্বে পৌর বন্যা নিয়ন্ত্রণ কক্ষ এবং স্থানীয় জরুরি কর্মীদের কাছে উচ্চ-অগ্রাধিকার সতর্কতা স্থানাঙ্ক প্রেরণ করবে।',
    swal_sos_confirm: 'হ্যাঁ, SOS পাঠান',
    swal_reboot_title: 'ESP32 কন্ট্রোলার রিবুট করবেন?',
    swal_reboot_desc: 'মাইক্রোকন্ট্রোলার পুনরায় চালু হওয়ার সময় টেলিমেট্রি স্ট্রিমিং প্রায় ৩-৫ সেকেন্ডের জন্য থামবে।',
    swal_reboot_confirm: 'হ্যাঁ, নোড রিবুট করুন',
    swal_reboot_success_title: 'রিবুট সংকেত পাঠানো হয়েছে',
    swal_reboot_success_desc: 'ESP32 কন্ট্রোলারকে সফট সিস্টেম রিসেট করার নির্দেশ দেওয়া হয়েছে।',
  },
};

const LanguageContext = createContext(null);

export const getActiveLanguage = () => {
  try {
    const saved = localStorage.getItem('suowmrs_lang') || localStorage.getItem('suowmrs-lang');
    if (saved && LANGUAGES.some(l => l.code === saved)) {
      return saved;
    }
    return 'en';
  } catch {
    return 'en';
  }
};

export const getTranslation = (key, customLang) => {
  const lang = customLang || getActiveLanguage();
  return translations[lang]?.[key] ?? translations['en']?.[key] ?? key;
};

const DIGIT_MAPS = {
  hi: ['०', '१', '२', '३', '४', '५', '६', '७', '८', '९'],
  or: ['୦', '୧', '୨', '୩', '୪', '୫', '୬', '୭', '୮', '୯'],
  bn: ['০', '১', '২', '৩', '৪', '৫', '৬', '৭', '৮', '৯'],
  te: ['౦', '౧', '౨', '౩', '౪', '౫', '౬', '౭', '౮', '౯'],
  ta: ['௦', '௧', '௨', '௩', '௪', '௫', '௬', '௭', '௮', '௯'],
};

export function LanguageProvider({ children }) {
  const [lang, setLangState] = useState(() => {
    try {
      const saved = localStorage.getItem('suowmrs_lang') || localStorage.getItem('suowmrs-lang');
      if (saved && LANGUAGES.some(l => l.code === saved)) {
        return saved;
      }
      return 'en';
    } catch {
      return 'en';
    }
  });

  useEffect(() => {
    try {
      if (lang) {
        localStorage.setItem('suowmrs_lang', lang);
        localStorage.setItem('suowmrs-lang', lang);
        document.documentElement.lang = lang;
      }
    } catch (e) {
      console.warn('LocalStorage unavailable for language setting', e);
    }
  }, [lang]);

  const setLang = (newLang) => {
    if (newLang && LANGUAGES.some(l => l.code === newLang)) {
      setLangState(newLang);
      try {
        localStorage.setItem('suowmrs_lang', newLang);
        localStorage.setItem('suowmrs-lang', newLang);
      } catch (e) {
        console.warn('LocalStorage unavailable for language setting', e);
      }
    }
  };

  const t = (key) => translations[lang]?.[key] ?? translations['en']?.[key] ?? key;

  // Helper to convert numbers to localized digits
  const localizeNumber = (num) => {
    if (num == null) return '';
    const str = String(num);
    const map = DIGIT_MAPS[lang];
    if (!map) return str;
    return str.replace(/\d/g, (d) => map[Number(d)] ?? d);
  };

  // Helper to translate alerts dynamically with level interpolation
  const formatAlert = (alert) => {
    if (!alert) return '';
    const key = alert.messageKey || (alert.type ? `alert_${alert.type}` : null);
    const template = key ? t(key) : null;
    let levelStr = alert.level != null ? Number(alert.level).toFixed(1) : null;
    if (!levelStr && alert.message) {
      const match = String(alert.message).match(/(\d+(?:\.\d+)?)\s*%/);
      if (match) levelStr = match[1];
    }
    if (template && template.includes('{level}')) {
      return template.replace('{level}', levelStr ? localizeNumber(levelStr) : '—');
    }
    return template || alert.message || '';
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang, language: lang, changeLanguage: setLang, t, formatAlert, localizeNumber, LANGUAGES }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error('useLanguage must be used within a LanguageProvider');
  return ctx;
}
