import React, { createContext, useContext, useState, useEffect } from 'react';

// ── Supported Indian Languages ──
export const LANGUAGES = [
  { code: 'en', label: 'English', native: 'English' },
  { code: 'hi', label: 'Hindi', native: 'हिंदी' },
  { code: 'or', label: 'Odia', native: 'ଓଡ଼ିଆ' },
  { code: 'te', label: 'Telugu', native: 'తెలుగు' },
  { code: 'ta', label: 'Tamil', native: 'தமிழ்' },
  { code: 'bn', label: 'Bengali', native: 'বাংলা' },
];

// ── Translation Dictionary ──
const translations = {
  en: {
    appName: 'SUOWMRS',
    appSubtitle: 'Water Monitoring & Reuse',
    dashboard: 'Overview',
    waterMonitoring: 'Water Monitoring',
    alerts: 'Alerts & History',
    storage: 'Underground Storage',
    waterReuse: 'Water Reuse & Quality',
    weather: 'Weather Forecast',
    complaints: 'Citizen Portal',
    sos: 'Emergency SOS',
    maintenance: 'Maintenance Hub',
    systemHealth: 'System Health',
    sensors: 'Sensors & Valves',
    esp32Diagnostics: 'ESP32 Controller',
    sensorDiagnostics: 'Sensors & Calibration',
    componentsHealth: 'Actuators & Relays',
    workOrders: 'Work Orders & Tickets',
    adminDashboard: 'Municipality Control',
    userApprovals: 'User Approvals',
    adminMap: 'GIS Flood Mapping',
    adminSystems: 'Multi-System Grid',
    adminComplaints: 'Citizen Reports',
    adminAnalytics: 'Predictive Analytics',
    aiPrediction: 'AI Flood Prediction',
    myProfile: 'My Profile & Password',
    signOut: 'Sign Out',
    userVerificationTitle: 'User Verification & Approvals',
    userVerificationDesc: 'Verify incoming Resident and Technician registrations before granting access.',
    pending: 'Pending',
    verified: 'Verified',
    rejected: 'Rejected',
    all: 'All',
    refresh: 'Refresh',
    searchUser: 'Search users...',
    residentOps: 'Resident Operations',
    technicianSuite: 'Technician Suite',
    municipalityAdmin: 'Municipality Admin',
    live: 'Live',
    demoUser: 'Demo User',
    waterMonitoringTitle: 'Water Monitoring Dashboard',
    emergencySos: 'Emergency SOS',
    reportIssue: 'Report Issue',
    waterLevel: 'Water Level',
    undergroundStorage: 'Underground Storage',
    solenoidValve: 'Solenoid Valve',
    liveDrainageTrend: 'Live Drainage Trend',
    alertFeed: 'Alert Feed',
    treatmentTitle: 'Water Treatment & Reuse Lifecycle',
    approvedReuseChannels: 'Approved Reuse Channels',
    gardening: 'Gardening',
    cleaning: 'Cleaning',
    irrigation: 'Irrigation',
    construction: 'Construction',
    industrial: 'Industrial',
    manualOverride: 'Manual Override',
    openValve: 'Open Valve',
    closeValve: 'Close Valve',
    totalStored: 'Total Stored',
    treatedWater: 'Treated Water',
    availableReuse: 'Available for Reuse',
    language: 'Language',
    role: 'Role',
    // Dynamic Backend Data & Alerts
    alert_normal: 'Water level normal at {level}%. Drainage flow stable.',
    alert_warning: 'Caution: Rising water level at {level}%. Monitoring closely.',
    alert_danger: 'HIGH RISK: Water level at {level}%! Diverter valve auto-opened.',
    alert_critical: 'CRITICAL FLOOD ALERT: Water level at {level}%! Emergency protocol active.',
    status_normal: 'NORMAL',
    status_warning: 'WARNING',
    status_danger: 'HIGH RISK',
    status_critical: 'CRITICAL FLOOD',
    valve_diverting: 'Diverting Flow',
    valve_standby: 'Standby',
    valve_auto: 'Automatic',
    valve_manual: 'Manual',
    activeTank: 'Active Tank',
    current: 'Current',
    capacity: 'Capacity',
    available: 'Available',
    inflowRate: 'Inflow Rate',
    empty: 'Empty',
    full: 'Full',
    minToday: 'MIN TODAY',
    avgToday: 'AVG TODAY',
    peakToday: 'PEAK TODAY',
    unread: 'Unread',
    noAlertsHealthy: 'No alerts — System healthy',
    autoUpdatesStream: 'Auto-updates from live Socket.io stream',
    quality: 'Quality',
    quality_good: 'GOOD',
    quality_excellent: 'EXCELLENT',
    quality_moderate: 'MODERATE',
    collected: 'Collected',
    efficiency: 'Efficiency',
    distributed: 'Distributed',
    treatmentPhase: 'Phase 4: Stored Inflow → Filtration → Approved Municipal Distribution',
    sensorsActive: 'Sensors Active',
    offline: 'Offline',

    // Landing Page & Footer Keys
    home: 'Home',
    residentPortal: 'Resident Portal',
    signIn: 'Sign In',
    heroBadge: 'Smart Underground Overflow Water Management and Reuse System (SUOWMRS)',
    heroTitle1: 'One Smart Platform for',
    heroTitle2: 'Flood, Rainwater & Greywater Management',
    heroDesc: 'A next-generation AI & IoT platform for smart flood prevention, rainwater harvesting, greywater recycling, and real-time water management—all in one intelligent underground system.',
    sensorsMonitored: 'Sensors Monitored',
    liveWaterLevel: 'Live Water Level',
    storedWater: 'Stored Water',
    autoValveStatus: 'Auto Valve Status',
    totalFloodPrevented: 'Total Flood Volume Prevented',
    activeIoTNodes: 'Active IoT Sensor Nodes',
    systemUptime: 'System Telemetry Uptime',
    treatedWaterReused: 'Treated Water Reused',
    ecosystemBlueprint: 'The 7-Phase SUOWMRS Ecosystem',
    tailoredExperience: 'Built for 3 Essential User Roles',
    openResidentView: 'Open Resident View',
    technicianHub: 'Technician Hub',
    footerFoundation: 'SUOWMRS Smart Water Platform',
    allRightsReserved: 'All rights reserved.',
    step1Title: '1. IoT Sensing',
    step1Desc: 'Ultrasonic depth sensors track drain water column levels every 5 seconds.',
    step2Title: '2. Auto Diversion',
    step2Desc: 'Solenoid valves actuate at 75% depth threshold, funneling runoff underground.',
    step3Title: '3. Filtration',
    step3Desc: 'Captured water undergoes multi-stage treatment to clear debris & turbidity.',
    step4Title: '4. City Reuse',
    step4Desc: 'Purified water is allocated for parks, irrigation, street washing & firefighting.',

    // 7 Phases
    phase1Title: '1. IoT Drain Sensing',
    phase1Desc: 'Ultrasonic sensors measure real-time water column depth every 5 seconds.',
    phase2Title: '2. Auto Diversion Valves',
    phase2Desc: 'Solenoid diverter valves trigger automatically at 75% depth threshold.',
    phase3Title: '3. Alerts & Early Warnings',
    phase3Desc: 'Instant SMS & portal notifications sent to residents and city emergency teams.',
    phase4Title: '4. Underground Storage Sump',
    phase4Desc: 'High-capacity subterranean sumps hold over 50,000L of storm runoff.',
    phase5Title: '5. Filtration & Quality Check',
    phase5Desc: 'Multi-stage mesh & sedimentation filtration purifies runoff for non-potable use.',
    phase6Title: '6. Municipality Control Center',
    phase6Desc: 'Central GIS map & system health portal for city engineers and operators.',
    phase7Title: '7. AI Flood Risk Engine',
    phase7Desc: 'Machine learning predicts flood saturation & rainfall runoff 4 hours in advance.',

    // Roles
    role1Title: 'Resident Operations',
    role1Desc: 'Live water gauges, flood early warnings, SOS emergency trigger, citizen complaint submission, and water reuse availability.',
    role2Title: 'Technician Suite',
    role2Desc: 'Hardware telemetry, ESP32 calibration, solenoid valve overrides, pump health inspections, and predictive maintenance schedules.',
    role3Title: 'Municipality Admin',
    role3Desc: 'City-wide flood GIS mapping, multi-system status aggregates, rapid emergency dispatch, and AI hydrological analytics.',

    // FAQs
    faq1Q: 'How does SUOWMRS detect and prevent urban flooding automatically?',
    faq1A: 'IoT ultrasonic sensors mounted inside drainage channels continuously measure water column depth. When levels breach the 75% depth threshold, the system automatically triggers solenoid diverter valves to open, funneling storm runoff into underground storage reservoirs before streets flood.',
    faq2Q: 'Is the collected flood water safe for municipal reuse?',
    faq2A: 'Yes! The collected water goes through an active treatment pipeline featuring multi-stage filtration. The purified water is designated for approved non-potable municipal uses such as agricultural irrigation, park gardening, street washing, and firefighter emergency reserves.',
    faq3Q: 'What role does the AI Flood Prediction Engine play?',
    faq3A: 'The Phase 7 AI Flood Engine combines live IoT telemetry, historical rainfall patterns, and real-time weather forecasts to calculate a Drainage Saturation Index (DSI). It predicts flood risk up to 4 hours in advance so city authorities can take proactive preventative actions.',
    faq4Q: 'Can field technicians manage hardware diagnostics remotely?',
    faq4A: 'Absolutely. Technicians have a dedicated Technician Suite allowing them to view ESP32 controller diagnostics, sensor calibration parameters, solenoid relay states, and log maintenance work orders directly from the platform.',

    // Features Showcase Section
    featuresBadge: 'System Capabilities',
    featuresTitle: 'Comprehensive Features & Platform Modules',
    featuresSubtitle: 'Everything you need to monitor, control, and reuse storm water across your city.',
    feat1Title: 'IoT Water Telemetry',
    feat1Desc: 'Real-time ultrasonic depth sensing, flow rates, RSSI signal telemetry across city wards.',
    feat2Title: 'Underground Sump Storage',
    feat2Desc: 'Subterranean holding sumps managing 50,000L+ storm runoff with active volume gauges.',
    feat3Title: 'Water Filtration & Reuse',
    feat3Desc: 'Multi-stage filtration feeding gardening, street cleaning, irrigation & firefighting.',
    feat4Title: 'AI Flood Prediction Engine',
    feat4Desc: 'Machine learning calculating Drainage Saturation Index (DSI) 4 hours in advance.',
    feat5Title: 'GIS Flood Map & Control Grid',
    feat5Desc: 'Interactive spatial mapping, ward flood risk heatmaps, and emergency team dispatch.',
    feat6Title: 'Citizen Portal & Emergency SOS',
    feat6Desc: 'Instant emergency SOS dispatch and geotagged community issue complaint portal.',
    feat7Title: 'Technician Maintenance Suite',
    feat7Desc: 'ESP32 controller diagnostics, sensor calibration, relay controls, and work order tickets.',
    feat8Title: 'Weather & Monsoon Forecast',
    feat8Desc: 'Rainfall radar integration, precipitation probability, and monsoon risk analytics.',

    automatedLifecycle: 'Automated Lifecycle',
    howItWorksTitle: 'How SUOWMRS Works in 4 Steps',
    architecturalBlueprint: 'Architectural Blueprint',
    explorePhase: 'Explore phase',
    faqTitle: 'Frequently Asked Questions',
    faqSubtitle: 'Got Questions? We Have Answers.',
  },
  hi: {
    appName: 'SUOWMRS',
    appSubtitle: 'जल निगरानी और पुनर्उपयोग',
    dashboard: 'अवलोकन',
    waterMonitoring: 'जल निगरानी',
    alerts: 'अलर्ट और इतिहास',
    storage: 'भूमिगत भंडारण',
    waterReuse: 'जल पुनर्उपयोग और गुणवत्ता',
    weather: 'मौसम पूर्वानुमान',
    complaints: 'नागरिक पोर्टल',
    sos: 'आपातकालीन SOS',
    maintenance: 'रखरखाव केंद्र',
    systemHealth: 'सिस्टम स्वास्थ्य',
    sensors: 'सेंसर और वाल्व',
    esp32Diagnostics: 'ईएसपी32 नियंत्रक',
    sensorDiagnostics: 'सेंसर और अंशांकन',
    componentsHealth: 'एक्चुएटर और रिले',
    workOrders: 'कार्य आदेश और टिकट',
    adminDashboard: 'नगरपालिका नियंत्रण',
    userApprovals: 'उपयोगकर्ता अनुमोदन',
    adminMap: 'GIS बाढ़ मानचित्र',
    adminSystems: 'मल्टी-सिस्टम ग्रिड',
    adminComplaints: 'नागरिक रिपोर्ट',
    adminAnalytics: 'पूर्वानुमान विश्लेषण',
    aiPrediction: 'एआई बाढ़ पूर्वानुमान',
    myProfile: 'मेरी प्रोफ़ाइल और पासवर्ड',
    signOut: 'साइन आउट',
    userVerificationTitle: 'उपयोगकर्ता सत्यापन और अनुमोदन',
    userVerificationDesc: 'नेटवर्क एक्सेस देने से पहले नए निवासी और तकनीशियन पंजीकरण का सत्यापन करें।',
    pending: 'लंबित',
    verified: 'सत्यापित',
    rejected: 'अस्वीकृत',
    all: 'सभी',
    refresh: 'रिफ़्रेश',
    searchUser: 'उपयोगकर्ता खोजें...',
    residentOps: 'निवासी संचालन',
    technicianSuite: 'तकनीशियन सूट',
    municipalityAdmin: 'नगरपालिका प्रशासन',
    live: 'लाइव',
    demoUser: 'डेमो उपयोगकर्ता',
    waterMonitoringTitle: 'जल निगरानी डैशबोर्ड',
    emergencySos: 'आपातकालीन SOS',
    reportIssue: 'समस्या रिपोर्ट करें',
    waterLevel: 'जल स्तर',
    undergroundStorage: 'भूमिगत भंडार',
    solenoidValve: 'सोलेनॉइड वाल्व',
    liveDrainageTrend: 'लाइव जल स्तर प्रवृत्ति',
    alertFeed: 'अलर्ट फ़ीड',
    treatmentTitle: 'जल उपचार और पुनर्उपयोग जीवनचक्र',
    approvedReuseChannels: 'स्वीकृत पुनर्उपयोग चैनल',
    gardening: 'बागवानी',
    cleaning: 'सफाई',
    irrigation: 'सिंचाई',
    construction: 'निर्माण',
    industrial: 'औद्योगिक',
    manualOverride: 'मैनुअल ओवरराइड',
    openValve: 'वाल्व खोलें',
    closeValve: 'वाल्व बंद करें',
    totalStored: 'कुल संग्रहित',
    treatedWater: 'उपचारित जल',
    availableReuse: 'पुनर्उपयोग के लिए उपलब्ध',
    language: 'भाषा',
    role: 'भूमिका',
    // Dynamic Backend Data & Alerts
    alert_normal: 'जल स्तर {level}% पर सामान्य। जल निकासी स्थिर।',
    alert_warning: 'सावधानी: जल स्तर बढ़कर {level}% हुआ। निगरानी जारी।',
    alert_danger: 'उच्च जोखिम: जल स्तर {level}% पर! डायवर्टर वाल्व स्वचालित रूप से खुला।',
    alert_critical: 'गंभीर बाढ़ चेतावनी: जल स्तर {level}%! आपातकालीन प्रोटोकॉल सक्रिय।',
    status_normal: 'सामान्य',
    status_warning: 'चेतावनी',
    status_danger: 'उच्च जोखिम',
    status_critical: 'गंभीर बाढ़',
    valve_diverting: 'प्रवाह मोड़ रहा है',
    valve_standby: 'स्टैंडबाय',
    valve_auto: 'स्वचालित',
    valve_manual: 'मैनुअल',
    activeTank: 'सक्रिय टैंक',
    current: 'वर्तमान',
    capacity: 'क्षमता',
    available: 'उपलब्ध',
    inflowRate: 'अंतर्प्रवाह दर',
    empty: 'खाली',
    full: 'भरा हुआ',
    minToday: 'न्यूनतम आज',
    avgToday: 'औसत आज',
    peakToday: 'चरम आज',
    unread: 'अपठित',
    noAlertsHealthy: 'कोई अलर्ट नहीं — सिस्टम स्वस्थ',
    autoUpdatesStream: 'लाइव Socket.io स्ट्रीम से स्वतः अपडेट',
    quality: 'गुणवत्ता',
    quality_good: 'उत्तम',
    quality_excellent: 'अति उत्तम',
    quality_moderate: 'मध्यम',
    collected: 'एकत्रित',
    efficiency: 'दक्षता',
    distributed: 'वितरित',
    treatmentPhase: 'चरण 4: संग्रहित अंतर्प्रवाह → निस्पंदन → स्वीकृत नगर वितरण',
    sensorsActive: 'सेंसर सक्रिय',
    offline: 'ऑफ़लाइन',

    // Landing Page & Footer Keys
    home: 'होम',
    residentPortal: 'निवासी पोर्टल',
    signIn: 'साइन इन',
    liveApp: 'लाइव ऐप',
    heroBadge: 'स्मार्ट भूमिगत ओवरफ्लो और जल निगरानी / पुनर्उपयोग प्रणाली',
    heroTitle1: 'आगामी पीढ़ी का एआई और आईओटी प्लेटफॉर्म',
    heroTitle2: 'बाढ़ रोकथाम और जल पुनर्उपयोग',
    heroDesc: 'SUOWMRS शहरी बाढ़ संकट को स्थायी जल परिसंपत्तियों में परिवर्तित करता है। वास्तविक समय नाले की सेंसिंग से लेकर भूमिगत ऑटो-डायवर्जन और एआई पूर्वानुमान तक।',
    sensorsMonitored: 'सेंसर मॉनिटर किए गए',
    liveWaterLevel: 'लाइव जल स्तर',
    storedWater: 'संग्रहित जल',
    autoValveStatus: 'ऑटो वाल्व स्थिति',
    totalFloodPrevented: 'कुल रोकथाम बाढ़ जल',
    activeIoTNodes: 'सक्रिय IoT सेंसर नोड्स',
    systemUptime: 'सिस्टम टेलीमेट्री अपटाइम',
    treatedWaterReused: 'उपचारित जल पुनर्उपयोग',
    ecosystemBlueprint: '7-चरण SUOWMRS पारिस्थितिकी तंत्र',
    tailoredExperience: '3 आवश्यक उपयोगकर्ता भूमिकाओं के लिए निर्मित',
    openResidentView: 'निवासी दृश्य खोलें',
    technicianHub: 'तकनीशियन हब',
    footerFoundation: 'SUOWMRS स्मार्ट जल मंच',
    allRightsReserved: 'सर्वाधिकार सुरक्षित।',
    step1Title: '1. IoT सेंसिंग',
    step1Desc: 'अल्ट्रासोनिक गहराई सेंसर हर 5 सेकंड में नाले के जल स्तर को ट्रैक करते हैं।',
    step2Title: '2. स्वतः डायवर्जन',
    step2Desc: '75% गहराई पर सोलेनॉइड वाल्व स्वतः खुलते हैं और पानी को भूमिगत मोड़ते हैं।',
    step3Title: '3. निस्पंदन',
    step3Desc: 'एकत्रित पानी मलबे और मैल को साफ करने के लिए बहु-स्तरीय उपचार से गुजरता है।',
    step4Title: '4. नगर पुनर्उपयोग',
    step4Desc: 'शुद्ध पानी पार्कों, सिंचाई, सड़क धुलाई और अग्निशमन के लिए आवंटित किया जाता है।',

    // 7 Phases
    phase1Title: '1. IoT नाला सेंसिंग',
    phase1Desc: 'अल्ट्रासोनिक सेंसर हर 5 सेकंड में वास्तविक समय जल गहराई मापते हैं।',
    phase2Title: '2. स्वतः डायवर्जन वाल्व',
    phase2Desc: '75% गहराई सीमा पर सोलेनॉइड डायवर्टर वाल्व स्वतः चालू होते हैं।',
    phase3Title: '3. अलर्ट और पूर्व चेतावनियां',
    phase3Desc: 'नागरिकों और आपातकालीन टीमों को तत्काल एसएमएस व पोर्टल सूचनाएं।',
    phase4Title: '4. भूमिगत भंडारण संप',
    phase4Desc: 'उच्च क्षमता वाले भूमिगत संप 50,000L से अधिक बाढ़ जल संचित करते हैं।',
    phase5Title: '5. निस्पंदन और गुणवत्ता जांच',
    phase5Desc: 'बहु-स्तरीय निस्पंदन पानी को गैर-पेयजल उपयोग के लिए शुद्ध करता है।',
    phase6Title: '6. नगरपालिका नियंत्रण केंद्र',
    phase6Desc: 'शहर के इंजीनियरों और ऑपरेटरों के लिए केंद्रीय जीआईएस मानचित्र और स्वास्थ्य पोर्टल।',
    phase7Title: '7. AI बाढ़ जोखिम इंजन',
    phase7Desc: 'मशीन लर्निंग 4 घंटे पहले ही बाढ़ संतृप्ति और वर्षा जल का पूर्वानुमान लगाती है।',

    // Roles
    role1Title: 'निवासी संचालन',
    role1Desc: 'लाइव जल गेज, बाढ़ पूर्व चेतावनी, एसओएस आपातकालीन ट्रिगर, नागरिक शिकायत और जल पुनर्उपयोग उपलब्ध।',
    role2Title: 'तकनीशियन सूट',
    role2Desc: 'हार्डवेयर टेलीमेट्री, ईएसपी32 अंशांकन, वाल्व ओवरराइड, पंप स्वास्थ्य जांच और निवारक रखरखाव शेड्यूल।',
    role3Title: 'नगरपालिका प्रशासन',
    role3Desc: 'शहर-व्यापी बाढ़ जीआईएस मैपिंग, मल्टी-सिस्टम स्थिति समुच्चय, त्वरित आपातकालीन प्रेषण और एआई जल विज्ञान विश्लेषण।',

    // FAQs
    faq1Q: 'SUOWMRS स्वचालित रूप से शहरी बाढ़ का पता कैसे लगाता है और इसे कैसे रोकता है?',
    faq1A: 'ड्रेनेज चैनलों के अंदर स्थापित आईओटी अल्ट्रासोनिक सेंसर लगातार जल स्तंभ की गहराई को मापते हैं। जब स्तर 75% की सीमा को पार करता है, तो प्रणाली स्वचालित रूप से सोलेनॉइड वाल्व खोलती है, जिससे पानी सड़कों पर भरने से पहले भूमिगत जलाशयों में चला जाता है।',
    faq2Q: 'क्या एकत्रित बाढ़ का पानी नगरपालिका के पुनर्उपयोग के लिए सुरक्षित है?',
    faq2A: 'हाँ! एकत्रित पानी बहु-स्तरीय निस्पंदन उपचार प्रक्रिया से गुजरता है। शुद्ध पानी पार्कों की बागवानी, सिंचाई, सड़क धुलाई और अग्निशमन रिजर्व के लिए स्वीकृत है।',
    faq3Q: 'AI बाढ़ पूर्वानुमान इंजन क्या भूमिका निभाता है?',
    faq3A: 'चरण 7 एआई इंजन आईओटी टेलीमेट्री, ऐतिहासिक वर्षा पैटर्न और मौसम पूर्वानुमान को मिलाकर ड्रेनेज संतृप्ति सूचकांक (DSI) की गणना करता है। यह 4 घंटे पहले तक बाढ़ के जोखिम की भविष्यवाणी करता है।',
    faq4Q: 'क्या फील्ड तकनीशियन दूरस्थ रूप से हार्डवेयर का प्रबंधन कर सकते हैं?',
    faq4A: 'बिल्कुल। तकनीशियनों के पास एक समर्पित तकनीशियन सूट है जिससे वे ESP32 नियंत्रक डायग्नोस्टिक्स, सेंसर अंशांकन और वाल्व रिले की जांच दूरस्थ रूप से कर सकते हैं।',

    // Features Showcase Section
    featuresBadge: 'सिस्टम क्षमताएं',
    featuresTitle: 'व्यापक विशेषताएं और प्लेटफ़ॉर्म मॉड्यूल',
    featuresSubtitle: 'आपके शहर में वर्षा जल की निगरानी, नियंत्रण और पुनर्उपयोग के लिए आवश्यक सब कुछ।',
    feat1Title: 'IoT जल टेलीमेट्री',
    feat1Desc: 'शहर के वार्डों में वास्तविक समय अल्ट्रासोनिक गहराई सेंसिंग, प्रवाह दर और आरएसएसआई सिग्नल टेलीमेट्री।',
    feat2Title: 'भूमिगत संप भंडारण',
    feat2Desc: 'सक्रिय आयतन गेज के साथ 50,000L+ वर्षा जल का प्रबंधन करने वाले भूमिगत होल्डिंग संप।',
    feat3Title: 'जल निस्पंदन और पुनर्उपयोग',
    feat3Desc: 'बागवानी, सड़क की सफाई, सिंचाई और अग्निशमन के लिए आपूर्ति करने वाला बहु-स्तरीय निस्पंदन।',
    feat4Title: 'AI बाढ़ जोखिम पूर्वानुमान',
    feat4Desc: 'मशीन लर्निंग द्वारा 4 घंटे पहले ही जल निकासी संतृप्ति सूचकांक (DSI) की गणना।',
    feat5Title: 'GIS बाढ़ मानचित्र और ग्रिड',
    feat5Desc: 'इंटरएक्टिव स्थानिक मैपिंग, वार्ड बाढ़ जोखिम हीटमैप और आपातकालीन टीम प्रेषण।',
    feat6Title: 'नागरिक पोर्टल और आपातकालीन SOS',
    feat6Desc: 'त्वरित आपातकालीन एसओएस प्रेषण और जियोटैग की गई सामुदायिक समस्या रिपोर्टिंग पोर्टल।',
    feat7Title: 'तकनीशियन रखरखाव सूट',
    feat7Desc: 'ESP32 नियंत्रक डायग्नोस्टिक्स, सेंसर अंशांकन, वाल्व रिले नियंत्रण और कार्य आदेश।',
    feat8Title: 'मौसम और मानसून पूर्वानुमान',
    feat8Desc: 'वर्षा रडार एकीकरण, वर्षा की संभावना और मानसून जोखिम विश्लेषण।',

    automatedLifecycle: 'स्वचालित जीवनचक्र',
    howItWorksTitle: '4 चरणों में SUOWMRS कैसे काम करता है',
    architecturalBlueprint: 'वास्तुकला की रूपरेखा',
    explorePhase: 'चरण देखें',
    faqTitle: 'अक्सर पूछे जाने वाले प्रश्न',
    faqSubtitle: 'क्या आपके पास प्रश्न हैं? हमारे पास उत्तर हैं।',
  },
  or: {
    appName: 'SUOWMRS',
    appSubtitle: 'ଜଳ ଅନୁବୀକ୍ଷଣ ଓ ପୁନର୍ ବ୍ୟବହାର',
    dashboard: 'ସଂକ୍ଷିପ୍ତ ବିବରଣ',
    waterMonitoring: 'ଜଳ ଅନୁବୀକ୍ଷଣ',
    alerts: 'ସତର୍କତା ଓ ଇତିହାସ',
    storage: 'ଭୂ-ସଂରକ୍ଷଣ',
    waterReuse: 'ଜଳ ପୁନର୍ ବ୍ୟବହାର',
    weather: 'ପାଣିପାଗ ପୂର୍ବାନୁମାନ',
    complaints: 'ନାଗରିକ ପୋର୍ଟାଲ',
    sos: 'ଜରୁରୀ SOS',
    maintenance: 'ରକ୍ଷଣାବେକ୍ଷଣ',
    systemHealth: 'ସିଷ୍ଟମ ସ୍ୱାସ୍ଥ୍ୟ',
    sensors: 'ସେନ୍ସର ଓ ଭାଲ୍ଭ',
    esp32Diagnostics: 'ESP32 ନିୟନ୍ତ୍ରକ',
    sensorDiagnostics: 'ସେନ୍ସର ଓ କାଲିବ୍ରେସନ୍',
    componentsHealth: 'ଆକ୍ଚୁଏଟର ଓ ରିଲେ',
    workOrders: 'କାର୍ଯ୍ୟ ଆଦେଶ ଓ ଟିକେଟ',
    adminDashboard: 'ମ୍ୟୁନିସିପାଲ ନିୟନ୍ତ୍ରଣ',
    userApprovals: 'ଉପଭୋକ୍ତା ଅନୁମୋଦନ',
    adminMap: 'GIS ବନ୍ୟା ମାନଚିତ୍ର',
    adminSystems: 'ବହୁ-ସିଷ୍ଟମ ଗ୍ରିଡ',
    adminComplaints: 'ନାଗରିକ ରିପୋର୍ଟ',
    adminAnalytics: 'ପୂର୍ବାନୁମାନ ବିଶ୍ଳେଷଣ',
    aiPrediction: 'AI ବନ୍ୟା ପୂର୍ବାନୁମାନ',
    myProfile: 'ମୋର ପ୍ରୋଫାଇଲ୍ ଓ ପାସୱାର୍ଡ',
    signOut: 'ସାଇନ୍ ଆଉଟ୍',
    userVerificationTitle: 'ଉପଭୋକ୍ତା ଯାଞ୍ଚ ଓ ଅନୁମୋଦନ',
    userVerificationDesc: 'ନେଟୱାର୍କ ପ୍ରବେଶ ଅନୁମତି ଦେବା ପୂର୍ବରୁ ଆସୁଥିବା ନିବାସୀ ଓ ଟେକ୍ନିସିଆନ ପଞ୍ଜୀକରଣ ଯାଞ୍ଚ କରନ୍ତୁ।',
    pending: 'ବିଚାରାଧୀନ',
    verified: 'ଯାଞ୍ଚ ହୋଇଛି',
    rejected: 'ଅଗ୍ରାହ୍ୟ',
    all: 'ସମସ୍ତ',
    refresh: 'ରିଫ୍ରେସ',
    searchUser: 'ଉପଭୋକ୍ତା ଖୋଜନ୍ତୁ...',
    residentOps: 'ନିବାସୀ କାର୍ଯ୍ୟ',
    technicianSuite: 'ଟେକ୍ନିସିଆନ ସ୍ୟୁଟ',
    municipalityAdmin: 'ମ୍ୟୁନିସିପାଲ ପ୍ରଶାସନ',
    live: 'ସରଜୀବ',
    demoUser: 'ଡେମୋ ଉପଯୋଗକର୍ତ୍ତା',
    waterMonitoringTitle: 'ଜଳ ଅନୁବୀକ୍ଷଣ ଡ୍ୟାଶବୋର୍ଡ',
    emergencySos: 'ଜରୁରୀ SOS',
    reportIssue: 'ସମସ୍ୟା ଜଣାନ୍ତୁ',
    waterLevel: 'ଜଳ ସ୍ତର',
    undergroundStorage: 'ଭୂ-ଭଣ୍ଡାର',
    solenoidValve: 'ସୋଲେନୋଇଡ ଭାଲ୍ଭ',
    liveDrainageTrend: 'ସଜୀବ ଜଳ ସ୍ତର ଧାରା',
    alertFeed: 'ସତର୍କତା ଫିଡ',
    treatmentTitle: 'ଜଳ ଶୋଧନ ଓ ପୁନର୍ ବ୍ୟବହାର ଚକ୍ର',
    approvedReuseChannels: 'ଅନୁମୋଦିତ ପୁନର୍ ବ୍ୟବହାର ଚ୍ୟାନେଲ',
    gardening: 'ବଗିଚା',
    cleaning: 'ଯାନ ସଫା',
    irrigation: 'ଜଳସେଚନ',
    construction: 'ନିର୍ମାଣ',
    industrial: 'ଶିଳ୍ପ',
    manualOverride: 'ମ୍ୟାନୁଆଲ ଓଭରରାଇଡ',
    openValve: 'ଭାଲ୍ଭ ଖୋଲନ୍ତୁ',
    closeValve: 'ଭାଲ୍ଭ ବନ୍ଦ କରନ୍ତୁ',
    totalStored: 'ମୋଟ ସଂଗ୍ରହ',
    treatedWater: 'ଶୋଧିତ ଜଳ',
    availableReuse: 'ପୁନର୍ ବ୍ୟବହାର ଯୋଗ୍ୟ',
    language: 'ଭାଷା',
    role: 'ଭୂମିକା',
    // Dynamic Backend Data & Alerts
    alert_normal: 'ଜଳ ସ୍ତର {level}% ରେ ସ୍ୱାଭାବିକ। ନିଷ୍କାସନ ସ୍ଥିର।',
    alert_warning: 'ସତର୍କତା: ଜଳ ସ୍ତର ବୃଦ୍ଧି ପାଇ {level}% ହୋଇଛି। ନଜର ରଖାଯାଇଛି।',
    alert_danger: 'ଉଚ୍ଚ ବିପଦ: ଜଳ ସ୍ତର {level}%! ଡାଇଭର୍ଟର ଭାଲ୍ଭ ଆପେ ଖୋଲିଲା।',
    alert_critical: 'ଜରୁରୀ ବନ୍ୟା ସତର୍କତା: ଜଳ ସ୍ତର {level}%! ଜରୁରୀ ପଦକ୍ଷେପ ସକ୍ରିୟ।',
    status_normal: 'ସ୍ୱାଭାବିକ',
    status_warning: 'ସତର୍କତା',
    status_danger: 'ଉଚ୍ଚ ବିପଦ',
    status_critical: 'ଜରୁରୀ ବନ୍ୟା',
    valve_diverting: 'ପ୍ରବାହ ମୋଡ଼ାଯାଉଛି',
    valve_standby: 'ଷ୍ଟାଣ୍ଡବାଇ',
    valve_auto: 'ସ୍ୱୟଂଚାଳିତ',
    valve_manual: 'ମ୍ୟାନୁଆଲ',
    activeTank: 'ସକ୍ରିୟ ଟାଙ୍କି',
    current: 'ବର୍ତ୍ତମାନ',
    capacity: 'କ୍ଷମତା',
    available: 'ଉପଲବ୍ଧ',
    inflowRate: 'ପ୍ରବେଶ ହାର',
    empty: 'ଖାଲି',
    full: 'ପୂର୍ଣ୍ଣ',
    minToday: 'ସର୍ବନିମ୍ନ ଆଜି',
    avgToday: 'ହାରାହାରି ଆଜି',
    peakToday: 'ସର୍ବୋଚ୍ଚ ଆଜି',
    unread: 'ଅପଠିତ',
    noAlertsHealthy: 'କୌଣସି ସତର୍କତା ନାହିଁ — ସିଷ୍ଟମ ସୁରକ୍ଷିତ',
    autoUpdatesStream: 'ଲାଇଭ Socket.io ଷ୍ଟ୍ରିମରୁ ସ୍ୱତଃ ଅପଡେଟ',
    quality: 'ଗୁଣବତ୍ତା',
    quality_good: 'ଉତ୍ତମ',
    quality_excellent: 'ଅତି ଉତ୍ତମ',
    quality_moderate: 'ମଧ୍ୟମ',
    collected: 'ସଂଗୃହିତ',
    efficiency: 'ଦକ୍ଷତା',
    distributed: 'ବଣ୍ଟିତ',
    treatmentPhase: 'ପର୍ଯ୍ୟାୟ ୪: ସଂରକ୍ଷିତ ଜଳ → ଶୋଧନ → ପୌର ବିତରଣ',
    sensorsActive: 'ସେନ୍ସର ସକ୍ରିୟ',
    offline: 'ଅଫଲାଇନ',

    // Landing Page & Footer Keys
    home: 'ଗୃହ',
    residentPortal: 'ନିବାସୀ ପୋର୍ଟାଲ',
    signIn: 'ସାଇନ୍ ଇନ୍',
    liveApp: 'ଲାଇଭ୍ ଆପ୍',
    heroBadge: 'ସ୍ମାର୍ଟ ଭୂତଳ ଜଳ ନିଷ୍କାସନ, ଅନୁବୀକ୍ଷଣ ଓ ପୁନର୍ ବ୍ୟବହାର ବ୍ୟବସ୍ଥା',
    heroTitle1: 'ନୂତନ ପିଢ଼ିର AI ଓ IoT ମଞ୍ଚ',
    heroTitle2: 'ବନ୍ୟା ରୋକିବା ଓ ଜଳ ପୁନର୍ ବ୍ୟବହାର',
    heroDesc: 'SUOWMRS ସହରାଞ୍ଚଳ ବନ୍ୟା ସମସ୍ୟାକୁ ଜଳ ସମ୍ପଦରେ ପରିଣତ କରେ। ନାଳର ସଜୀବ ଅନୁବୀକ୍ଷଣରୁ ଭୂତଳ ମୋଡ଼ ଓ AI ପୂର୍ବାନୁମାନ ପର୍ଯ୍ୟନ୍ତ।',
    sensorsMonitored: 'ସେନ୍ସର ଅନୁବୀକ୍ଷିତ',
    liveWaterLevel: 'ସଜୀବ ଜଳ ସ୍ତର',
    storedWater: 'ସଂରକ୍ଷିତ ଜଳ',
    autoValveStatus: 'ଅଟୋ ଭାଲ୍ଭ ସ୍ଥିତି',
    totalFloodPrevented: 'ମୋଟ ବନ୍ୟା ରୋକାଯାଇଥିବା ପରିମାଣ',
    activeIoTNodes: 'ସକ୍ରିୟ IoT ସେନ୍ସର ନୋଡ୍',
    systemUptime: 'ସିଷ୍ଟମ ଅପଟାଇମ',
    treatedWaterReused: 'ଶୋଧିତ ଜଳ ପୁନର୍ବ୍ୟବହୃତ',
    ecosystemBlueprint: '7-ପର୍ଯ୍ୟାୟ SUOWMRS ବ୍ୟବସ୍ଥା',
    tailoredExperience: '3 ଆବଶ୍ୟକୀୟ ଭୂମିକା ପାଇଁ ନିର୍ମିତ',
    openResidentView: 'ନିବାସୀ ଦୃଶ୍ୟ ଖୋଲନ୍ତୁ',
    technicianHub: 'ଟେକ୍ନିସିଆନ ହବ୍',
    footerFoundation: 'SUOWMRS ସ୍ମାର୍ଟ ଜଳ ମଞ୍ଚ',
    allRightsReserved: 'ସର୍ବାଧିକାର ସୁରକ୍ଷିତ।',
    step1Title: '୧. IoT ସେନ୍ସିଂ',
    step1Desc: 'ଅଲ୍ଟ୍ରାସୋନିକ ଗଭୀରତା ସେନ୍ସର ପ୍ରତି ୫ ସେକେଣ୍ଡରେ ନାଳର ଜଳ ସ୍ତର ଟ୍ରାକ୍ କରନ୍ତି।',
    step2Title: '୨. ସ୍ୱୟଂଚାଳିତ ମୋଡ଼',
    step2Desc: '୭୫% ଗଭୀରତାରେ ସୋଲେନୋଇଡ ଭାଲ୍ଭ ଆପେ ଖୋଲି ଜଳକୁ ଭୂତଳକୁ ପଠାଏ।',
    step3Title: '୩. ବିଶୋଧନ',
    step3Desc: 'ସଂଗୃହିତ ଜଳ ଆବର୍ଜନା ଓ ଅଳିଆ ସଫା ପାଇଁ ବହୁ-ସ୍ତରୀୟ ଶୋଧନ ଦେଇ ଗତି କରେ।',
    step4Title: '୪. ପୌର ପୁନର୍ବ୍ୟବହାର',
    step4Desc: 'ଶୋଧିତ ଜଳ ବଗିଚା, ଜଳସେଚନ, ରାସ୍ତା ସଫା ଓ ନିଆଁ ଲିଭାଇବା ପାଇଁ ବଣ୍ଟନ କରାଯାଏ।',

    // 7 Phases
    phase1Title: '୧. IoT ନାଳ ଅନୁବୀକ୍ଷଣ',
    phase1Desc: 'ଅଲ୍ଟ୍ରାସୋନିକ ସେନ୍ସର ପ୍ରତି ୫ ସେକେଣ୍ଡରେ ଜଳ ଗଭୀରତା ମାପନ୍ତି।',
    phase2Title: '୨. ସ୍ୱୟଂଚାଳିତ ମୋଡ଼ ଭାଲ୍ଭ',
    phase2Desc: '୭୫% ଗଭୀରତାରେ ସୋଲେନୋଇଡ ଭାଲ୍ଭ ସ୍ୱତଃ ଖୋଲିଯାଏ।',
    phase3Title: '୩. ସତର୍କତା ଓ ପୂର୍ବ ସୂଚନା',
    phase3Desc: 'ନାଗରିକ ଓ ଜରୁରୀକାଳୀନ ଦଳକୁ ତୁରନ୍ତ SMS ଓ ପୋର୍ଟାଲ୍ ସୂଚନା।',
    phase4Title: '୪. ଭୂତଳ ଜଳ ଭଣ୍ଡାର',
    phase4Desc: 'ଉଚ୍ଚ କ୍ଷମତା ସମ୍ପନ୍ନ ଭୂତଳ ଭଣ୍ଡାର ୫୦,୦୦୦L ରୁ ଅଧିକ ଜଳ ସଂରକ୍ଷଣ କରେ।',
    phase5Title: '୫. ଶୋଧନ ଓ ଗୁଣବତ୍ତା ଯାଞ୍ଚ',
    phase5Desc: 'ବହୁ-ସ୍ତରୀୟ ବିଶୋଧନ ଜଳକୁ ପୁନର୍ ବ୍ୟବହାର ଯୋଗ୍ୟ କରେ।',
    phase6Title: '୬. ମ୍ୟୁନିସିପାଲିଟି ନିୟନ୍ତ୍ରଣ କେନ୍ଦ୍ର',
    phase6Desc: 'ଇଞ୍ଜିନିୟରମାନଙ୍କ ପାଇଁ କେନ୍ଦ୍ରୀୟ GIS ମାନଚିତ୍ର ଓ ସିଷ୍ଟମ ପୋର୍ଟାଲ।',
    phase7Title: '୭. AI ବନ୍ୟା ପୂର୍ବାନୁମାନ',
    phase7Desc: 'AI ସିଷ୍ଟମ ୪ ଘଣ୍ଟା ପୂର୍ବରୁ ବନ୍ୟା ବିପଦର ପୂର୍ବାନୁମାନ କରେ।',

    // Roles
    role1Title: 'ନିବାସୀ କାର୍ଯ୍ୟ',
    role1Desc: 'ସଜୀବ ଜଳ ମାପକ, ବନ୍ୟା ପୂର୍ବ ସୂଚନା, SOS ଜରୁରୀକାଳୀନ ସେବା, ନାଗରିକ ଅଭିଯୋଗ ଓ ଜଳ ପୁନର୍ବ୍ୟବହାର।',
    role2Title: 'ଟେକ୍ନିସିଆନ ସ୍ୟୁଟ',
    role2Desc: 'ହାର୍ଡୱେର୍ ଟେଲିମେଟ୍ରି, ESP32 କାଲିବ୍ରେସନ୍, ଭାଲ୍ଭ ନିୟନ୍ତ୍ରଣ ଓ ରକ୍ଷଣାବେକ୍ଷଣ ସମୟସୂଚୀ।',
    role3Title: 'ମ୍ୟୁନିସିପାଲ ପ୍ରଶାସନ',
    role3Desc: 'ସହର-ବ୍ୟାପୀ GIS ବନ୍ୟା ମାନଚିତ୍ର, ବହୁ-ସିଷ୍ଟମ ସ୍ଥିତି, ଜରୁରୀ ସେବା ଓ AI ବିଶ୍ଳେଷଣ।',

    // FAQs
    faq1Q: 'SUOWMRS କିପରି ସ୍ୱୟଂଚାଳିତ ଭାବରେ ବନ୍ୟା ଚିହ୍ନଟ ଓ ରୋକିଥାଏ?',
    faq1A: 'ନାଳ ଭିତରେ ଥିବା IoT ଅଲ୍ଟ୍ରାସୋନିକ ସେନ୍ସର ପ୍ରତି ମୁହୂର୍ତ୍ତରେ ଜଳ ଗଭୀରତା ମାପନ୍ତି। ଜଳ ସ୍ତର ୭୫% ଟପିଲେ, ସୋଲେନୋଇଡ ଭାଲ୍ଭ ଆପେ ଖୋଲି ପାଣିକୁ ରାସ୍ତାକୁ ଆସିବା ପୂର୍ବରୁ ଭୂତଳ ଭଣ୍ଡାରକୁ ପଠାଇଦିଏ।',
    faq2Q: 'ସଂଗୃହିତ ବନ୍ୟା ଜଳ ପୌର ପୁନର୍ ବ୍ୟବହାର ପାଇଁ ସୁରକ୍ଷିତ କି?',
    faq2A: 'ହଁ! ସଂଗୃହିତ ଜଳ ବହୁ-ସ୍ତରୀୟ ବିଶୋଧନ ଦେଇ ଗତି କରେ। ଏହି ପରିଷ୍କାର ଜଳ ବଗିଚା, ଜଳସେଚନ, ରାସ୍ତା ସଫା ଓ ଅଗ୍ନିଶମ ସେବା ପାଇଁ ବ୍ୟବହାର କରାଯାଏ।',
    faq3Q: 'AI ବନ୍ୟା ପୂର୍ବାନୁମାନର ଭୂମିକା କ’ଣ?',
    faq3A: 'AI ଇଞ୍ଜିନ୍ IoT ଟେଲିମେଟ୍ରି, ବର୍ଷା ତଥ୍ୟ ଓ ପାଣିପାଗ ପୂର୍ବାନୁମାନ ମିଶାଇ ୪ ଘଣ୍ଟା ପୂର୍ବରୁ ବନ୍ୟା ସମ୍ଭାବନା ଆକଳନ କରେ।',
    faq4Q: 'ଟେକ୍ନିସିଆନମାନେ ଦୂରରୁ ହାର୍ଡୱେର ଯାଞ୍ଚ କରିପାରିବେ କି?',
    faq4A: 'ନିଶ୍ଚିତ ଭାବରେ। ଟେକ୍ନିସିଆନ ସ୍ୟୁଟ୍ ମାଧ୍ୟମରେ ESP32 ନିୟନ୍ତ୍ରକ, ସେନ୍ସର ଓ ଭାଲ୍ଭର ସ୍ଥିତି ଦୂରରୁ ନିୟନ୍ତ୍ରଣ ଓ ଯାଞ୍ଚ କରାଯାଇପାରିବ।',

    // Features Showcase Section
    featuresBadge: 'ସିଷ୍ଟମ କ୍ଷମତା',
    featuresTitle: 'ସମ୍ପୂର୍ଣ୍ଣ ବୈଶିଷ୍ଟ୍ୟ ଓ ପ୍ଲାଟଫର୍ମ ମଡ୍ୟୁଲ୍',
    featuresSubtitle: 'ଆପଣଙ୍କ ସହରର ବନ୍ୟା ଜଳ ଅନୁବୀକ୍ଷଣ, ନିୟନ୍ତ୍ରଣ ଓ ପୁନର୍ ବ୍ୟବହାର ପାଇଁ ସବୁକିଛି।',
    feat1Title: 'IoT ଜଳ ଟେଲିମେଟ୍ରି',
    feat1Desc: 'ସହରର ୱାର୍ଡଗୁଡ଼ିକରେ ସଜୀବ ଅଲ୍ଟ୍ରାସୋନିକ ଗଭୀରତା, ପ୍ରବାହ ହାର ଓ RSSI ସିଗନାଲ।',
    feat2Title: 'ଭୂତଳ ଜଳ ଭଣ୍ଡାର',
    feat2Desc: '୫୦,୦୦୦L ରୁ ଅଧିକ ଜଳ ସଂରକ୍ଷଣ କରୁଥିବା ଭୂତଳ ଭଣ୍ଡାର ଓ ସଜୀବ ଗେଜ୍।',
    feat3Title: 'ଜଳ ଶୋଧନ ଓ ପୁନର୍ ବ୍ୟବହାର',
    feat3Desc: 'ବଗିଚା, ରାସ୍ତା ସଫା, ଜଳସେଚନ ଓ ଅଗ୍ନିଶମ ସେବା ପାଇଁ ବହୁ-ସ୍ତରୀୟ ଶୋଧନ।',
    feat4Title: 'AI ବନ୍ୟା ପୂର୍ବାନୁମାନ',
    feat4Desc: 'AI ଦ୍ୱାରା ୪ ଘଣ୍ଟା ପୂର୍ବରୁ ଜଳ ନିଷ୍କାସନ ସଂପୃକ୍ତି ସୂଚକାଙ୍କ (DSI) ଆକଳନ।',
    feat5Title: 'GIS ବନ୍ୟା ମାନଚିତ୍ର ଓ ଗ୍ରିଡ',
    feat5Desc: 'ଇଣ୍ଟରାକ୍ଟିଭ୍ ମାନଚିତ୍ର, ୱାର୍ଡ ବନ୍ୟା ହିଟମ୍ୟାପ୍ ଓ ଜରୁରୀକାଳୀନ ଦଳ ପ୍ରେରଣ।',
    feat6Title: 'ନାଗରିକ ପୋର୍ଟାଲ ଓ SOS',
    feat6Desc: 'ତୁରନ୍ତ ଜରୁରୀକାଳୀନ SOS ଓ ନାଗରିକ ଅଭିଯୋଗ ରିପୋର୍ଟ ପୋର୍ଟାଲ।',
    feat7Title: 'ଟେକ୍ନିସିଆନ ରକ୍ଷଣାବେକ୍ଷଣ ସ୍ୟୁଟ',
    feat7Desc: 'ESP32 ନିୟନ୍ତ୍ରକ, ସେନ୍ସର କାଲିବ୍ରେସନ୍, ରିଲେ ନିୟନ୍ତ୍ରଣ ଓ ଟିକେଟ।',
    feat8Title: 'ପାଣିପାଗ ଓ ବର୍ଷା ପୂର୍ବାନୁମାନ',
    feat8Desc: 'ବର୍ଷା ରାଡାର, ବର୍ଷା ସମ୍ଭାବନା ଓ ମୌସୁମୀ ବିପଦ ବିଶ୍ଳେଷଣ।',

    automatedLifecycle: 'ସ୍ୱୟଂଚାଳିତ ଚକ୍ର',
    howItWorksTitle: '୪ ପର୍ଯ୍ୟାୟରେ SUOWMRS କିପରି କାମ କରେ',
    architecturalBlueprint: 'ବ୍ୟବସ୍ଥାର ରୂପରେଖ',
    explorePhase: 'ପର୍ଯ୍ୟାୟ ଦେଖନ୍ତୁ',
    faqTitle: 'ବାରମ୍ବାର ପଚରାଯାଉଥିବା ପ୍ରଶ୍ନ',
    faqSubtitle: 'ଆପଣଙ୍କର ପ୍ରଶ୍ନ ଅଛି? ଆମ ପାଖରେ ଉତ୍ତର ଅଛି।',
  },
  te: {
    appName: 'SUOWMRS',
    appSubtitle: 'నీటి పర్యవేక్షణ & పునర్వినియోగం',
    dashboard: 'అవలోకనం',
    waterMonitoring: 'నీటి పర్యవేక్షణ',
    alerts: 'హెచ్చరికలు & చరిత్ర',
    storage: 'భూగర్భ నిల్వ',
    waterReuse: 'నీటి పునర్వినియోగం',
    weather: 'వాతావరణ అంచనా',
    complaints: 'పౌర పోర్టల్',
    sos: 'అత్యవసర SOS',
    maintenance: 'నిర్వహణ కేంద్రం',
    systemHealth: 'సిస్టమ్ ఆరోగ్యం',
    sensors: 'సెన్సర్లు & వాల్వులు',
    esp32Diagnostics: 'ESP32 కంట్రోలర్',
    sensorDiagnostics: 'సెన్సార్లు & అమరిక',
    componentsHealth: 'యాక్చుయేటర్లు & రిలేలు',
    workOrders: 'పని ఆర్డర్లు & టిక్కెట్లు',
    adminDashboard: 'మున్సిపాలిటీ నియంత్రణ',
    userApprovals: 'వినియోగదారుల ఆమోదాలు',
    adminMap: 'GIS వరద మ్యాపింగ్',
    adminSystems: 'మల్టీ-సిస్టమ్ గ్రిడ్',
    adminComplaints: 'పౌర నివేదికలు',
    adminAnalytics: 'అంచనా విశ్లేషణ',
    aiPrediction: 'AI వరద అంచనా',
    myProfile: 'నా ప్రొఫైల్ & పాస్‌వర్డ్',
    signOut: 'సైన్ అవుట్',
    userVerificationTitle: 'వినియోగదారు ధృవీకరణ & ఆమోదాలు',
    userVerificationDesc: 'యాక్సెస్ మంజూరు చేయడానికి ముందు కొత్త నివాసి మరియు టెక్నీషియన్ రిజిస్ట్రేషన్లను ధృవీకరించండి.',
    pending: 'పెండింగ్‌లో ఉంది',
    verified: 'ధృవీకరించబడింది',
    rejected: 'తిరస్కరించబడింది',
    all: 'అన్నీ',
    refresh: 'రిఫ్రెష్',
    searchUser: 'వినియోగదారులను శోధించండి...',
    residentOps: 'నివాసి కార్యకలాపాలు',
    technicianSuite: 'టెక్నీషియన్ స్యూట్',
    municipalityAdmin: 'మున్సిపాలిటీ అడ్మిన్',
    live: 'నేరుగా',
    demoUser: 'డెమో వినియోగదారు',
    waterMonitoringTitle: 'నీటి పర్యవేక్షణ డాష్‌బోర్డ్',
    emergencySos: 'అత్యవసర SOS',
    reportIssue: 'సమస్యను నివేదించండి',
    waterLevel: 'నీటి స్థాయి',
    undergroundStorage: 'భూగర్భ నిల్వ',
    solenoidValve: 'సోలెనాయిడ్ వాల్వ్',
    liveDrainageTrend: 'నేరుగా నీటి స్థాయి ధోరణి',
    alertFeed: 'హెచ్చరిక ఫీడ్',
    treatmentTitle: 'నీటి శుద్ధి & పునర్వినియోగ జీవిత చక్రం',
    approvedReuseChannels: 'ఆమోదించిన పునర్వినియోగ ఛానెల్లు',
    gardening: 'తోటపని',
    cleaning: 'శుభ్రత',
    irrigation: 'నీటిపారుదల',
    construction: 'నిర్మాణం',
    industrial: 'పారిశ్రామిక',
    manualOverride: 'మాన్యువల్ ఓవర్‌రైడ్',
    openValve: 'వాల్వ్ తెరవండి',
    closeValve: 'వాల్వ్ మూయండి',
    totalStored: 'మొత్తం నిల్వ',
    treatedWater: 'శుద్ధి చేసిన నీరు',
    availableReuse: 'పునర్వినియోగానికి అందుబాటులో',
    language: 'భాష',
    role: 'పాత్ర',
    // Dynamic Backend Data & Alerts
    alert_normal: 'నీటి స్థాయి {level}% వద్ద సాధారణం. డ్రైనేజ్ ప్రవాహం స్థిరంగా ఉంది.',
    alert_warning: 'హెచ్చరిక: నీటి స్థాయి {level}% కి పెరుగుతోంది. నిశితంగా పర్యవేక్షిస్తున్నారు.',
    alert_danger: 'అధిక ప్రమాదం: నీటి స్థాయి {level}% వద్ద ఉంది! డైవర్టర్ వాల్వ్ ఆటోమేటిక్‌గా తెరవబడింది.',
    alert_critical: 'తీవ్రమైన వరద హెచ్చరిక: నీటి స్థాయి {level}% వద్ద ఉంది! అత్యవసర ప్రోటోకాల్ సక్రియం.',
    status_normal: 'సాధారణం',
    status_warning: 'హెచ్చరిక',
    status_danger: 'అధిక ప్రమాదం',
    status_critical: 'తీవ్రమైన వరద',
    valve_diverting: 'ప్రవాహాన్ని మళ్లిస్తోంది',
    valve_standby: 'స్టాండ్‌బై',
    valve_auto: 'ఆటోమేటిక్',
    valve_manual: 'మాన్యువల్',
    activeTank: 'యాక్టివ్ ట్యాంక్',
    current: 'ప్రస్తుతం',
    capacity: 'సామర్థ్యం',
    available: 'అందుబాటులో ఉంది',
    inflowRate: 'ఇన్‌ఫ్లో రేటు',
    empty: 'ఖాళీ',
    full: 'నిండినది',
    minToday: 'ఈ రోజు కనిష్టం',
    avgToday: 'ఈ రోజు సగటు',
    peakToday: 'ఈ రోజు గరిష్టం',
    unread: 'చదవనివి',
    noAlertsHealthy: 'హెచ్చరికలు లేవు — సిస్టమ్ సురక్షితం',
    autoUpdatesStream: 'లైవ్ Socket.io స్ట్రీమ్ నుండి ఆటో-అప్‌డేట్‌లు',
    quality: 'నాణ్యత',
    quality_good: 'మంచిది',
    quality_excellent: 'అద్భుతమైనది',
    quality_moderate: 'మధ్యస్థం',
    collected: 'సేకరించబడినది',
    efficiency: 'సమర్థత',
    distributed: 'పంపిణీ చేయబడింది',
    treatmentPhase: 'దశ 4: నిల్వ ప్రవాహం → వడపోత → ఆమోదిత మున్సిపల్ పంపిణీ',
    sensorsActive: 'సెన్సార్లు సక్రియం',
    offline: 'ఆఫ్‌లైన్',
  },
  ta: {
    appName: 'SUOWMRS',
    appSubtitle: 'நீர் கண்காணிப்பு & மறுபயன்பாடு',
    dashboard: 'கண்ணோட்டம்',
    waterMonitoring: 'நீர் கண்காணிப்பு',
    alerts: 'எச்சரிக்கைகள் & வரலாறு',
    storage: 'நிலத்தடி சேமிப்பு',
    waterReuse: 'நீர் மறுபயன்பாடு',
    weather: 'வானிலை முன்னறிவிப்பு',
    complaints: 'குடிமக்கள் போர்டல்',
    sos: 'அவசர SOS',
    maintenance: 'பராமரிப்பு மையம்',
    systemHealth: 'கணினி ஆரோக்கியம்',
    sensors: 'சென்சார்கள் & வால்வுகள்',
    esp32Diagnostics: 'ESP32 கட்டுப்படுத்தி',
    sensorDiagnostics: 'சென்சார்கள் & அளவுத்திருத்தம்',
    componentsHealth: 'ஆக்சுவேட்டர்கள் & ரிலேக்கள்',
    workOrders: 'பணி ஆணைகள் & டிக்கெட்டுகள்',
    adminDashboard: 'நகராட்சி கட்டுப்பாடு',
    userApprovals: 'பயனர் ஒப்புதல்கள்',
    adminMap: 'GIS வெள்ள வரைபடம்',
    adminSystems: 'பல-அமைப்பு கட்டம்',
    adminComplaints: 'குடிமக்கள் அறிக்கைகள்',
    adminAnalytics: 'கணிப்பு பகுப்பாய்வு',
    aiPrediction: 'AI வெள்ள முன்னறிவிப்பு',
    myProfile: 'எனது சுயவிவரம் & கடவுச்சொல்',
    signOut: 'வெளியேறு',
    userVerificationTitle: 'பயனர் சரிபார்ப்பு & ஒப்புதல்கள்',
    userVerificationDesc: 'அணுகல் வழங்குவதற்கு முன் புதிய குடியிருப்பாளர் மற்றும் தொழில்நுட்ப வல்லுநர் பதிவுகளை சரிபார்க்கவும்.',
    pending: 'நிலுவையில் உள்ளது',
    verified: 'சரிபார்க்கப்பட்டது',
    rejected: 'நிராகரிக்கப்பட்டது',
    all: 'அனைத்தும்',
    refresh: 'புதுப்பி',
    searchUser: 'பயனர்களைத் தேடு...',
    residentOps: 'குடியிருப்பாளர் செயல்பாடுகள்',
    technicianSuite: 'தொழில்நுட்பவியலாளர் தொகுப்பு',
    municipalityAdmin: 'நகராட்சி நிர்வாகம்',
    live: 'நேரடி',
    demoUser: 'டெமோ பயனர்',
    waterMonitoringTitle: 'நீர் கண்காணிப்பு டாஷ்போர்டு',
    emergencySos: 'அவசர SOS',
    reportIssue: 'சிக்கலை புகாரளிக்கவும்',
    waterLevel: 'நீர் மட்டம்',
    undergroundStorage: 'நிலத்தடி சேமிப்பு',
    solenoidValve: 'சோலினாய்டு வால்வு',
    liveDrainageTrend: 'நேரடி நீர் மட்ட போக்கு',
    alertFeed: 'எச்சரிக்கை ஊட்டம்',
    treatmentTitle: 'நீர் சுத்திகரிப்பு & மறுபயன்பாட்டு சுழற்சி',
    approvedReuseChannels: 'அங்கீகரிக்கப்பட்ட மறுபயன்பாட்டு சேனல்கள்',
    gardening: 'தோட்டக்கலை',
    cleaning: 'சுத்தம்',
    irrigation: 'நீர்ப்பாசனம்',
    construction: 'கட்டுமானம்',
    industrial: 'தொழில்துறை',
    manualOverride: 'கைமுறை மேலெழுதல்',
    openValve: 'வால்வு திறக்கவும்',
    closeValve: 'வால்வு மூடவும்',
    totalStored: 'மொத்தம் சேமிக்கப்பட்டது',
    treatedWater: 'சுத்திகரிக்கப்பட்ட நீர்',
    availableReuse: 'மறுபயன்பாட்டிற்கு கிடைக்கும்',
    language: 'மொழி',
    role: 'பங்கு',
    // Dynamic Backend Data & Alerts
    alert_normal: 'நீர் மட்டம் {level}% இல் சாதாரணமாக உள்ளது. வடிகால் சீராக உள்ளது.',
    alert_warning: 'எச்சரிக்கை: நீர் மட்டம் {level}% ஆக உயர்கிறது. தீவிர கண்காணிப்பு.',
    alert_danger: 'அதிக ஆபத்து: நீர் மட்டம் {level}%! மாற்று வால்வு தானாக திறக்கப்பட்டது.',
    alert_critical: 'தீவிர வெள்ள எச்சரிக்கை: நீர் மட்டம் {level}%! அவசரகால நெறிமுறை செயல்படுத்தப்பட்டது.',
    status_normal: 'இயல்பு',
    status_warning: 'எச்சரிக்கை',
    status_danger: 'அதிக ஆபத்து',
    status_critical: 'தீவிர வெள்ளம்',
    valve_diverting: 'நீர் திருப்பப்படுகிறது',
    valve_standby: 'தயார் நிலை',
    valve_auto: 'தானியங்கி',
    valve_manual: 'கைமுறை',
    activeTank: 'செயலில் உள்ள தொட்டி',
    current: 'தற்போதைய',
    capacity: 'கொள்ளளவு',
    available: 'கிடைக்கக்கூடியது',
    inflowRate: 'உள்வரவு விகிதம்',
    empty: 'வெற்று',
    full: 'முழு',
    minToday: 'இன்று குறைந்தபட்சம்',
    avgToday: 'இன்று சராசரி',
    peakToday: 'இன்று உச்சம்',
    unread: 'படிக்காதவை',
    noAlertsHealthy: 'எச்சரிக்கைகள் இல்லை — கணினி பாதுகாப்பானது',
    autoUpdatesStream: 'நேரலை Socket.io ஸ்ட்ரீமிலிருந்து தானாக புதுப்பிக்கப்படும்',
    quality: 'தரம்',
    quality_good: 'நல்லது',
    quality_excellent: 'சிறந்தது',
    quality_moderate: 'மிதமான',
    collected: 'சேகரிக்கப்பட்டது',
    efficiency: 'திறன்',
    distributed: 'விநியோகிக்கப்பட்டது',
    treatmentPhase: 'கட்டம் 4: சேமிக்கப்பட்ட நீர் → வடிகட்டுதல் → அங்கீகரிக்கப்பட்ட நகராட்சி விநியோகம்',
    sensorsActive: 'சென்சார்கள் செயலில் உள்ளன',
    offline: 'ஆஃப்லைன்',
  },
  bn: {
    appName: 'SUOWMRS',
    appSubtitle: 'জল পর্যবেক্ষণ ও পুনর্ব্যবহার',
    dashboard: 'সংক্ষিপ্ত বিবরণ',
    waterMonitoring: 'জল পর্যবেক্ষণ',
    alerts: 'সতর্কতা ও ইতিহাস',
    storage: 'ভূগর্ভস্থ সঞ্চয়',
    waterReuse: 'জল পুনর্ব্যবহার',
    weather: 'আবহাওয়ার পূর্বাভাস',
    complaints: 'নাগরিক পোর্টাল',
    sos: 'জরুরি SOS',
    maintenance: 'রক্ষণাবেক্ষণ কেন্দ্র',
    systemHealth: 'সিস্টেম স্বাস্থ্য',
    sensors: 'সেন্সর ও ভাল্ব',
    esp32Diagnostics: 'ESP32 কন্ট্রোলার',
    sensorDiagnostics: 'সেন্সর ও ক্রমাঙ্কন',
    componentsHealth: 'অ্যাকচুয়েটর ও রিলে',
    workOrders: 'কাজের আদেশ ও টিকিট',
    adminDashboard: 'পৌরসভা নিয়ন্ত্রণ',
    userApprovals: 'ব্যবহারকারী অনুমোদন',
    adminMap: 'GIS বন্যা মানচিত্র',
    adminSystems: 'মাল্টি-সিস্টেম গ্রিড',
    adminComplaints: 'নাগরিক প্রতিবেদন',
    adminAnalytics: 'পূর্বাভাস বিশ্লেষণ',
    aiPrediction: 'এআই বন্যা পূর্বাভাস',
    myProfile: 'আমার প্রোফাইল এবং পাসওয়ার্ড',
    signOut: 'সাইন আউট',
    userVerificationTitle: 'ব্যবহারকারী যাচাইকরণ এবং অনুমোদন',
    userVerificationDesc: 'নেটওয়ার্ক অ্যাক্সেস দেওয়ার আগে নতুন বাসিন্দা এবং টেকনিশিয়ান রেজিস্ট্রেশন যাচাই করুন।',
    pending: 'বিবেচনাধীন',
    verified: 'যাচাইকৃত',
    rejected: 'প্রত্যাখ্যাত',
    all: 'সব',
    refresh: 'রিফ্রেশ',
    searchUser: 'ব্যবহারকারী খুঁজুন...',
    residentOps: 'বাসিন্দা কার্যক্রম',
    technicianSuite: 'টেকনিশিয়ান স্যুট',
    municipalityAdmin: 'পৌরসভা প্রশাসন',
    live: 'সরাসরি',
    demoUser: 'ডেমো ব্যবহারকারী',
    waterMonitoringTitle: 'জল পর্যবেক্ষণ ড্যাশবোর্ড',
    emergencySos: 'জরুরি SOS',
    reportIssue: 'সমস্যা রিপোর্ট করুন',
    waterLevel: 'জলের স্তর',
    undergroundStorage: 'ভূগর্ভস্থ সঞ্চয়',
    solenoidValve: 'সোলেনয়েড ভাল্ব',
    liveDrainageTrend: 'সরাসরি জলের স্তর প্রবণতা',
    alertFeed: 'সতর্কতা ফিড',
    treatmentTitle: 'জল পরিশোধন ও পুনর্ব্যবহার জীবনচক্র',
    approvedReuseChannels: 'অনুমোদিত পুনর্ব্যবহার চ্যানেল',
    gardening: 'বাগান',
    cleaning: 'পরিষ্কার',
    irrigation: 'সেচ',
    construction: 'নির্মাণ',
    industrial: 'শিল্প',
    manualOverride: 'ম্যানুয়াল ওভাররাইড',
    openValve: 'ভাল্ব খুলুন',
    closeValve: 'ভাল্ব বন্ধ করুন',
    totalStored: 'মোট সঞ্চিত',
    treatedWater: 'পরিশোধিত জল',
    availableReuse: 'পুনর্ব্যবহারের জন্য উপলব্ধ',
    language: 'ভাষা',
    role: 'ভূমিকা',
    // Dynamic Backend Data & Alerts
    alert_normal: 'জলের স্তর {level}% এ স্বাভাবিক। নিকাশী নিষ্কাশন স্থিতিশীল।',
    alert_warning: 'সতর্কতা: জলের স্তর বেড়ে {level}% হয়েছে। নিবিড় নজরদারি।',
    alert_danger: 'উচ্চ ঝুঁকি: জলের স্তর {level}%! ডাইভার্টার ভালভ স্বয়ংক্রিয়ভাবে খোলা হয়েছে।',
    alert_critical: 'গুরুতর বন্যা সতর্কতা: জলের স্তর {level}%! জরুরি প্রোটোকল সক্রিয়।',
    status_normal: 'স্বাভাবিক',
    status_warning: 'সতর্কতা',
    status_danger: 'উচ্চ ঝুঁকি',
    status_critical: 'গুরুতর বন্যা',
    valve_diverting: 'প্রবাহ পরিবর্তন হচ্ছে',
    valve_standby: 'স্ট্যান্ডবাই',
    valve_auto: 'স্বয়ংক্রিয়',
    valve_manual: 'ম্যানুয়াল',
    activeTank: 'সক্রিয় ট্যাঙ্ক',
    current: 'বর্তমান',
    capacity: 'ক্ষমতা',
    available: 'উপলব্ধ',
    inflowRate: 'প্রবাহের হার',
    empty: 'খালি',
    full: 'পূর্ণ',
    minToday: 'আজকের সর্বনিম্ন',
    avgToday: 'আজকের গড়',
    peakToday: 'আজকের সর্বোচ্চ',
    unread: 'অপঠিত',
    noAlertsHealthy: 'কোনো সতর্কতা নেই — সিস্টেম সুরক্ষিত',
    autoUpdatesStream: 'লাইভ Socket.io স্ট্রিম থেকে স্বয়ংক্রিয় আপডেট',
    quality: 'মান',
    quality_good: 'ভালো',
    quality_excellent: 'চমৎকার',
    quality_moderate: 'মাঝারি',
    collected: 'সংগৃহীত',
    efficiency: 'দক্ষতা',
    distributed: 'বিতরণকৃত',
    treatmentPhase: 'পর্যায় ৪: সঞ্চিত অন্তর্মুখী জল → পরিস্রাবণ → অনুমোদিত পৌর বন্টন',
    sensorsActive: 'সেন্সর সক্রিয়',
    offline: 'অফলাইন',
  },
};

const LanguageContext = createContext(null);

export function LanguageProvider({ children }) {
  const [lang, setLangState] = useState(() => {
    try {
      return localStorage.getItem('suowmrs_lang') || 'en';
    } catch {
      return 'en';
    }
  });

  const setLang = (newLang) => {
    setLangState(newLang);
    try {
      localStorage.setItem('suowmrs_lang', newLang);
    } catch (e) {
      console.warn('LocalStorage unavailable for language setting', e);
    }
  };

  const t = (key) => translations[lang]?.[key] ?? translations['en']?.[key] ?? key;

  // Helper to translate alerts dynamically with level interpolation
  const formatAlert = (alert) => {
    if (!alert) return '';
    const key = alert.messageKey || (alert.type ? `alert_${alert.type}` : null);
    const template = key ? t(key) : null;
    const levelStr = alert.level != null ? Number(alert.level).toFixed(1) : '—';
    if (template && template.includes('{level}')) {
      return template.replace('{level}', levelStr);
    }
    return alert.message || template || '';
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang, language: lang, changeLanguage: setLang, t, formatAlert, LANGUAGES }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error('useLanguage must be used within a LanguageProvider');
  return ctx;
}
